// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: basic_details.sql

package db

import (
	"context"
)

const getShopLogo = `-- name: GetShopLogo :one
SELECT brand_logo FROM basic_details WHERE webshop_brand_id = ?
`

// GetShopLogo
//
//	SELECT brand_logo FROM basic_details WHERE webshop_brand_id = ?
func (q *Queries) GetShopLogo(ctx context.Context, webshopBrandID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getShopLogo, webshopBrandID)
	var brand_logo string
	err := row.Scan(&brand_logo)
	return brand_logo, err
}
