// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cash_drawer.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const closeCashDrawerSession = `-- name: CloseCashDrawerSession :exec
UPDATE dg_pos_cash_drawer_sessions
SET
    closed_at = CURRENT_TIMESTAMP,
    session_ended_user_id = ?,
    closing_balance_expected = ?,
    difference = ?,
    total_in_amount = ?,
    total_out_amount = ?,
    total_sales_amount = ?,
    total_other_sales_amount = ?,
    total_refund_amount = ?,
    status = 'CLOSED',
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type CloseCashDrawerSessionParams struct {
	SessionEndedUserID     sql.NullInt64 `json:"session_ended_user_id"`
	ClosingBalanceExpected sql.NullInt32 `json:"closing_balance_expected"`
	Difference             sql.NullInt32 `json:"difference"`
	TotalInAmount          sql.NullInt32 `json:"total_in_amount"`
	TotalOutAmount         sql.NullInt32 `json:"total_out_amount"`
	TotalSalesAmount       sql.NullInt32 `json:"total_sales_amount"`
	TotalOtherSalesAmount  sql.NullInt32 `json:"total_other_sales_amount"`
	TotalRefundAmount      sql.NullInt32 `json:"total_refund_amount"`
	ID                     uint64        `json:"id"`
}

// CloseCashDrawerSession
//
//	UPDATE dg_pos_cash_drawer_sessions
//	SET
//	    closed_at = CURRENT_TIMESTAMP,
//	    session_ended_user_id = ?,
//	    closing_balance_expected = ?,
//	    difference = ?,
//	    total_in_amount = ?,
//	    total_out_amount = ?,
//	    total_sales_amount = ?,
//	    total_other_sales_amount = ?,
//	    total_refund_amount = ?,
//	    status = 'CLOSED',
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) CloseCashDrawerSession(ctx context.Context, arg *CloseCashDrawerSessionParams) error {
	_, err := q.db.ExecContext(ctx, closeCashDrawerSession,
		arg.SessionEndedUserID,
		arg.ClosingBalanceExpected,
		arg.Difference,
		arg.TotalInAmount,
		arg.TotalOutAmount,
		arg.TotalSalesAmount,
		arg.TotalOtherSalesAmount,
		arg.TotalRefundAmount,
		arg.ID,
	)
	return err
}

const createCashDrawer = `-- name: CreateCashDrawer :exec
INSERT INTO
    dg_pos_cash_drawer (
        outlet_id,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateCashDrawerParams struct {
	OutletID uint64 `json:"outlet_id"`
	IsActive bool   `json:"is_active"`
}

// CreateCashDrawer
//
//	INSERT INTO
//	    dg_pos_cash_drawer (
//	        outlet_id,
//	        is_active,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateCashDrawer(ctx context.Context, arg *CreateCashDrawerParams) error {
	_, err := q.db.ExecContext(ctx, createCashDrawer, arg.OutletID, arg.IsActive)
	return err
}

const createCashDrawerSession = `-- name: CreateCashDrawerSession :exec
INSERT INTO
    dg_pos_cash_drawer_sessions (
        cash_drawer_id,
        session_started_user_id,
        opened_at,
        opening_balance,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateCashDrawerSessionParams struct {
	CashDrawerID         uint64    `json:"cash_drawer_id"`
	SessionStartedUserID uint64    `json:"session_started_user_id"`
	OpenedAt             time.Time `json:"opened_at"`
	OpeningBalance       int32     `json:"opening_balance"`
}

// CreateCashDrawerSession
//
//	INSERT INTO
//	    dg_pos_cash_drawer_sessions (
//	        cash_drawer_id,
//	        session_started_user_id,
//	        opened_at,
//	        opening_balance,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateCashDrawerSession(ctx context.Context, arg *CreateCashDrawerSessionParams) error {
	_, err := q.db.ExecContext(ctx, createCashDrawerSession,
		arg.CashDrawerID,
		arg.SessionStartedUserID,
		arg.OpenedAt,
		arg.OpeningBalance,
	)
	return err
}

const getCashDrawerByOutletID = `-- name: GetCashDrawerByOutletID :one
SELECT id, outlet_id, is_active, created_at, updated_at FROM dg_pos_cash_drawer WHERE is_active AND outlet_id = ?
`

// GetCashDrawerByOutletID
//
//	SELECT id, outlet_id, is_active, created_at, updated_at FROM dg_pos_cash_drawer WHERE is_active AND outlet_id = ?
func (q *Queries) GetCashDrawerByOutletID(ctx context.Context, outletID uint64) (*DgPosCashDrawer, error) {
	row := q.db.QueryRowContext(ctx, getCashDrawerByOutletID, outletID)
	var i DgPosCashDrawer
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCashDrawerSessionByID = `-- name: GetCashDrawerSessionByID :one
SELECT
    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
    u_started.name AS session_started_user_name,
    u_started.key_id_name AS session_started_user_key_id_name,
    u_started.last_name AS session_started_user_last_name,
    u_started.key_id_last_name AS session_started_user_key_id_last_name,
    u_ended.name AS session_ended_user_name,
    u_ended.key_id_name AS session_ended_user_key_id_name,
    u_ended.last_name AS session_ended_user_last_name,
    u_ended.key_id_last_name AS session_ended_user_key_id_last_name
FROM
    dg_pos_cash_drawer_sessions cds
    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
    JOIN users u_started ON u_started.id = cds.session_started_user_id
    JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
WHERE
    cds.id = ?
`

type GetCashDrawerSessionByIDRow struct {
	ID                              uint64         `json:"id"`
	CashDrawerID                    uint64         `json:"cash_drawer_id"`
	SessionStartedUserID            uint64         `json:"session_started_user_id"`
	SessionEndedUserID              sql.NullInt64  `json:"session_ended_user_id"`
	OpenedAt                        time.Time      `json:"opened_at"`
	OpeningBalance                  int32          `json:"opening_balance"`
	ClosedAt                        sql.NullTime   `json:"closed_at"`
	ClosingBalanceCounted           sql.NullInt32  `json:"closing_balance_counted"`
	ClosingBalanceExpected          sql.NullInt32  `json:"closing_balance_expected"`
	Difference                      sql.NullInt32  `json:"difference"`
	TotalInAmount                   sql.NullInt32  `json:"total_in_amount"`
	TotalOutAmount                  sql.NullInt32  `json:"total_out_amount"`
	TotalSalesAmount                sql.NullInt32  `json:"total_sales_amount"`
	TotalOtherSalesAmount           sql.NullInt32  `json:"total_other_sales_amount"`
	TotalRefundAmount               sql.NullInt32  `json:"total_refund_amount"`
	Status                          string         `json:"status"`
	CreatedAt                       sql.NullTime   `json:"created_at"`
	UpdatedAt                       sql.NullTime   `json:"updated_at"`
	SessionStartedUserName          string         `json:"session_started_user_name"`
	SessionStartedUserKeyIDName     int32          `json:"session_started_user_key_id_name"`
	SessionStartedUserLastName      sql.NullString `json:"session_started_user_last_name"`
	SessionStartedUserKeyIDLastName int32          `json:"session_started_user_key_id_last_name"`
	SessionEndedUserName            string         `json:"session_ended_user_name"`
	SessionEndedUserKeyIDName       int32          `json:"session_ended_user_key_id_name"`
	SessionEndedUserLastName        sql.NullString `json:"session_ended_user_last_name"`
	SessionEndedUserKeyIDLastName   int32          `json:"session_ended_user_key_id_last_name"`
}

// GetCashDrawerSessionByID
//
//	SELECT
//	    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
//	    u_started.name AS session_started_user_name,
//	    u_started.key_id_name AS session_started_user_key_id_name,
//	    u_started.last_name AS session_started_user_last_name,
//	    u_started.key_id_last_name AS session_started_user_key_id_last_name,
//	    u_ended.name AS session_ended_user_name,
//	    u_ended.key_id_name AS session_ended_user_key_id_name,
//	    u_ended.last_name AS session_ended_user_last_name,
//	    u_ended.key_id_last_name AS session_ended_user_key_id_last_name
//	FROM
//	    dg_pos_cash_drawer_sessions cds
//	    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
//	    JOIN users u_started ON u_started.id = cds.session_started_user_id
//	    JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
//	WHERE
//	    cds.id = ?
func (q *Queries) GetCashDrawerSessionByID(ctx context.Context, id uint64) (*GetCashDrawerSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCashDrawerSessionByID, id)
	var i GetCashDrawerSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CashDrawerID,
		&i.SessionStartedUserID,
		&i.SessionEndedUserID,
		&i.OpenedAt,
		&i.OpeningBalance,
		&i.ClosedAt,
		&i.ClosingBalanceCounted,
		&i.ClosingBalanceExpected,
		&i.Difference,
		&i.TotalInAmount,
		&i.TotalOutAmount,
		&i.TotalSalesAmount,
		&i.TotalOtherSalesAmount,
		&i.TotalRefundAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionStartedUserName,
		&i.SessionStartedUserKeyIDName,
		&i.SessionStartedUserLastName,
		&i.SessionStartedUserKeyIDLastName,
		&i.SessionEndedUserName,
		&i.SessionEndedUserKeyIDName,
		&i.SessionEndedUserLastName,
		&i.SessionEndedUserKeyIDLastName,
	)
	return &i, err
}

const getCashDrawerSessionSummary = `-- name: GetCashDrawerSessionSummary :one
SELECT
    cds.id AS cash_drawer_session_id,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'PAY_IN' THEN cdm.amount
            ELSE 0
        END
    ) AS total_in_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'PAY_OUT' THEN cdm.amount
            ELSE 0
        END
    ) AS total_out_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'SALE' THEN cdm.amount
            ELSE 0
        END
    ) + SUM(
        CASE
            WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_sales_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'OTHER_SALES' THEN cdm.amount
            ELSE 0
        END
    ) + SUM(
        CASE
            WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_other_sales_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_cash_sale_cash_refund_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'CARD_SALE_CASH_REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_card_sale_cash_refund_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_pos_card_sale_cash_refund_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_other_refund_amount,
    0 + SUM(
        CASE
            WHEN cdm.movement_type = 'REFUND'
            OR cdm.movement_type = 'CARD_SALE_CASH_REFUND'
            OR cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND'
            OR cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
            ELSE 0
        END
    ) AS total_refund_amount,
    0 + COALESCE(SUM(cdm.amount), 0) AS total_movements,
    cds.opening_balance + COALESCE(SUM(cdm.amount), 0) AS expected_balance,
    cds.closing_balance_counted - (
        cds.opening_balance + COALESCE(SUM(cdm.amount), 0)
    ) AS difference
FROM
    dg_pos_cash_drawer_sessions cds
    LEFT JOIN dg_pos_cash_movements cdm ON cds.id = cdm.cash_drawer_session_id
WHERE
    cds.id = ?
GROUP BY
    cds.id
`

type GetCashDrawerSessionSummaryRow struct {
	CashDrawerSessionID              uint64 `json:"cash_drawer_session_id"`
	TotalInAmount                    int32  `json:"total_in_amount"`
	TotalOutAmount                   int32  `json:"total_out_amount"`
	TotalSalesAmount                 int32  `json:"total_sales_amount"`
	TotalOtherSalesAmount            int32  `json:"total_other_sales_amount"`
	TotalCashSaleCashRefundAmount    int32  `json:"total_cash_sale_cash_refund_amount"`
	TotalCardSaleCashRefundAmount    int32  `json:"total_card_sale_cash_refund_amount"`
	TotalPosCardSaleCashRefundAmount int32  `json:"total_pos_card_sale_cash_refund_amount"`
	TotalOtherRefundAmount           int32  `json:"total_other_refund_amount"`
	TotalRefundAmount                int32  `json:"total_refund_amount"`
	TotalMovements                   int32  `json:"total_movements"`
	ExpectedBalance                  int32  `json:"expected_balance"`
	Difference                       int32  `json:"difference"`
}

// GetCashDrawerSessionSummary
//
//	SELECT
//	    cds.id AS cash_drawer_session_id,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'PAY_IN' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_in_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'PAY_OUT' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_out_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'SALE' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_sales_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'OTHER_SALES' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_other_sales_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_cash_sale_cash_refund_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'CARD_SALE_CASH_REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_card_sale_cash_refund_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_pos_card_sale_cash_refund_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_other_refund_amount,
//	    0 + SUM(
//	        CASE
//	            WHEN cdm.movement_type = 'REFUND'
//	            OR cdm.movement_type = 'CARD_SALE_CASH_REFUND'
//	            OR cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND'
//	            OR cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
//	            ELSE 0
//	        END
//	    ) AS total_refund_amount,
//	    0 + COALESCE(SUM(cdm.amount), 0) AS total_movements,
//	    cds.opening_balance + COALESCE(SUM(cdm.amount), 0) AS expected_balance,
//	    cds.closing_balance_counted - (
//	        cds.opening_balance + COALESCE(SUM(cdm.amount), 0)
//	    ) AS difference
//	FROM
//	    dg_pos_cash_drawer_sessions cds
//	    LEFT JOIN dg_pos_cash_movements cdm ON cds.id = cdm.cash_drawer_session_id
//	WHERE
//	    cds.id = ?
//	GROUP BY
//	    cds.id
func (q *Queries) GetCashDrawerSessionSummary(ctx context.Context, id uint64) (*GetCashDrawerSessionSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCashDrawerSessionSummary, id)
	var i GetCashDrawerSessionSummaryRow
	err := row.Scan(
		&i.CashDrawerSessionID,
		&i.TotalInAmount,
		&i.TotalOutAmount,
		&i.TotalSalesAmount,
		&i.TotalOtherSalesAmount,
		&i.TotalCashSaleCashRefundAmount,
		&i.TotalCardSaleCashRefundAmount,
		&i.TotalPosCardSaleCashRefundAmount,
		&i.TotalOtherRefundAmount,
		&i.TotalRefundAmount,
		&i.TotalMovements,
		&i.ExpectedBalance,
		&i.Difference,
	)
	return &i, err
}

const getCashDrawerSessions = `-- name: GetCashDrawerSessions :many
SELECT
    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
    u_started.name AS session_started_user_name,
    u_started.key_id_name AS session_started_user_key_id_name,
    u_started.last_name AS session_started_user_last_name,
    u_started.key_id_last_name AS session_started_user_key_id_last_name,
    u_ended.name AS session_ended_user_name,
    u_ended.key_id_name AS session_ended_user_key_id_name,
    u_ended.last_name AS session_ended_user_last_name,
    u_ended.key_id_last_name AS session_ended_user_key_id_last_name
FROM
    dg_pos_cash_drawer_sessions cds
    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
    JOIN users u_started ON u_started.id = cds.session_started_user_id
    JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
WHERE
    cd.outlet_id = ?
    AND cds.status = 'CLOSED'
    AND cds.created_at >= ?
    AND cds.created_at <= ?
`

type GetCashDrawerSessionsParams struct {
	OutletID uint64       `json:"outlet_id"`
	FromDate sql.NullTime `json:"from_date"`
	ToDate   sql.NullTime `json:"to_date"`
}

type GetCashDrawerSessionsRow struct {
	ID                              uint64         `json:"id"`
	CashDrawerID                    uint64         `json:"cash_drawer_id"`
	SessionStartedUserID            uint64         `json:"session_started_user_id"`
	SessionEndedUserID              sql.NullInt64  `json:"session_ended_user_id"`
	OpenedAt                        time.Time      `json:"opened_at"`
	OpeningBalance                  int32          `json:"opening_balance"`
	ClosedAt                        sql.NullTime   `json:"closed_at"`
	ClosingBalanceCounted           sql.NullInt32  `json:"closing_balance_counted"`
	ClosingBalanceExpected          sql.NullInt32  `json:"closing_balance_expected"`
	Difference                      sql.NullInt32  `json:"difference"`
	TotalInAmount                   sql.NullInt32  `json:"total_in_amount"`
	TotalOutAmount                  sql.NullInt32  `json:"total_out_amount"`
	TotalSalesAmount                sql.NullInt32  `json:"total_sales_amount"`
	TotalOtherSalesAmount           sql.NullInt32  `json:"total_other_sales_amount"`
	TotalRefundAmount               sql.NullInt32  `json:"total_refund_amount"`
	Status                          string         `json:"status"`
	CreatedAt                       sql.NullTime   `json:"created_at"`
	UpdatedAt                       sql.NullTime   `json:"updated_at"`
	SessionStartedUserName          string         `json:"session_started_user_name"`
	SessionStartedUserKeyIDName     int32          `json:"session_started_user_key_id_name"`
	SessionStartedUserLastName      sql.NullString `json:"session_started_user_last_name"`
	SessionStartedUserKeyIDLastName int32          `json:"session_started_user_key_id_last_name"`
	SessionEndedUserName            string         `json:"session_ended_user_name"`
	SessionEndedUserKeyIDName       int32          `json:"session_ended_user_key_id_name"`
	SessionEndedUserLastName        sql.NullString `json:"session_ended_user_last_name"`
	SessionEndedUserKeyIDLastName   int32          `json:"session_ended_user_key_id_last_name"`
}

// GetCashDrawerSessions
//
//	SELECT
//	    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
//	    u_started.name AS session_started_user_name,
//	    u_started.key_id_name AS session_started_user_key_id_name,
//	    u_started.last_name AS session_started_user_last_name,
//	    u_started.key_id_last_name AS session_started_user_key_id_last_name,
//	    u_ended.name AS session_ended_user_name,
//	    u_ended.key_id_name AS session_ended_user_key_id_name,
//	    u_ended.last_name AS session_ended_user_last_name,
//	    u_ended.key_id_last_name AS session_ended_user_key_id_last_name
//	FROM
//	    dg_pos_cash_drawer_sessions cds
//	    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
//	    JOIN users u_started ON u_started.id = cds.session_started_user_id
//	    JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
//	WHERE
//	    cd.outlet_id = ?
//	    AND cds.status = 'CLOSED'
//	    AND cds.created_at >= ?
//	    AND cds.created_at <= ?
func (q *Queries) GetCashDrawerSessions(ctx context.Context, arg *GetCashDrawerSessionsParams) ([]*GetCashDrawerSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCashDrawerSessions, arg.OutletID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCashDrawerSessionsRow{}
	for rows.Next() {
		var i GetCashDrawerSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CashDrawerID,
			&i.SessionStartedUserID,
			&i.SessionEndedUserID,
			&i.OpenedAt,
			&i.OpeningBalance,
			&i.ClosedAt,
			&i.ClosingBalanceCounted,
			&i.ClosingBalanceExpected,
			&i.Difference,
			&i.TotalInAmount,
			&i.TotalOutAmount,
			&i.TotalSalesAmount,
			&i.TotalOtherSalesAmount,
			&i.TotalRefundAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionStartedUserName,
			&i.SessionStartedUserKeyIDName,
			&i.SessionStartedUserLastName,
			&i.SessionStartedUserKeyIDLastName,
			&i.SessionEndedUserName,
			&i.SessionEndedUserKeyIDName,
			&i.SessionEndedUserLastName,
			&i.SessionEndedUserKeyIDLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashDrawerTransactionHistory = `-- name: GetCashDrawerTransactionHistory :many
SELECT
    cd.id AS cash_drawer_id,
    cds.id AS cash_drawer_session_id,
    cm.id AS cash_movement_id,
    cm.created_at,
    cm.movement_type,
    cm.note,
    cm.amount,
    users.name AS user_name,
    users.key_id_name AS user_key_id_name,
    users.last_name AS user_last_name,
    users.key_id_last_name AS user_key_id_last_name
FROM
    dg_pos_cash_movements cm
    LEFT JOIN users ON users.id = cm.user_id
    JOIN dg_pos_cash_drawer_sessions cds ON cds.id = cm.cash_drawer_session_id
    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
WHERE
    cd.outlet_id = ?
    AND cm.movement_type IN ('PAY_IN', 'PAY_OUT')
    AND cm.created_at >= ?
    AND cm.created_at <= ?
ORDER BY cm.id DESC
`

type GetCashDrawerTransactionHistoryParams struct {
	OutletID uint64       `json:"outlet_id"`
	FromDate sql.NullTime `json:"from_date"`
	ToDate   sql.NullTime `json:"to_date"`
}

type GetCashDrawerTransactionHistoryRow struct {
	CashDrawerID        uint64         `json:"cash_drawer_id"`
	CashDrawerSessionID uint64         `json:"cash_drawer_session_id"`
	CashMovementID      uint64         `json:"cash_movement_id"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	MovementType        string         `json:"movement_type"`
	Note                sql.NullString `json:"note"`
	Amount              int32          `json:"amount"`
	UserName            sql.NullString `json:"user_name"`
	UserKeyIDName       sql.NullInt32  `json:"user_key_id_name"`
	UserLastName        sql.NullString `json:"user_last_name"`
	UserKeyIDLastName   sql.NullInt32  `json:"user_key_id_last_name"`
}

// GetCashDrawerTransactionHistory
//
//	SELECT
//	    cd.id AS cash_drawer_id,
//	    cds.id AS cash_drawer_session_id,
//	    cm.id AS cash_movement_id,
//	    cm.created_at,
//	    cm.movement_type,
//	    cm.note,
//	    cm.amount,
//	    users.name AS user_name,
//	    users.key_id_name AS user_key_id_name,
//	    users.last_name AS user_last_name,
//	    users.key_id_last_name AS user_key_id_last_name
//	FROM
//	    dg_pos_cash_movements cm
//	    LEFT JOIN users ON users.id = cm.user_id
//	    JOIN dg_pos_cash_drawer_sessions cds ON cds.id = cm.cash_drawer_session_id
//	    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
//	WHERE
//	    cd.outlet_id = ?
//	    AND cm.movement_type IN ('PAY_IN', 'PAY_OUT')
//	    AND cm.created_at >= ?
//	    AND cm.created_at <= ?
//	ORDER BY cm.id DESC
func (q *Queries) GetCashDrawerTransactionHistory(ctx context.Context, arg *GetCashDrawerTransactionHistoryParams) ([]*GetCashDrawerTransactionHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCashDrawerTransactionHistory, arg.OutletID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCashDrawerTransactionHistoryRow{}
	for rows.Next() {
		var i GetCashDrawerTransactionHistoryRow
		if err := rows.Scan(
			&i.CashDrawerID,
			&i.CashDrawerSessionID,
			&i.CashMovementID,
			&i.CreatedAt,
			&i.MovementType,
			&i.Note,
			&i.Amount,
			&i.UserName,
			&i.UserKeyIDName,
			&i.UserLastName,
			&i.UserKeyIDLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashMovement = `-- name: GetCashMovement :one
SELECT cm.id, cm.cash_drawer_session_id, cm.movement_type, cm.amount, cm.note, cm.user_id, cm.created_at, cm.updated_at
FROM dg_pos_cash_movements cm
WHERE
    cash_drawer_session_id = ?
    AND movement_type = ?
`

type GetCashMovementParams struct {
	CashDrawerSessionID uint64 `json:"cash_drawer_session_id"`
	MovementType        string `json:"movement_type"`
}

// GetCashMovement
//
//	SELECT cm.id, cm.cash_drawer_session_id, cm.movement_type, cm.amount, cm.note, cm.user_id, cm.created_at, cm.updated_at
//	FROM dg_pos_cash_movements cm
//	WHERE
//	    cash_drawer_session_id = ?
//	    AND movement_type = ?
func (q *Queries) GetCashMovement(ctx context.Context, arg *GetCashMovementParams) (*DgPosCashMovement, error) {
	row := q.db.QueryRowContext(ctx, getCashMovement, arg.CashDrawerSessionID, arg.MovementType)
	var i DgPosCashMovement
	err := row.Scan(
		&i.ID,
		&i.CashDrawerSessionID,
		&i.MovementType,
		&i.Amount,
		&i.Note,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCashPaidPosOrderIdsWithinTimeRange = `-- name: GetCashPaidPosOrderIdsWithinTimeRange :many
SELECT
    DISTINCT odr.id
FROM
    ` + "`" + `order` + "`" + ` odr
    JOIN order_transaction ot ON odr.id = ot.type_id AND ot.` + "`" + `type` + "`" + ` = 'ORDER'
WHERE
    -- ot.transaction_type = 'SALE'
    ot.transaction_mode = 'CASH'
    AND odr.status IN ('COMPLETED', 'CANCELED')
    AND odr.device_platform = 'dg_pos'
    AND odr.testing_order = 0
    AND odr.created_at >= ?
    AND odr.created_at <= ?
    AND odr.shop_id = ?
`

type GetCashPaidPosOrderIdsWithinTimeRangeParams struct {
	FromCreatedAt sql.NullTime `json:"from_created_at"`
	ToCreatedAt   sql.NullTime `json:"to_created_at"`
	ShopID        int32        `json:"shop_id"`
}

// GetCashPaidPosOrderIdsWithinTimeRange
//
//	SELECT
//	    DISTINCT odr.id
//	FROM
//	    `order` odr
//	    JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
//	WHERE
//	    -- ot.transaction_type = 'SALE'
//	    ot.transaction_mode = 'CASH'
//	    AND odr.status IN ('COMPLETED', 'CANCELED')
//	    AND odr.device_platform = 'dg_pos'
//	    AND odr.testing_order = 0
//	    AND odr.created_at >= ?
//	    AND odr.created_at <= ?
//	    AND odr.shop_id = ?
func (q *Queries) GetCashPaidPosOrderIdsWithinTimeRange(ctx context.Context, arg *GetCashPaidPosOrderIdsWithinTimeRangeParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, getCashPaidPosOrderIdsWithinTimeRange, arg.FromCreatedAt, arg.ToCreatedAt, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncompleteOrders = `-- name: GetIncompleteOrders :many




SELECT id, shop_id, platform_id, remote_order_id, display_order_id, delivery_date_time, total_amount, sub_total, total_fee, campaign_code, discount, voucher_discount, discount_mode_applied, discount_percentage_applied, discount_type, vouchers, status, cancelled_reason, order_type_id, note, created_at, updated_at, customer_name, user_id, customer_id, delivery_location_id, delivery_tax, tax_id, shipping_method, shipping_total, shipping_tax, total_tax, cash_due, surcharge, contact_access_code, testing_order, cancelled_by_customer, payment_method, payment_mode, is_scheduled, is_table_order, tip, tip_percentage, table_id, dgpos_table_id, table_order_method_id, device_platform, order_delayed, unique_order_id, order_session_id
FROM ` + "`" + `order` + "`" + ` odr
WHERE
    odr.status NOT IN(
        'COMPLETED',
        'CANCELED',
        'MISSED',
        'DENIED',
        'CREATED',
        'TEMP'
    )
    AND odr.created_at BETWEEN ? AND ?
    AND odr.shop_id = ?
`

type GetIncompleteOrdersParams struct {
	FromCreatedAt sql.NullTime `json:"from_created_at"`
	ToCreatedAt   sql.NullTime `json:"to_created_at"`
	ShopID        int32        `json:"shop_id"`
}

// -- name: GetSalesCashAmountPOS :one
// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS sales_total
// FROM
//
//	`order` odr
//	JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
//
// WHERE
//
//	ot.transaction_type = 'SALE'
//	AND ot.transaction_mode = 'CASH'
//	AND odr.status IN ('COMPLETED', 'CANCELED')
//	AND odr.device_platform = 'dg_pos'
//	AND odr.testing_order = 0
//	AND odr.created_at >= sqlc.arg (from_created_at)
//	AND odr.created_at <= sqlc.arg (to_created_at)
//	AND odr.shop_id = ?;
//
// -- name: GetRefundCashAmountPOS :one
// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
// FROM
//
//	`order` odr
//	JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
//
// WHERE
//
//	ot.transaction_type = 'REFUND'
//	AND ot.transaction_mode = 'CASH'
//	AND odr.status IN ('COMPLETED', 'CANCELED')
//	AND odr.device_platform = 'dg_pos'
//	AND odr.testing_order = 0
//	AND odr.created_at >= sqlc.arg (from_created_at)
//	AND odr.created_at <= sqlc.arg (to_created_at)
//	AND odr.shop_id = ?;
//
// -- name: GetCashSaleCashRefundAmountPOS :one
// WITH cash_paid_orders_within_time_range AS (
//
//	SELECT odr.id
//	FROM
//	    `order` odr
//	    JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
//	WHERE
//	    ot.transaction_type = 'SALE'
//	    AND ot.transaction_mode = 'CASH'
//	    AND odr.status IN ('COMPLETED', 'CANCELED')
//	    AND odr.device_platform = 'dg_pos'
//	    AND odr.testing_order = 0
//	    AND odr.created_at >= sqlc.arg (from_created_at)
//	    AND odr.created_at <= sqlc.arg (to_created_at)
//	    AND odr.shop_id = ?
//
// )
// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
// FROM order_transaction ot
//
//	JOIN cash_paid_orders_within_time_range cpo ON cpo.id = ot.type_id
//
// WHERE
//
//	ot.transaction_type = 'REFUND'
//	AND ot.transaction_mode = 'CASH';
//
// -- name: GetRefundCardAmount :one
// WITH card_paid_orders_within_time_range AS (
//
//	SELECT odr.id
//	FROM
//	    `order` odr
//	    JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
//	WHERE
//	    ot.transaction_type = 'SALE'
//	    AND ot.transaction_mode = 'CARD'
//	    AND odr.status IN ('COMPLETED', 'CANCELED')
//	    AND odr.testing_order = 0
//	    AND odr.created_at >= sqlc.arg (from_created_at)
//	    AND odr.created_at <= sqlc.arg (to_created_at)
//	    AND odr.shop_id = ?
//
// )
// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
// FROM order_transaction ot
//
//	JOIN card_paid_orders_within_time_range cpo ON cpo.id = ot.type_id
//
// WHERE
//
//	   ot.transaction_type = 'REFUND'
//	   AND ot.transaction_mode = 'CASH';
//
//
//
//
//
//	SELECT id, shop_id, platform_id, remote_order_id, display_order_id, delivery_date_time, total_amount, sub_total, total_fee, campaign_code, discount, voucher_discount, discount_mode_applied, discount_percentage_applied, discount_type, vouchers, status, cancelled_reason, order_type_id, note, created_at, updated_at, customer_name, user_id, customer_id, delivery_location_id, delivery_tax, tax_id, shipping_method, shipping_total, shipping_tax, total_tax, cash_due, surcharge, contact_access_code, testing_order, cancelled_by_customer, payment_method, payment_mode, is_scheduled, is_table_order, tip, tip_percentage, table_id, dgpos_table_id, table_order_method_id, device_platform, order_delayed, unique_order_id, order_session_id
//	FROM `order` odr
//	WHERE
//	    odr.status NOT IN(
//	        'COMPLETED',
//	        'CANCELED',
//	        'MISSED',
//	        'DENIED',
//	        'CREATED',
//	        'TEMP'
//	    )
//	    AND odr.created_at BETWEEN ? AND ?
//	    AND odr.shop_id = ?
func (q *Queries) GetIncompleteOrders(ctx context.Context, arg *GetIncompleteOrdersParams) ([]*Order, error) {
	rows, err := q.db.QueryContext(ctx, getIncompleteOrders, arg.FromCreatedAt, arg.ToCreatedAt, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.PlatformID,
			&i.RemoteOrderID,
			&i.DisplayOrderID,
			&i.DeliveryDateTime,
			&i.TotalAmount,
			&i.SubTotal,
			&i.TotalFee,
			&i.CampaignCode,
			&i.Discount,
			&i.VoucherDiscount,
			&i.DiscountModeApplied,
			&i.DiscountPercentageApplied,
			&i.DiscountType,
			&i.Vouchers,
			&i.Status,
			&i.CancelledReason,
			&i.OrderTypeID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.UserID,
			&i.CustomerID,
			&i.DeliveryLocationID,
			&i.DeliveryTax,
			&i.TaxID,
			&i.ShippingMethod,
			&i.ShippingTotal,
			&i.ShippingTax,
			&i.TotalTax,
			&i.CashDue,
			&i.Surcharge,
			&i.ContactAccessCode,
			&i.TestingOrder,
			&i.CancelledByCustomer,
			&i.PaymentMethod,
			&i.PaymentMode,
			&i.IsScheduled,
			&i.IsTableOrder,
			&i.Tip,
			&i.TipPercentage,
			&i.TableID,
			&i.DgposTableID,
			&i.TableOrderMethodID,
			&i.DevicePlatform,
			&i.OrderDelayed,
			&i.UniqueOrderID,
			&i.OrderSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenCashDrawerSession = `-- name: GetOpenCashDrawerSession :one
SELECT
    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
    u_started.name AS session_started_user_name,
    u_started.key_id_name AS session_started_user_key_id_name,
    u_started.last_name AS session_started_user_last_name,
    u_started.key_id_last_name AS session_started_user_key_id_last_name
FROM
    dg_pos_cash_drawer_sessions cds
    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
    JOIN users u_started ON u_started.id = cds.session_started_user_id
WHERE
    cd.outlet_id = ?
    AND cds.status = 'OPEN'
LIMIT 1
`

type GetOpenCashDrawerSessionRow struct {
	ID                              uint64         `json:"id"`
	CashDrawerID                    uint64         `json:"cash_drawer_id"`
	SessionStartedUserID            uint64         `json:"session_started_user_id"`
	SessionEndedUserID              sql.NullInt64  `json:"session_ended_user_id"`
	OpenedAt                        time.Time      `json:"opened_at"`
	OpeningBalance                  int32          `json:"opening_balance"`
	ClosedAt                        sql.NullTime   `json:"closed_at"`
	ClosingBalanceCounted           sql.NullInt32  `json:"closing_balance_counted"`
	ClosingBalanceExpected          sql.NullInt32  `json:"closing_balance_expected"`
	Difference                      sql.NullInt32  `json:"difference"`
	TotalInAmount                   sql.NullInt32  `json:"total_in_amount"`
	TotalOutAmount                  sql.NullInt32  `json:"total_out_amount"`
	TotalSalesAmount                sql.NullInt32  `json:"total_sales_amount"`
	TotalOtherSalesAmount           sql.NullInt32  `json:"total_other_sales_amount"`
	TotalRefundAmount               sql.NullInt32  `json:"total_refund_amount"`
	Status                          string         `json:"status"`
	CreatedAt                       sql.NullTime   `json:"created_at"`
	UpdatedAt                       sql.NullTime   `json:"updated_at"`
	SessionStartedUserName          string         `json:"session_started_user_name"`
	SessionStartedUserKeyIDName     int32          `json:"session_started_user_key_id_name"`
	SessionStartedUserLastName      sql.NullString `json:"session_started_user_last_name"`
	SessionStartedUserKeyIDLastName int32          `json:"session_started_user_key_id_last_name"`
}

// GetOpenCashDrawerSession
//
//	SELECT
//	    cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
//	    u_started.name AS session_started_user_name,
//	    u_started.key_id_name AS session_started_user_key_id_name,
//	    u_started.last_name AS session_started_user_last_name,
//	    u_started.key_id_last_name AS session_started_user_key_id_last_name
//	FROM
//	    dg_pos_cash_drawer_sessions cds
//	    JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
//	    JOIN users u_started ON u_started.id = cds.session_started_user_id
//	WHERE
//	    cd.outlet_id = ?
//	    AND cds.status = 'OPEN'
//	LIMIT 1
func (q *Queries) GetOpenCashDrawerSession(ctx context.Context, outletID uint64) (*GetOpenCashDrawerSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getOpenCashDrawerSession, outletID)
	var i GetOpenCashDrawerSessionRow
	err := row.Scan(
		&i.ID,
		&i.CashDrawerID,
		&i.SessionStartedUserID,
		&i.SessionEndedUserID,
		&i.OpenedAt,
		&i.OpeningBalance,
		&i.ClosedAt,
		&i.ClosingBalanceCounted,
		&i.ClosingBalanceExpected,
		&i.Difference,
		&i.TotalInAmount,
		&i.TotalOutAmount,
		&i.TotalSalesAmount,
		&i.TotalOtherSalesAmount,
		&i.TotalRefundAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionStartedUserName,
		&i.SessionStartedUserKeyIDName,
		&i.SessionStartedUserLastName,
		&i.SessionStartedUserKeyIDLastName,
	)
	return &i, err
}

const updateClosingBalanceCounted = `-- name: UpdateClosingBalanceCounted :exec
UPDATE dg_pos_cash_drawer_sessions
SET
    closing_balance_counted = ?
WHERE
    id = ?
`

type UpdateClosingBalanceCountedParams struct {
	ClosingBalanceCounted sql.NullInt32 `json:"closing_balance_counted"`
	ID                    uint64        `json:"id"`
}

// UpdateClosingBalanceCounted
//
//	UPDATE dg_pos_cash_drawer_sessions
//	SET
//	    closing_balance_counted = ?
//	WHERE
//	    id = ?
func (q *Queries) UpdateClosingBalanceCounted(ctx context.Context, arg *UpdateClosingBalanceCountedParams) error {
	_, err := q.db.ExecContext(ctx, updateClosingBalanceCounted, arg.ClosingBalanceCounted, arg.ID)
	return err
}

const upsertCashMovement = `-- name: UpsertCashMovement :exec
INSERT INTO
    dg_pos_cash_movements (
        id,
        cash_drawer_session_id,
        movement_type,
        note,
        amount,
        user_id,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON DUPLICATE KEY UPDATE
    amount = amount +
VALUES (amount),
    note = VALUES(note),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCashMovementParams struct {
	ID                  uint64         `json:"id"`
	CashDrawerSessionID uint64         `json:"cash_drawer_session_id"`
	MovementType        string         `json:"movement_type"`
	Note                sql.NullString `json:"note"`
	Amount              int32          `json:"amount"`
	UserID              uint64         `json:"user_id"`
}

// UpsertCashMovement
//
//	INSERT INTO
//	    dg_pos_cash_movements (
//	        id,
//	        cash_drawer_session_id,
//	        movement_type,
//	        note,
//	        amount,
//	        user_id,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
//	ON DUPLICATE KEY UPDATE
//	    amount = amount +
//	VALUES (amount),
//	    note = VALUES(note),
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertCashMovement(ctx context.Context, arg *UpsertCashMovementParams) error {
	_, err := q.db.ExecContext(ctx, upsertCashMovement,
		arg.ID,
		arg.CashDrawerSessionID,
		arg.MovementType,
		arg.Note,
		arg.Amount,
		arg.UserID,
	)
	return err
}
