// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commisions_query.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderCommission = `-- name: CreateOrderCommission :exec
INSERT INTO
    order_commission (
        order_tmp_id,
        order_id,
        commission,
        reference,
        report_id,
        status,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderCommissionParams struct {
	OrderTmpID sql.NullInt64  `json:"order_tmp_id"`
	OrderID    int64          `json:"order_id"`
	Commission string         `json:"commission"`
	Reference  sql.NullString `json:"reference"`
	ReportID   sql.NullInt32  `json:"report_id"`
	Status     string         `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

// CreateOrderCommission
//
//	INSERT INTO
//	    order_commission (
//	        order_tmp_id,
//	        order_id,
//	        commission,
//	        reference,
//	        report_id,
//	        status,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateOrderCommission(ctx context.Context, arg *CreateOrderCommissionParams) error {
	_, err := q.db.ExecContext(ctx, createOrderCommission,
		arg.OrderTmpID,
		arg.OrderID,
		arg.Commission,
		arg.Reference,
		arg.ReportID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOrderCommission = `-- name: DeleteOrderCommission :exec
DELETE FROM order_commission WHERE order_id = ?
`

// DeleteOrderCommission
//
//	DELETE FROM order_commission WHERE order_id = ?
func (q *Queries) DeleteOrderCommission(ctx context.Context, orderID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderCommission, orderID)
	return err
}

const getCommissionAmount = `-- name: GetCommissionAmount :one
SELECT order_commission
FROM shop_brand_details
WHERE
    shop_id = ?
    AND webshop_brand_id = ?
`

type GetCommissionAmountParams struct {
	ShopID         uint32 `json:"shop_id"`
	WebshopBrandID uint32 `json:"webshop_brand_id"`
}

// GetCommissionAmount
//
//	SELECT order_commission
//	FROM shop_brand_details
//	WHERE
//	    shop_id = ?
//	    AND webshop_brand_id = ?
func (q *Queries) GetCommissionAmount(ctx context.Context, arg *GetCommissionAmountParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCommissionAmount, arg.ShopID, arg.WebshopBrandID)
	var order_commission string
	err := row.Scan(&order_commission)
	return order_commission, err
}

const getOrderCommission = `-- name: GetOrderCommission :one
SELECT id, order_tmp_id, order_id, commission, reference, report_id, status, created_at, updated_at FROM order_commission WHERE order_id = ?
`

// GetOrderCommission
//
//	SELECT id, order_tmp_id, order_id, commission, reference, report_id, status, created_at, updated_at FROM order_commission WHERE order_id = ?
func (q *Queries) GetOrderCommission(ctx context.Context, orderID int64) (*OrderCommission, error) {
	row := q.db.QueryRowContext(ctx, getOrderCommission, orderID)
	var i OrderCommission
	err := row.Scan(
		&i.ID,
		&i.OrderTmpID,
		&i.OrderID,
		&i.Commission,
		&i.Reference,
		&i.ReportID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateOrderCommission = `-- name: UpdateOrderCommission :exec
UPDATE order_commission
SET
    commission = ?,
    updated_at = ?
WHERE
    order_id = ?
`

type UpdateOrderCommissionParams struct {
	Commission string       `json:"commission"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	OrderID    int64        `json:"order_id"`
}

// UpdateOrderCommission
//
//	UPDATE order_commission
//	SET
//	    commission = ?,
//	    updated_at = ?
//	WHERE
//	    order_id = ?
func (q *Queries) UpdateOrderCommission(ctx context.Context, arg *UpdateOrderCommissionParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderCommission, arg.Commission, arg.UpdatedAt, arg.OrderID)
	return err
}
