// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customer_query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createCustomer = `-- name: CreateCustomer :execlastid
INSERT INTO
    customers (
        first_name,
        hashed_first_name,
        key_id_first_name,
        last_name,
        hashed_last_name,
        key_id_last_name, 
        phone,
        hashed_phone,
        key_id_phone,
        country_code,
        ` + "`" + `type` + "`" + `,
        device_platform,
        status,
        account_brand,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateCustomerParams struct {
	FirstName       sql.NullString `json:"first_name"`
	HashedFirstName sql.NullString `json:"hashed_first_name"`
	KeyIDFirstName  int32          `json:"key_id_first_name"`
	LastName        sql.NullString `json:"last_name"`
	HashedLastName  sql.NullString `json:"hashed_last_name"`
	KeyIDLastName   int32          `json:"key_id_last_name"`
	Phone           sql.NullString `json:"phone"`
	HashedPhone     sql.NullString `json:"hashed_phone"`
	KeyIDPhone      int32          `json:"key_id_phone"`
	CountryCode     sql.NullString `json:"country_code"`
	Type            sql.NullString `json:"type"`
	DevicePlatform  sql.NullString `json:"device_platform"`
	Status          bool           `json:"status"`
	AccountBrand    sql.NullInt32  `json:"account_brand"`
}

// CreateCustomer
//
//	INSERT INTO
//	    customers (
//	        first_name,
//	        hashed_first_name,
//	        key_id_first_name,
//	        last_name,
//	        hashed_last_name,
//	        key_id_last_name,
//	        phone,
//	        hashed_phone,
//	        key_id_phone,
//	        country_code,
//	        `type`,
//	        device_platform,
//	        status,
//	        account_brand,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateCustomer(ctx context.Context, arg *CreateCustomerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCustomer,
		arg.FirstName,
		arg.HashedFirstName,
		arg.KeyIDFirstName,
		arg.LastName,
		arg.HashedLastName,
		arg.KeyIDLastName,
		arg.Phone,
		arg.HashedPhone,
		arg.KeyIDPhone,
		arg.CountryCode,
		arg.Type,
		arg.DevicePlatform,
		arg.Status,
		arg.AccountBrand,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real FROM customers WHERE id = ?
`

// GetCustomerByID
//
//	SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real FROM customers WHERE id = ?
func (q *Queries) GetCustomerByID(ctx context.Context, id uint64) (*Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.OrderID,
		&i.FirstOrderOfferEligible,
		&i.SubscribeToPromotionEmails,
		&i.PromotionEmailsSubscribedAt,
		&i.FirstName,
		&i.HashedFirstName,
		&i.KeyIDFirstName,
		&i.LastName,
		&i.HashedLastName,
		&i.KeyIDLastName,
		&i.AccountBrand,
		&i.Dob,
		&i.HashedDob,
		&i.KeyIDDob,
		&i.Address1,
		&i.HashedAddress1,
		&i.KeyIDAddress1,
		&i.Address2,
		&i.HashedAddress2,
		&i.KeyIDAddress2,
		&i.Email,
		&i.HashedEmail,
		&i.KeyIDEmail,
		&i.Password,
		&i.AppleID,
		&i.Phone,
		&i.HashedPhone,
		&i.KeyIDPhone,
		&i.CountryCode,
		&i.City,
		&i.HashedCity,
		&i.KeyIDCity,
		&i.State,
		&i.HashedState,
		&i.KeyIDState,
		&i.Postcode,
		&i.HashedPostcode,
		&i.KeyIDPostcode,
		&i.Country,
		&i.HashedCountry,
		&i.KeyIDCountry,
		&i.RemoteID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.HashedLatitude,
		&i.KeyIDLatitude,
		&i.Longitude,
		&i.HashedLongitude,
		&i.KeyIDLongitude,
		&i.ResetToken,
		&i.RememberToken,
		&i.StripeID,
		&i.ContactAccessCode,
		&i.Otp,
		&i.Status,
		&i.PasswordResetCode,
		&i.PasswordResetCodeStatus,
		&i.AddressType,
		&i.Notes,
		&i.ExpoToken,
		&i.NotificationPermissionGivenAt,
		&i.DeviceID,
		&i.DevicePlatform,
		&i.LastActiveTime,
		&i.LastActiveDevice,
		&i.DeletedAt,
		&i.IsReal,
	)
	return &i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real
FROM customers
WHERE
    hashed_phone IN (
        /*SLICE:phone_number_formats*/?
    )
    AND country_code = ?
`

type GetCustomerByPhoneParams struct {
	PhoneNumberFormats []sql.NullString `json:"phone_number_formats"`
	CountryCode        sql.NullString   `json:"country_code"`
}

// GetCustomerByPhone
//
//	SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real
//	FROM customers
//	WHERE
//	    hashed_phone IN (
//	        /*SLICE:phone_number_formats*/?
//	    )
//	    AND country_code = ?
func (q *Queries) GetCustomerByPhone(ctx context.Context, arg *GetCustomerByPhoneParams) (*Customer, error) {
	query := getCustomerByPhone
	var queryParams []interface{}
	if len(arg.PhoneNumberFormats) > 0 {
		for _, v := range arg.PhoneNumberFormats {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:phone_number_formats*/?", strings.Repeat(",?", len(arg.PhoneNumberFormats))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:phone_number_formats*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CountryCode)
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.OrderID,
		&i.FirstOrderOfferEligible,
		&i.SubscribeToPromotionEmails,
		&i.PromotionEmailsSubscribedAt,
		&i.FirstName,
		&i.HashedFirstName,
		&i.KeyIDFirstName,
		&i.LastName,
		&i.HashedLastName,
		&i.KeyIDLastName,
		&i.AccountBrand,
		&i.Dob,
		&i.HashedDob,
		&i.KeyIDDob,
		&i.Address1,
		&i.HashedAddress1,
		&i.KeyIDAddress1,
		&i.Address2,
		&i.HashedAddress2,
		&i.KeyIDAddress2,
		&i.Email,
		&i.HashedEmail,
		&i.KeyIDEmail,
		&i.Password,
		&i.AppleID,
		&i.Phone,
		&i.HashedPhone,
		&i.KeyIDPhone,
		&i.CountryCode,
		&i.City,
		&i.HashedCity,
		&i.KeyIDCity,
		&i.State,
		&i.HashedState,
		&i.KeyIDState,
		&i.Postcode,
		&i.HashedPostcode,
		&i.KeyIDPostcode,
		&i.Country,
		&i.HashedCountry,
		&i.KeyIDCountry,
		&i.RemoteID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.HashedLatitude,
		&i.KeyIDLatitude,
		&i.Longitude,
		&i.HashedLongitude,
		&i.KeyIDLongitude,
		&i.ResetToken,
		&i.RememberToken,
		&i.StripeID,
		&i.ContactAccessCode,
		&i.Otp,
		&i.Status,
		&i.PasswordResetCode,
		&i.PasswordResetCodeStatus,
		&i.AddressType,
		&i.Notes,
		&i.ExpoToken,
		&i.NotificationPermissionGivenAt,
		&i.DeviceID,
		&i.DevicePlatform,
		&i.LastActiveTime,
		&i.LastActiveDevice,
		&i.DeletedAt,
		&i.IsReal,
	)
	return &i, err
}

const getCustomersWithAddresses = `-- name: GetCustomersWithAddresses :many
SELECT c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real, dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at
FROM
    customers c
    LEFT JOIN delivery_location dl ON c.id = dl.customer_id
WHERE
    c.deleted_at IS NULL
ORDER BY c.id DESC
`

type GetCustomersWithAddressesRow struct {
	Customer       Customer       `json:"customer"`
	ID             sql.NullInt64  `json:"id"`
	CustomerID     sql.NullInt32  `json:"customer_id"`
	Label          sql.NullString `json:"label"`
	FlatNo         sql.NullString `json:"flat_no"`
	HouseNo        sql.NullString `json:"house_no"`
	AddressLine1   sql.NullString `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	City           sql.NullString `json:"city"`
	Landmark       sql.NullString `json:"landmark"`
	PostalCode     sql.NullString `json:"postal_code"`
	DefaultAddress sql.NullBool   `json:"default_address"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

// GetCustomersWithAddresses
//
//	SELECT c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real, dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at
//	FROM
//	    customers c
//	    LEFT JOIN delivery_location dl ON c.id = dl.customer_id
//	WHERE
//	    c.deleted_at IS NULL
//	ORDER BY c.id DESC
func (q *Queries) GetCustomersWithAddresses(ctx context.Context) ([]*GetCustomersWithAddressesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersWithAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCustomersWithAddressesRow{}
	for rows.Next() {
		var i GetCustomersWithAddressesRow
		if err := rows.Scan(
			&i.Customer.ID,
			&i.Customer.Source,
			&i.Customer.OrderID,
			&i.Customer.FirstOrderOfferEligible,
			&i.Customer.SubscribeToPromotionEmails,
			&i.Customer.PromotionEmailsSubscribedAt,
			&i.Customer.FirstName,
			&i.Customer.HashedFirstName,
			&i.Customer.KeyIDFirstName,
			&i.Customer.LastName,
			&i.Customer.HashedLastName,
			&i.Customer.KeyIDLastName,
			&i.Customer.AccountBrand,
			&i.Customer.Dob,
			&i.Customer.HashedDob,
			&i.Customer.KeyIDDob,
			&i.Customer.Address1,
			&i.Customer.HashedAddress1,
			&i.Customer.KeyIDAddress1,
			&i.Customer.Address2,
			&i.Customer.HashedAddress2,
			&i.Customer.KeyIDAddress2,
			&i.Customer.Email,
			&i.Customer.HashedEmail,
			&i.Customer.KeyIDEmail,
			&i.Customer.Password,
			&i.Customer.AppleID,
			&i.Customer.Phone,
			&i.Customer.HashedPhone,
			&i.Customer.KeyIDPhone,
			&i.Customer.CountryCode,
			&i.Customer.City,
			&i.Customer.HashedCity,
			&i.Customer.KeyIDCity,
			&i.Customer.State,
			&i.Customer.HashedState,
			&i.Customer.KeyIDState,
			&i.Customer.Postcode,
			&i.Customer.HashedPostcode,
			&i.Customer.KeyIDPostcode,
			&i.Customer.Country,
			&i.Customer.HashedCountry,
			&i.Customer.KeyIDCountry,
			&i.Customer.RemoteID,
			&i.Customer.Type,
			&i.Customer.CreatedAt,
			&i.Customer.UpdatedAt,
			&i.Customer.Latitude,
			&i.Customer.HashedLatitude,
			&i.Customer.KeyIDLatitude,
			&i.Customer.Longitude,
			&i.Customer.HashedLongitude,
			&i.Customer.KeyIDLongitude,
			&i.Customer.ResetToken,
			&i.Customer.RememberToken,
			&i.Customer.StripeID,
			&i.Customer.ContactAccessCode,
			&i.Customer.Otp,
			&i.Customer.Status,
			&i.Customer.PasswordResetCode,
			&i.Customer.PasswordResetCodeStatus,
			&i.Customer.AddressType,
			&i.Customer.Notes,
			&i.Customer.ExpoToken,
			&i.Customer.NotificationPermissionGivenAt,
			&i.Customer.DeviceID,
			&i.Customer.DevicePlatform,
			&i.Customer.LastActiveTime,
			&i.Customer.LastActiveDevice,
			&i.Customer.DeletedAt,
			&i.Customer.IsReal,
			&i.ID,
			&i.CustomerID,
			&i.Label,
			&i.FlatNo,
			&i.HouseNo,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Latitude,
			&i.Longitude,
			&i.City,
			&i.Landmark,
			&i.PostalCode,
			&i.DefaultAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuestCustomer = `-- name: GetGuestCustomer :one
SELECT id, first_name, hashed_first_name, last_name, hashed_last_name
FROM customers
WHERE
    hashed_email = 'b2dba1e9d647b1efa184223800731c18ddae80ddf38ca728b138ef59ff872be0'
`

type GetGuestCustomerRow struct {
	ID              uint64         `json:"id"`
	FirstName       sql.NullString `json:"first_name"`
	HashedFirstName sql.NullString `json:"hashed_first_name"`
	LastName        sql.NullString `json:"last_name"`
	HashedLastName  sql.NullString `json:"hashed_last_name"`
}

// GetGuestCustomer
//
//	SELECT id, first_name, hashed_first_name, last_name, hashed_last_name
//	FROM customers
//	WHERE
//	    hashed_email = 'b2dba1e9d647b1efa184223800731c18ddae80ddf38ca728b138ef59ff872be0'
func (q *Queries) GetGuestCustomer(ctx context.Context) (*GetGuestCustomerRow, error) {
	row := q.db.QueryRowContext(ctx, getGuestCustomer)
	var i GetGuestCustomerRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.HashedFirstName,
		&i.LastName,
		&i.HashedLastName,
	)
	return &i, err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET
    first_name = ?,
    hashed_first_name = ?,
    key_id_first_name = ?,
    last_name = ?,
    hashed_last_name = ?,
    key_id_last_name = ?,
    hashed_phone = ?,
    phone = ?,
    key_id_phone = ?,
    country_code = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateCustomerParams struct {
	FirstName       sql.NullString `json:"first_name"`
	HashedFirstName sql.NullString `json:"hashed_first_name"`
	KeyIDFirstName  int32          `json:"key_id_first_name"`
	LastName        sql.NullString `json:"last_name"`
	HashedLastName  sql.NullString `json:"hashed_last_name"`
	KeyIDLastName   int32          `json:"key_id_last_name"`
	HashedPhone     sql.NullString `json:"hashed_phone"`
	Phone           sql.NullString `json:"phone"`
	KeyIDPhone      int32          `json:"key_id_phone"`
	CountryCode     sql.NullString `json:"country_code"`
	ID              uint64         `json:"id"`
}

// UpdateCustomer
//
//	UPDATE customers
//	SET
//	    first_name = ?,
//	    hashed_first_name = ?,
//	    key_id_first_name = ?,
//	    last_name = ?,
//	    hashed_last_name = ?,
//	    key_id_last_name = ?,
//	    hashed_phone = ?,
//	    phone = ?,
//	    key_id_phone = ?,
//	    country_code = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateCustomer(ctx context.Context, arg *UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.FirstName,
		arg.HashedFirstName,
		arg.KeyIDFirstName,
		arg.LastName,
		arg.HashedLastName,
		arg.KeyIDLastName,
		arg.HashedPhone,
		arg.Phone,
		arg.KeyIDPhone,
		arg.CountryCode,
		arg.ID,
	)
	return err
}
