// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery_location.sql

package db

import (
	"context"
	"database/sql"
)

const createDeliveryLocation = `-- name: CreateDeliveryLocation :execlastid
INSERT INTO
    delivery_location (
        customer_id,
        label,
        flat_no,
        house_no,
        address_line_1,
        address_line_2,
        latitude,
        longitude,
        city,
        landmark,
        postal_code,
        default_address,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateDeliveryLocationParams struct {
	CustomerID     int32          `json:"customer_id"`
	Label          sql.NullString `json:"label"`
	FlatNo         sql.NullString `json:"flat_no"`
	HouseNo        sql.NullString `json:"house_no"`
	AddressLine1   string         `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	City           sql.NullString `json:"city"`
	Landmark       sql.NullString `json:"landmark"`
	PostalCode     sql.NullString `json:"postal_code"`
	DefaultAddress bool           `json:"default_address"`
}

// CreateDeliveryLocation
//
//	INSERT INTO
//	    delivery_location (
//	        customer_id,
//	        label,
//	        flat_no,
//	        house_no,
//	        address_line_1,
//	        address_line_2,
//	        latitude,
//	        longitude,
//	        city,
//	        landmark,
//	        postal_code,
//	        default_address,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateDeliveryLocation(ctx context.Context, arg *CreateDeliveryLocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDeliveryLocation,
		arg.CustomerID,
		arg.Label,
		arg.FlatNo,
		arg.HouseNo,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Latitude,
		arg.Longitude,
		arg.City,
		arg.Landmark,
		arg.PostalCode,
		arg.DefaultAddress,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteDeliveryLocation = `-- name: DeleteDeliveryLocation :exec
DELETE FROM delivery_location WHERE id = ?
`

// DeleteDeliveryLocation
//
//	DELETE FROM delivery_location WHERE id = ?
func (q *Queries) DeleteDeliveryLocation(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryLocation, id)
	return err
}

const getCustomerAddresses = `-- name: GetCustomerAddresses :many
SELECT id, customer_id, label, flat_no, house_no, address_line_1, address_line_2, latitude, longitude, city, landmark, postal_code, default_address, created_at, updated_at
FROM delivery_location
WHERE
    customer_id = ?
    AND label IS NOT NULL
    AND address_line_1 IS NOT NULL
`

// GetCustomerAddresses
//
//	SELECT id, customer_id, label, flat_no, house_no, address_line_1, address_line_2, latitude, longitude, city, landmark, postal_code, default_address, created_at, updated_at
//	FROM delivery_location
//	WHERE
//	    customer_id = ?
//	    AND label IS NOT NULL
//	    AND address_line_1 IS NOT NULL
func (q *Queries) GetCustomerAddresses(ctx context.Context, customerID int32) ([]*DeliveryLocation, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerAddresses, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DeliveryLocation{}
	for rows.Next() {
		var i DeliveryLocation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Label,
			&i.FlatNo,
			&i.HouseNo,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Latitude,
			&i.Longitude,
			&i.City,
			&i.Landmark,
			&i.PostalCode,
			&i.DefaultAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderReceiver = `-- name: GetOrderReceiver :one
SELECT dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at, c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real
FROM
    delivery_location dl
    JOIN customers c ON dl.customer_id = c.id
WHERE
    dl.id = ?
    AND customer_id = ?
`

type GetOrderReceiverParams struct {
	ID         uint64 `json:"id"`
	CustomerID int32  `json:"customer_id"`
}

type GetOrderReceiverRow struct {
	DeliveryLocation DeliveryLocation `json:"delivery_location"`
	Customer         Customer         `json:"customer"`
}

// GetOrderReceiver
//
//	SELECT dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at, c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real
//	FROM
//	    delivery_location dl
//	    JOIN customers c ON dl.customer_id = c.id
//	WHERE
//	    dl.id = ?
//	    AND customer_id = ?
func (q *Queries) GetOrderReceiver(ctx context.Context, arg *GetOrderReceiverParams) (*GetOrderReceiverRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderReceiver, arg.ID, arg.CustomerID)
	var i GetOrderReceiverRow
	err := row.Scan(
		&i.DeliveryLocation.ID,
		&i.DeliveryLocation.CustomerID,
		&i.DeliveryLocation.Label,
		&i.DeliveryLocation.FlatNo,
		&i.DeliveryLocation.HouseNo,
		&i.DeliveryLocation.AddressLine1,
		&i.DeliveryLocation.AddressLine2,
		&i.DeliveryLocation.Latitude,
		&i.DeliveryLocation.Longitude,
		&i.DeliveryLocation.City,
		&i.DeliveryLocation.Landmark,
		&i.DeliveryLocation.PostalCode,
		&i.DeliveryLocation.DefaultAddress,
		&i.DeliveryLocation.CreatedAt,
		&i.DeliveryLocation.UpdatedAt,
		&i.Customer.ID,
		&i.Customer.Source,
		&i.Customer.OrderID,
		&i.Customer.FirstOrderOfferEligible,
		&i.Customer.SubscribeToPromotionEmails,
		&i.Customer.PromotionEmailsSubscribedAt,
		&i.Customer.FirstName,
		&i.Customer.HashedFirstName,
		&i.Customer.KeyIDFirstName,
		&i.Customer.LastName,
		&i.Customer.HashedLastName,
		&i.Customer.KeyIDLastName,
		&i.Customer.AccountBrand,
		&i.Customer.Dob,
		&i.Customer.HashedDob,
		&i.Customer.KeyIDDob,
		&i.Customer.Address1,
		&i.Customer.HashedAddress1,
		&i.Customer.KeyIDAddress1,
		&i.Customer.Address2,
		&i.Customer.HashedAddress2,
		&i.Customer.KeyIDAddress2,
		&i.Customer.Email,
		&i.Customer.HashedEmail,
		&i.Customer.KeyIDEmail,
		&i.Customer.Password,
		&i.Customer.AppleID,
		&i.Customer.Phone,
		&i.Customer.HashedPhone,
		&i.Customer.KeyIDPhone,
		&i.Customer.CountryCode,
		&i.Customer.City,
		&i.Customer.HashedCity,
		&i.Customer.KeyIDCity,
		&i.Customer.State,
		&i.Customer.HashedState,
		&i.Customer.KeyIDState,
		&i.Customer.Postcode,
		&i.Customer.HashedPostcode,
		&i.Customer.KeyIDPostcode,
		&i.Customer.Country,
		&i.Customer.HashedCountry,
		&i.Customer.KeyIDCountry,
		&i.Customer.RemoteID,
		&i.Customer.Type,
		&i.Customer.CreatedAt,
		&i.Customer.UpdatedAt,
		&i.Customer.Latitude,
		&i.Customer.HashedLatitude,
		&i.Customer.KeyIDLatitude,
		&i.Customer.Longitude,
		&i.Customer.HashedLongitude,
		&i.Customer.KeyIDLongitude,
		&i.Customer.ResetToken,
		&i.Customer.RememberToken,
		&i.Customer.StripeID,
		&i.Customer.ContactAccessCode,
		&i.Customer.Otp,
		&i.Customer.Status,
		&i.Customer.PasswordResetCode,
		&i.Customer.PasswordResetCodeStatus,
		&i.Customer.AddressType,
		&i.Customer.Notes,
		&i.Customer.ExpoToken,
		&i.Customer.NotificationPermissionGivenAt,
		&i.Customer.DeviceID,
		&i.Customer.DevicePlatform,
		&i.Customer.LastActiveTime,
		&i.Customer.LastActiveDevice,
		&i.Customer.DeletedAt,
		&i.Customer.IsReal,
	)
	return &i, err
}

const makeCustomerAddressNonDefault = `-- name: MakeCustomerAddressNonDefault :exec
UPDATE delivery_location
SET
    default_address = 0
WHERE
    customer_id = ?
`

// MakeCustomerAddressNonDefault
//
//	UPDATE delivery_location
//	SET
//	    default_address = 0
//	WHERE
//	    customer_id = ?
func (q *Queries) MakeCustomerAddressNonDefault(ctx context.Context, customerID int32) error {
	_, err := q.db.ExecContext(ctx, makeCustomerAddressNonDefault, customerID)
	return err
}

const updateDeliveryLocation = `-- name: UpdateDeliveryLocation :exec
UPDATE delivery_location
SET
    label = ?,
    flat_no = ?,
    house_no = ?,
    address_line_1 = ?,
    address_line_2 = ?,
    latitude = ?,
    longitude = ?,
    city = ?,
    landmark = ?,
    postal_code = ?,
    default_address = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND customer_id = ?
`

type UpdateDeliveryLocationParams struct {
	Label          sql.NullString `json:"label"`
	FlatNo         sql.NullString `json:"flat_no"`
	HouseNo        sql.NullString `json:"house_no"`
	AddressLine1   string         `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	City           sql.NullString `json:"city"`
	Landmark       sql.NullString `json:"landmark"`
	PostalCode     sql.NullString `json:"postal_code"`
	DefaultAddress bool           `json:"default_address"`
	ID             uint64         `json:"id"`
	CustomerID     int32          `json:"customer_id"`
}

// UpdateDeliveryLocation
//
//	UPDATE delivery_location
//	SET
//	    label = ?,
//	    flat_no = ?,
//	    house_no = ?,
//	    address_line_1 = ?,
//	    address_line_2 = ?,
//	    latitude = ?,
//	    longitude = ?,
//	    city = ?,
//	    landmark = ?,
//	    postal_code = ?,
//	    default_address = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
//	    AND customer_id = ?
func (q *Queries) UpdateDeliveryLocation(ctx context.Context, arg *UpdateDeliveryLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryLocation,
		arg.Label,
		arg.FlatNo,
		arg.HouseNo,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Latitude,
		arg.Longitude,
		arg.City,
		arg.Landmark,
		arg.PostalCode,
		arg.DefaultAddress,
		arg.ID,
		arg.CustomerID,
	)
	return err
}
