// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deliveryPlatform_query.sql

package db

import (
	"context"
	"database/sql"
)

const getDeliveryPlatform = `-- name: GetDeliveryPlatform :one
SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name, wb.brand_name AS brand_name
FROM delivery_platform dp
LEFT JOIN platform p ON dp.platform_id = p.id
LEFT JOIN webshop_brand wb ON dp.webshop_brand_id = wb.id
WHERE
    outlet_id = ?
    AND webshop_brand_id = ?
    AND platform_id = ?
`

type GetDeliveryPlatformParams struct {
	OutletID       sql.NullInt64 `json:"outlet_id"`
	WebshopBrandID sql.NullInt32 `json:"webshop_brand_id"`
	PlatformID     sql.NullInt32 `json:"platform_id"`
}

type GetDeliveryPlatformRow struct {
	ID                 uint64         `json:"id"`
	PlatformID         sql.NullInt32  `json:"platform_id"`
	Name               string         `json:"name"`
	WebshopBrandID     sql.NullInt32  `json:"webshop_brand_id"`
	ApiUrl             sql.NullString `json:"api_url"`
	AuthUrl            sql.NullString `json:"auth_url"`
	ApiParameters      sql.NullString `json:"api_parameters"`
	Logo               sql.NullString `json:"logo"`
	Status             string         `json:"status"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	OutletCode         sql.NullString `json:"outlet_code"`
	SiteID             sql.NullString `json:"site_id"`
	BranchID           sql.NullString `json:"branch_id"`
	AccessToken        sql.NullString `json:"access_token"`
	PrimaryColor       sql.NullString `json:"primary_color"`
	CanUpload          bool           `json:"can_upload"`
	AutoAccepting      bool           `json:"auto_accepting"`
	FranchiseID        int32          `json:"franchise_id"`
	OutletID           sql.NullInt64  `json:"outlet_id"`
	MenuID             sql.NullString `json:"menu_id"`
	MenuUploadStatus   sql.NullString `json:"menu_upload_status"`
	StoreStatus        sql.NullString `json:"store_status"`
	AvailableFrom      sql.NullTime   `json:"available_from"`
	TenderTypes        sql.NullString `json:"tender_types"`
	IsMaster           bool           `json:"is_master"`
	ParentPlatform     sql.NullInt32  `json:"parent_platform"`
	PrepTime           sql.NullInt32  `json:"prep_time"`
	OwnDriver          bool           `json:"own_driver"`
	MenuPublishedAt    sql.NullTime   `json:"menu_published_at"`
	WebshopSetupStatus bool           `json:"webshop_setup_status"`
	HasCashPayment     bool           `json:"has_cash_payment"`
	HasCardPayment     bool           `json:"has_card_payment"`
	SelectedMenu       sql.NullInt32  `json:"selected_menu"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	PlatformName       sql.NullString `json:"platform_name"`
	BrandName          sql.NullString `json:"brand_name"`
}

// GetDeliveryPlatform
//
//	SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name, wb.brand_name AS brand_name
//	FROM delivery_platform dp
//	LEFT JOIN platform p ON dp.platform_id = p.id
//	LEFT JOIN webshop_brand wb ON dp.webshop_brand_id = wb.id
//	WHERE
//	    outlet_id = ?
//	    AND webshop_brand_id = ?
//	    AND platform_id = ?
func (q *Queries) GetDeliveryPlatform(ctx context.Context, arg *GetDeliveryPlatformParams) (*GetDeliveryPlatformRow, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryPlatform, arg.OutletID, arg.WebshopBrandID, arg.PlatformID)
	var i GetDeliveryPlatformRow
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.Name,
		&i.WebshopBrandID,
		&i.ApiUrl,
		&i.AuthUrl,
		&i.ApiParameters,
		&i.Logo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutletCode,
		&i.SiteID,
		&i.BranchID,
		&i.AccessToken,
		&i.PrimaryColor,
		&i.CanUpload,
		&i.AutoAccepting,
		&i.FranchiseID,
		&i.OutletID,
		&i.MenuID,
		&i.MenuUploadStatus,
		&i.StoreStatus,
		&i.AvailableFrom,
		&i.TenderTypes,
		&i.IsMaster,
		&i.ParentPlatform,
		&i.PrepTime,
		&i.OwnDriver,
		&i.MenuPublishedAt,
		&i.WebshopSetupStatus,
		&i.HasCashPayment,
		&i.HasCardPayment,
		&i.SelectedMenu,
		&i.DeletedAt,
		&i.PlatformName,
		&i.BrandName,
	)
	return &i, err
}

const getDeliveryPlatformById = `-- name: GetDeliveryPlatformById :one
SELECT id, platform_id, name, webshop_brand_id, api_url, auth_url, api_parameters, logo, status, created_at, updated_at, outlet_code, site_id, branch_id, access_token, primary_color, can_upload, auto_accepting, franchise_id, outlet_id, menu_id, menu_upload_status, store_status, available_from, tender_types, is_master, parent_platform, prep_time, own_driver, menu_published_at, webshop_setup_status, has_cash_payment, has_card_payment, selected_menu, deleted_at FROM delivery_platform WHERE id = ?
`

// GetDeliveryPlatformById
//
//	SELECT id, platform_id, name, webshop_brand_id, api_url, auth_url, api_parameters, logo, status, created_at, updated_at, outlet_code, site_id, branch_id, access_token, primary_color, can_upload, auto_accepting, franchise_id, outlet_id, menu_id, menu_upload_status, store_status, available_from, tender_types, is_master, parent_platform, prep_time, own_driver, menu_published_at, webshop_setup_status, has_cash_payment, has_card_payment, selected_menu, deleted_at FROM delivery_platform WHERE id = ?
func (q *Queries) GetDeliveryPlatformById(ctx context.Context, id uint64) (*DeliveryPlatform, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryPlatformById, id)
	var i DeliveryPlatform
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.Name,
		&i.WebshopBrandID,
		&i.ApiUrl,
		&i.AuthUrl,
		&i.ApiParameters,
		&i.Logo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutletCode,
		&i.SiteID,
		&i.BranchID,
		&i.AccessToken,
		&i.PrimaryColor,
		&i.CanUpload,
		&i.AutoAccepting,
		&i.FranchiseID,
		&i.OutletID,
		&i.MenuID,
		&i.MenuUploadStatus,
		&i.StoreStatus,
		&i.AvailableFrom,
		&i.TenderTypes,
		&i.IsMaster,
		&i.ParentPlatform,
		&i.PrepTime,
		&i.OwnDriver,
		&i.MenuPublishedAt,
		&i.WebshopSetupStatus,
		&i.HasCashPayment,
		&i.HasCardPayment,
		&i.SelectedMenu,
		&i.DeletedAt,
	)
	return &i, err
}

const getDeliveryPlatforms = `-- name: GetDeliveryPlatforms :many
SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name
FROM
    delivery_platform dp
    LEFT JOIN platform p ON dp.platform_id = p.id
    WHERE
        (
            ? IS NULL
            OR dp.outlet_id = ?
        )
        AND (
            ? IS NULL
            OR dp.webshop_brand_id = ?
        )
`

type GetDeliveryPlatformsParams struct {
	OutletID sql.NullInt64 `json:"outlet_id"`
	BrandID  sql.NullInt32 `json:"brand_id"`
}

type GetDeliveryPlatformsRow struct {
	ID                 uint64         `json:"id"`
	PlatformID         sql.NullInt32  `json:"platform_id"`
	Name               string         `json:"name"`
	WebshopBrandID     sql.NullInt32  `json:"webshop_brand_id"`
	ApiUrl             sql.NullString `json:"api_url"`
	AuthUrl            sql.NullString `json:"auth_url"`
	ApiParameters      sql.NullString `json:"api_parameters"`
	Logo               sql.NullString `json:"logo"`
	Status             string         `json:"status"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	OutletCode         sql.NullString `json:"outlet_code"`
	SiteID             sql.NullString `json:"site_id"`
	BranchID           sql.NullString `json:"branch_id"`
	AccessToken        sql.NullString `json:"access_token"`
	PrimaryColor       sql.NullString `json:"primary_color"`
	CanUpload          bool           `json:"can_upload"`
	AutoAccepting      bool           `json:"auto_accepting"`
	FranchiseID        int32          `json:"franchise_id"`
	OutletID           sql.NullInt64  `json:"outlet_id"`
	MenuID             sql.NullString `json:"menu_id"`
	MenuUploadStatus   sql.NullString `json:"menu_upload_status"`
	StoreStatus        sql.NullString `json:"store_status"`
	AvailableFrom      sql.NullTime   `json:"available_from"`
	TenderTypes        sql.NullString `json:"tender_types"`
	IsMaster           bool           `json:"is_master"`
	ParentPlatform     sql.NullInt32  `json:"parent_platform"`
	PrepTime           sql.NullInt32  `json:"prep_time"`
	OwnDriver          bool           `json:"own_driver"`
	MenuPublishedAt    sql.NullTime   `json:"menu_published_at"`
	WebshopSetupStatus bool           `json:"webshop_setup_status"`
	HasCashPayment     bool           `json:"has_cash_payment"`
	HasCardPayment     bool           `json:"has_card_payment"`
	SelectedMenu       sql.NullInt32  `json:"selected_menu"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	PlatformName       sql.NullString `json:"platform_name"`
}

// GetDeliveryPlatforms
//
//	SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name
//	FROM
//	    delivery_platform dp
//	    LEFT JOIN platform p ON dp.platform_id = p.id
//	    WHERE
//	        (
//	            ? IS NULL
//	            OR dp.outlet_id = ?
//	        )
//	        AND (
//	            ? IS NULL
//	            OR dp.webshop_brand_id = ?
//	        )
func (q *Queries) GetDeliveryPlatforms(ctx context.Context, arg *GetDeliveryPlatformsParams) ([]*GetDeliveryPlatformsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveryPlatforms,
		arg.OutletID,
		arg.OutletID,
		arg.BrandID,
		arg.BrandID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDeliveryPlatformsRow{}
	for rows.Next() {
		var i GetDeliveryPlatformsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.Name,
			&i.WebshopBrandID,
			&i.ApiUrl,
			&i.AuthUrl,
			&i.ApiParameters,
			&i.Logo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OutletCode,
			&i.SiteID,
			&i.BranchID,
			&i.AccessToken,
			&i.PrimaryColor,
			&i.CanUpload,
			&i.AutoAccepting,
			&i.FranchiseID,
			&i.OutletID,
			&i.MenuID,
			&i.MenuUploadStatus,
			&i.StoreStatus,
			&i.AvailableFrom,
			&i.TenderTypes,
			&i.IsMaster,
			&i.ParentPlatform,
			&i.PrepTime,
			&i.OwnDriver,
			&i.MenuPublishedAt,
			&i.WebshopSetupStatus,
			&i.HasCashPayment,
			&i.HasCardPayment,
			&i.SelectedMenu,
			&i.DeletedAt,
			&i.PlatformName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
