// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dg_pos_tables_query.sql

package db

import (
	"context"
	"database/sql"
)

const addOngoingOrderForTable = `-- name: AddOngoingOrderForTable :exec
INSERT INTO
    dg_pos_tables_ongoing_orders (table_id, order_id)
VALUES (?, ?)
`

type AddOngoingOrderForTableParams struct {
	TableID uint64 `json:"table_id"`
	OrderID uint64 `json:"order_id"`
}

// AddOngoingOrderForTable
//
//	INSERT INTO
//	    dg_pos_tables_ongoing_orders (table_id, order_id)
//	VALUES (?, ?)
func (q *Queries) AddOngoingOrderForTable(ctx context.Context, arg *AddOngoingOrderForTableParams) error {
	_, err := q.db.ExecContext(ctx, addOngoingOrderForTable, arg.TableID, arg.OrderID)
	return err
}

const getDgPosTableName = `-- name: GetDgPosTableName :one
SELECT name FROM dg_pos_tables WHERE id = ?
`

// GetDgPosTableName
//
//	SELECT name FROM dg_pos_tables WHERE id = ?
func (q *Queries) GetDgPosTableName(ctx context.Context, id uint64) (string, error) {
	row := q.db.QueryRowContext(ctx, getDgPosTableName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getDgPosTableNameByTableOrderingsID = `-- name: GetDgPosTableNameByTableOrderingsID :one
SELECT name FROM dg_pos_tables WHERE table_orderings_id = ?
`

// GetDgPosTableNameByTableOrderingsID
//
//	SELECT name FROM dg_pos_tables WHERE table_orderings_id = ?
func (q *Queries) GetDgPosTableNameByTableOrderingsID(ctx context.Context, tableOrderingsID sql.NullInt64) (string, error) {
	row := q.db.QueryRowContext(ctx, getDgPosTableNameByTableOrderingsID, tableOrderingsID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getOngoingOrdersForTable = `-- name: GetOngoingOrdersForTable :many
SELECT 
    too.id, too.table_id, too.order_id, too.created_at, too.updated_at,
    o.display_order_id,
    o.status,
    o.total_amount,
    o.customer_name,
    o.order_session_id,
    o.is_table_order,
    o.shipping_method,
    o.created_at,
    CASE WHEN o.payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
    p.logo AS platform_logo,
    tom.name AS table_order_method_name
FROM dg_pos_tables_ongoing_orders too 
JOIN ` + "`" + `order` + "`" + ` o ON too.order_id = o.id
JOIN delivery_platform dp ON o.platform_id = dp.id
JOIN platform p ON dp.platform_id = p.id
LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
WHERE too.table_id = ?
`

type GetOngoingOrdersForTableRow struct {
	ID                   uint64         `json:"id"`
	TableID              uint64         `json:"table_id"`
	OrderID              uint64         `json:"order_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	DisplayOrderID       sql.NullString `json:"display_order_id"`
	Status               string         `json:"status"`
	TotalAmount          int32          `json:"total_amount"`
	CustomerName         sql.NullString `json:"customer_name"`
	OrderSessionID       sql.NullInt32  `json:"order_session_id"`
	IsTableOrder         bool           `json:"is_table_order"`
	ShippingMethod       sql.NullString `json:"shipping_method"`
	CreatedAt_2          sql.NullTime   `json:"created_at_2"`
	PaymentStatus        string         `json:"payment_status"`
	PlatformLogo         sql.NullString `json:"platform_logo"`
	TableOrderMethodName sql.NullString `json:"table_order_method_name"`
}

// GetOngoingOrdersForTable
//
//	SELECT
//	    too.id, too.table_id, too.order_id, too.created_at, too.updated_at,
//	    o.display_order_id,
//	    o.status,
//	    o.total_amount,
//	    o.customer_name,
//	    o.order_session_id,
//	    o.is_table_order,
//	    o.shipping_method,
//	    o.created_at,
//	    CASE WHEN o.payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
//	    p.logo AS platform_logo,
//	    tom.name AS table_order_method_name
//	FROM dg_pos_tables_ongoing_orders too
//	JOIN `order` o ON too.order_id = o.id
//	JOIN delivery_platform dp ON o.platform_id = dp.id
//	JOIN platform p ON dp.platform_id = p.id
//	LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
//	WHERE too.table_id = ?
func (q *Queries) GetOngoingOrdersForTable(ctx context.Context, tableID uint64) ([]*GetOngoingOrdersForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, getOngoingOrdersForTable, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOngoingOrdersForTableRow{}
	for rows.Next() {
		var i GetOngoingOrdersForTableRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayOrderID,
			&i.Status,
			&i.TotalAmount,
			&i.CustomerName,
			&i.OrderSessionID,
			&i.IsTableOrder,
			&i.ShippingMethod,
			&i.CreatedAt_2,
			&i.PaymentStatus,
			&i.PlatformLogo,
			&i.TableOrderMethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE id = ? LIMIT 1
`

// GetTableByID
//
//	SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE id = ? LIMIT 1
func (q *Queries) GetTableByID(ctx context.Context, id uint64) (*DgPosTable, error) {
	row := q.db.QueryRowContext(ctx, getTableByID, id)
	var i DgPosTable
	err := row.Scan(
		&i.ID,
		&i.TableOrderingsID,
		&i.ShopID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.SeatCount,
		&i.Status,
		&i.OngoingOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTableByTableOrderingsID = `-- name: GetTableByTableOrderingsID :one
SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE table_orderings_id = ? LIMIT 1
`

// GetTableByTableOrderingsID
//
//	SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE table_orderings_id = ? LIMIT 1
func (q *Queries) GetTableByTableOrderingsID(ctx context.Context, tableOrderingsID sql.NullInt64) (*DgPosTable, error) {
	row := q.db.QueryRowContext(ctx, getTableByTableOrderingsID, tableOrderingsID)
	var i DgPosTable
	err := row.Scan(
		&i.ID,
		&i.TableOrderingsID,
		&i.ShopID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.SeatCount,
		&i.Status,
		&i.OngoingOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTables = `-- name: GetTables :many
SELECT tbs.id, tbs.table_orderings_id, tbs.shop_id, tbs.brand_id, tbs.name, tbs.description, tbs.seat_count, tbs.status, tbs.ongoing_order_id, tbs.created_at, tbs.updated_at
FROM
    dg_pos_tables tbs
WHERE (
        ? IS NULL
        OR tbs.shop_id = ?
    )
    AND (
        ? IS NULL
        OR tbs.brand_id = ?
    )
`

type GetTablesParams struct {
	OutletID sql.NullInt32 `json:"outlet_id"`
	BrandID  sql.NullInt32 `json:"brand_id"`
}

// GetTables
//
//	SELECT tbs.id, tbs.table_orderings_id, tbs.shop_id, tbs.brand_id, tbs.name, tbs.description, tbs.seat_count, tbs.status, tbs.ongoing_order_id, tbs.created_at, tbs.updated_at
//	FROM
//	    dg_pos_tables tbs
//	WHERE (
//	        ? IS NULL
//	        OR tbs.shop_id = ?
//	    )
//	    AND (
//	        ? IS NULL
//	        OR tbs.brand_id = ?
//	    )
func (q *Queries) GetTables(ctx context.Context, arg *GetTablesParams) ([]*DgPosTable, error) {
	rows, err := q.db.QueryContext(ctx, getTables,
		arg.OutletID,
		arg.OutletID,
		arg.BrandID,
		arg.BrandID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DgPosTable{}
	for rows.Next() {
		var i DgPosTable
		if err := rows.Scan(
			&i.ID,
			&i.TableOrderingsID,
			&i.ShopID,
			&i.BrandID,
			&i.Name,
			&i.Description,
			&i.SeatCount,
			&i.Status,
			&i.OngoingOrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOngoingOrderForTable = `-- name: RemoveOngoingOrderForTable :exec
DELETE FROM dg_pos_tables_ongoing_orders WHERE table_id = ?
`

// RemoveOngoingOrderForTable
//
//	DELETE FROM dg_pos_tables_ongoing_orders WHERE table_id = ?
func (q *Queries) RemoveOngoingOrderForTable(ctx context.Context, tableID uint64) error {
	_, err := q.db.ExecContext(ctx, removeOngoingOrderForTable, tableID)
	return err
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE dg_pos_tables
SET
    status = ?
WHERE
    id = ?
`

type UpdateTableStatusParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
}

// UpdateTableStatus
//
//	UPDATE dg_pos_tables
//	SET
//	    status = ?
//	WHERE
//	    id = ?
func (q *Queries) UpdateTableStatus(ctx context.Context, arg *UpdateTableStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTableStatus, arg.Status, arg.ID)
	return err
}

const updateTableStatusByTableOrderingsID = `-- name: UpdateTableStatusByTableOrderingsID :exec
UPDATE dg_pos_tables
SET
    status = ?
WHERE
    table_orderings_id = ?
`

type UpdateTableStatusByTableOrderingsIDParams struct {
	Status           string        `json:"status"`
	TableOrderingsID sql.NullInt64 `json:"table_orderings_id"`
}

// UpdateTableStatusByTableOrderingsID
//
//	UPDATE dg_pos_tables
//	SET
//	    status = ?
//	WHERE
//	    table_orderings_id = ?
func (q *Queries) UpdateTableStatusByTableOrderingsID(ctx context.Context, arg *UpdateTableStatusByTableOrderingsIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTableStatusByTableOrderingsID, arg.Status, arg.TableOrderingsID)
	return err
}
