// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dg_pos_order_location_query.sql

package db

import (
	"context"
	"database/sql"
)

const createDgPosOrderLocation = `-- name: CreateDgPosOrderLocation :exec
INSERT INTO
    ` + "`" + `dg_pos_order_location` + "`" + ` (
        order_id,
        first_name,
        last_name,
        email,
        country_code,
        country,
        phone,
        flat_no,
        house_no,
        address_line_1,
        address_line_2,
        city,
        landmark,
        postcode,
        latitude,
        longitude,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateDgPosOrderLocationParams struct {
	OrderID      int32          `json:"order_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	CountryCode  string         `json:"country_code"`
	Country      sql.NullString `json:"country"`
	Phone        string         `json:"phone"`
	FlatNo       sql.NullString `json:"flat_no"`
	HouseNo      sql.NullString `json:"house_no"`
	AddressLine1 string         `json:"address_line_1"`
	AddressLine2 sql.NullString `json:"address_line_2"`
	City         sql.NullString `json:"city"`
	Landmark     sql.NullString `json:"landmark"`
	Postcode     sql.NullString `json:"postcode"`
	Latitude     sql.NullString `json:"latitude"`
	Longitude    sql.NullString `json:"longitude"`
}

// CreateDgPosOrderLocation
//
//	INSERT INTO
//	    `dg_pos_order_location` (
//	        order_id,
//	        first_name,
//	        last_name,
//	        email,
//	        country_code,
//	        country,
//	        phone,
//	        flat_no,
//	        house_no,
//	        address_line_1,
//	        address_line_2,
//	        city,
//	        landmark,
//	        postcode,
//	        latitude,
//	        longitude,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateDgPosOrderLocation(ctx context.Context, arg *CreateDgPosOrderLocationParams) error {
	_, err := q.db.ExecContext(ctx, createDgPosOrderLocation,
		arg.OrderID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.CountryCode,
		arg.Country,
		arg.Phone,
		arg.FlatNo,
		arg.HouseNo,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.Landmark,
		arg.Postcode,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const getDgPosOrderLocation = `-- name: GetDgPosOrderLocation :one
SELECT id, order_id, first_name, last_name, email, country_code, country, phone, flat_no, house_no, address_line_1, address_line_2, city, landmark, postcode, latitude, longitude, created_at, updated_at FROM dg_pos_order_location WHERE order_id = ?
`

// GetDgPosOrderLocation
//
//	SELECT id, order_id, first_name, last_name, email, country_code, country, phone, flat_no, house_no, address_line_1, address_line_2, city, landmark, postcode, latitude, longitude, created_at, updated_at FROM dg_pos_order_location WHERE order_id = ?
func (q *Queries) GetDgPosOrderLocation(ctx context.Context, orderID int32) (*DgPosOrderLocation, error) {
	row := q.db.QueryRowContext(ctx, getDgPosOrderLocation, orderID)
	var i DgPosOrderLocation
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CountryCode,
		&i.Country,
		&i.Phone,
		&i.FlatNo,
		&i.HouseNo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Landmark,
		&i.Postcode,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWebshopOrderLocation = `-- name: GetWebshopOrderLocation :one
SELECT id, order_tmp_id, order_id, type, first_name, last_name, email, phone, country_code, address_line_1, address_line_2, city, state, postcode, country, latitude, longitude, created_at, updated_at FROM webshop_order_location WHERE order_id = ?
`

// GetWebshopOrderLocation
//
//	SELECT id, order_tmp_id, order_id, type, first_name, last_name, email, phone, country_code, address_line_1, address_line_2, city, state, postcode, country, latitude, longitude, created_at, updated_at FROM webshop_order_location WHERE order_id = ?
func (q *Queries) GetWebshopOrderLocation(ctx context.Context, orderID sql.NullInt64) (*WebshopOrderLocation, error) {
	row := q.db.QueryRowContext(ctx, getWebshopOrderLocation, orderID)
	var i WebshopOrderLocation
	err := row.Scan(
		&i.ID,
		&i.OrderTmpID,
		&i.OrderID,
		&i.Type,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CountryCode,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Postcode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
