// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dg_pos_user_activities.sql

package db

import (
	"context"
	"database/sql"
)

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO
    ` + "`" + `dg_pos_user_activities` + "`" + ` (
        brand_id,
        shop_id,
        log_name,
        description,
        event,
        subject_id,
        causer_id
    )
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	BrandID     sql.NullInt64  `json:"brand_id"`
	ShopID      sql.NullInt64  `json:"shop_id"`
	LogName     string         `json:"log_name"`
	Description sql.NullString `json:"description"`
	Event       string         `json:"event"`
	SubjectID   int64          `json:"subject_id"`
	CauserID    int64          `json:"causer_id"`
}

// CreateActivityLog
//
//	INSERT INTO
//	    `dg_pos_user_activities` (
//	        brand_id,
//	        shop_id,
//	        log_name,
//	        description,
//	        event,
//	        subject_id,
//	        causer_id
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateActivityLog(ctx context.Context, arg *CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.BrandID,
		arg.ShopID,
		arg.LogName,
		arg.Description,
		arg.Event,
		arg.SubjectID,
		arg.CauserID,
	)
	return err
}
