// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dg_pos_tmp_payments.sql

package db

import (
	"context"
	"database/sql"
)

const deleteDgPosTmpPayment = `-- name: DeleteDgPosTmpPayment :exec
DELETE FROM dg_pos_tmp_payments WHERE type_id = ?
`

// DeleteDgPosTmpPayment
//
//	DELETE FROM dg_pos_tmp_payments WHERE type_id = ?
func (q *Queries) DeleteDgPosTmpPayment(ctx context.Context, typeID string) error {
	_, err := q.db.ExecContext(ctx, deleteDgPosTmpPayment, typeID)
	return err
}

const getDgPosTmpPayments = `-- name: GetDgPosTmpPayments :many
SELECT id, type_id, type, payment_amount, payment_mode, transaction_id, created_at, updated_at FROM dg_pos_tmp_payments WHERE type_id = ?
`

// GetDgPosTmpPayments
//
//	SELECT id, type_id, type, payment_amount, payment_mode, transaction_id, created_at, updated_at FROM dg_pos_tmp_payments WHERE type_id = ?
func (q *Queries) GetDgPosTmpPayments(ctx context.Context, typeID string) ([]*DgPosTmpPayment, error) {
	rows, err := q.db.QueryContext(ctx, getDgPosTmpPayments, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DgPosTmpPayment{}
	for rows.Next() {
		var i DgPosTmpPayment
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Type,
			&i.PaymentAmount,
			&i.PaymentMode,
			&i.TransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDgPosTmpPayment = `-- name: InsertDgPosTmpPayment :exec
INSERT INTO
    dg_pos_tmp_payments (
        ` + "`" + `type_id` + "`" + `,
        ` + "`" + `type` + "`" + `,
        payment_mode,
        payment_amount,
        transaction_id,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type InsertDgPosTmpPaymentParams struct {
	TypeID        string         `json:"type_id"`
	Type          string         `json:"type"`
	PaymentMode   string         `json:"payment_mode"`
	PaymentAmount int32          `json:"payment_amount"`
	TransactionID sql.NullString `json:"transaction_id"`
}

// InsertDgPosTmpPayment
//
//	INSERT INTO
//	    dg_pos_tmp_payments (
//	        `type_id`,
//	        `type`,
//	        payment_mode,
//	        payment_amount,
//	        transaction_id,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) InsertDgPosTmpPayment(ctx context.Context, arg *InsertDgPosTmpPaymentParams) error {
	_, err := q.db.ExecContext(ctx, insertDgPosTmpPayment,
		arg.TypeID,
		arg.Type,
		arg.PaymentMode,
		arg.PaymentAmount,
		arg.TransactionID,
	)
	return err
}
