// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dg_pos_shop_configs.sql

package db

import (
	"context"
	"encoding/json"
)

const getShopConfig = `-- name: GetShopConfig :one
SELECT id, shop_id, brand_id, terminal_id, config_type, data, created_at, updated_at
FROM dg_pos_shop_config
WHERE
    config_type = ?
    AND shop_id = ?
    AND brand_id = ?
    AND terminal_id = ?
`

type GetShopConfigParams struct {
	ConfigType string `json:"config_type"`
	ShopID     int32  `json:"shop_id"`
	BrandID    int32  `json:"brand_id"`
	TerminalID int32  `json:"terminal_id"`
}

// GetShopConfig
//
//	SELECT id, shop_id, brand_id, terminal_id, config_type, data, created_at, updated_at
//	FROM dg_pos_shop_config
//	WHERE
//	    config_type = ?
//	    AND shop_id = ?
//	    AND brand_id = ?
//	    AND terminal_id = ?
func (q *Queries) GetShopConfig(ctx context.Context, arg *GetShopConfigParams) (*DgPosShopConfig, error) {
	row := q.db.QueryRowContext(ctx, getShopConfig,
		arg.ConfigType,
		arg.ShopID,
		arg.BrandID,
		arg.TerminalID,
	)
	var i DgPosShopConfig
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.BrandID,
		&i.TerminalID,
		&i.ConfigType,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertShopConfig = `-- name: UpsertShopConfig :exec
INSERT INTO
    dg_pos_shop_config (
        id,
        shop_id,
        brand_id,
        terminal_id,
        config_type,
        data
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
ON DUPLICATE KEY UPDATE
    data = VALUES(data)
`

type UpsertShopConfigParams struct {
	ID         uint64          `json:"id"`
	ShopID     int32           `json:"shop_id"`
	BrandID    int32           `json:"brand_id"`
	TerminalID int32           `json:"terminal_id"`
	ConfigType string          `json:"config_type"`
	Data       json.RawMessage `json:"data"`
}

// UpsertShopConfig
//
//	INSERT INTO
//	    dg_pos_shop_config (
//	        id,
//	        shop_id,
//	        brand_id,
//	        terminal_id,
//	        config_type,
//	        data
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?
//	    )
//	ON DUPLICATE KEY UPDATE
//	    data = VALUES(data)
func (q *Queries) UpsertShopConfig(ctx context.Context, arg *UpsertShopConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertShopConfig,
		arg.ID,
		arg.ShopID,
		arg.BrandID,
		arg.TerminalID,
		arg.ConfigType,
		arg.Data,
	)
	return err
}
