// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: encryption.sql

package db

import (
	"context"
)

const getEncryptionKeys = `-- name: GetEncryptionKeys :many
SELECT id, ` + "`" + `key` + "`" + `, created_at, updated_at FROM encryption_keys
`

// GetEncryptionKeys
//
//	SELECT id, `key`, created_at, updated_at FROM encryption_keys
func (q *Queries) GetEncryptionKeys(ctx context.Context) ([]*EncryptionKey, error) {
	rows, err := q.db.QueryContext(ctx, getEncryptionKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EncryptionKey{}
	for rows.Next() {
		var i EncryptionKey
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestEncryptionKey = `-- name: GetLatestEncryptionKey :one
SELECT id, ` + "`" + `key` + "`" + `, created_at, updated_at FROM encryption_keys ORDER BY id DESC LIMIT 1
`

// GetLatestEncryptionKey
//
//	SELECT id, `key`, created_at, updated_at FROM encryption_keys ORDER BY id DESC LIMIT 1
func (q *Queries) GetLatestEncryptionKey(ctx context.Context) (*EncryptionKey, error) {
	row := q.db.QueryRowContext(ctx, getLatestEncryptionKey)
	var i EncryptionKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
