// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ShopTaxMode string

const (
	ShopTaxModeInclusive ShopTaxMode = "inclusive"
	ShopTaxModeExclusive ShopTaxMode = "exclusive"
	ShopTaxModeNone      ShopTaxMode = "none"
)

func (e *ShopTaxMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopTaxMode(s)
	case string:
		*e = ShopTaxMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopTaxMode: %T", src)
	}
	return nil
}

type NullShopTaxMode struct {
	ShopTaxMode ShopTaxMode `json:"shop_tax_mode"`
	Valid       bool        `json:"valid"` // Valid is true if ShopTaxMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopTaxMode) Scan(value interface{}) error {
	if value == nil {
		ns.ShopTaxMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopTaxMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopTaxMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopTaxMode), nil
}

type BasicDetail struct {
	ID                        uint32         `json:"id"`
	BrandLogo                 string         `json:"brand_logo"`
	HeroImage                 string         `json:"hero_image"`
	BrandName                 string         `json:"brand_name"`
	Slogan                    string         `json:"slogan"`
	OpenTime                  time.Time      `json:"open_time"`
	CloseTime                 time.Time      `json:"close_time"`
	WebshopBrandID            int32          `json:"webshop_brand_id"`
	AboutAdjustmentImageLeft  string         `json:"about_adjustment_image_left"`
	AboutAdjustmentImageRight string         `json:"about_adjustment_image_right"`
	Email                     sql.NullString `json:"email"`
	Address                   sql.NullString `json:"address"`
	PhoneNo                   sql.NullString `json:"phone_no"`
	HasLoyalty                bool           `json:"has_loyalty"`
	OutletSelectText          sql.NullString `json:"outlet_select_text"`
	ShowLogo                  bool           `json:"show_logo"`
	ShowBrandName             bool           `json:"show_brand_name"`
	ShowMainScreenLogo        bool           `json:"show_main_screen_logo"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
}

type Customer struct {
	ID                            uint64         `json:"id"`
	Source                        sql.NullString `json:"source"`
	OrderID                       sql.NullInt64  `json:"order_id"`
	FirstOrderOfferEligible       bool           `json:"first_order_offer_eligible"`
	SubscribeToPromotionEmails    sql.NullBool   `json:"subscribe_to_promotion_emails"`
	PromotionEmailsSubscribedAt   sql.NullTime   `json:"promotion_emails_subscribed_at"`
	FirstName                     sql.NullString `json:"first_name"`
	HashedFirstName               sql.NullString `json:"hashed_first_name"`
	KeyIDFirstName                int32          `json:"key_id_first_name"`
	LastName                      sql.NullString `json:"last_name"`
	HashedLastName                sql.NullString `json:"hashed_last_name"`
	KeyIDLastName                 int32          `json:"key_id_last_name"`
	AccountBrand                  sql.NullInt32  `json:"account_brand"`
	Dob                           sql.NullString `json:"dob"`
	HashedDob                     sql.NullString `json:"hashed_dob"`
	KeyIDDob                      int32          `json:"key_id_dob"`
	Address1                      sql.NullString `json:"address_1"`
	HashedAddress1                sql.NullString `json:"hashed_address_1"`
	KeyIDAddress1                 int32          `json:"key_id_address_1"`
	Address2                      sql.NullString `json:"address_2"`
	HashedAddress2                sql.NullString `json:"hashed_address_2"`
	KeyIDAddress2                 int32          `json:"key_id_address_2"`
	Email                         sql.NullString `json:"email"`
	HashedEmail                   sql.NullString `json:"hashed_email"`
	KeyIDEmail                    int32          `json:"key_id_email"`
	Password                      sql.NullString `json:"password"`
	AppleID                       sql.NullString `json:"apple_id"`
	Phone                         sql.NullString `json:"phone"`
	HashedPhone                   sql.NullString `json:"hashed_phone"`
	KeyIDPhone                    int32          `json:"key_id_phone"`
	CountryCode                   sql.NullString `json:"country_code"`
	City                          sql.NullString `json:"city"`
	HashedCity                    sql.NullString `json:"hashed_city"`
	KeyIDCity                     int32          `json:"key_id_city"`
	State                         sql.NullString `json:"state"`
	HashedState                   sql.NullString `json:"hashed_state"`
	KeyIDState                    int32          `json:"key_id_state"`
	Postcode                      sql.NullString `json:"postcode"`
	HashedPostcode                sql.NullString `json:"hashed_postcode"`
	KeyIDPostcode                 int32          `json:"key_id_postcode"`
	Country                       sql.NullString `json:"country"`
	HashedCountry                 sql.NullString `json:"hashed_country"`
	KeyIDCountry                  int32          `json:"key_id_country"`
	RemoteID                      sql.NullString `json:"remote_id"`
	Type                          sql.NullString `json:"type"`
	CreatedAt                     sql.NullTime   `json:"created_at"`
	UpdatedAt                     sql.NullTime   `json:"updated_at"`
	Latitude                      sql.NullString `json:"latitude"`
	HashedLatitude                sql.NullString `json:"hashed_latitude"`
	KeyIDLatitude                 int32          `json:"key_id_latitude"`
	Longitude                     sql.NullString `json:"longitude"`
	HashedLongitude               sql.NullString `json:"hashed_longitude"`
	KeyIDLongitude                int32          `json:"key_id_longitude"`
	ResetToken                    sql.NullString `json:"reset_token"`
	RememberToken                 sql.NullString `json:"remember_token"`
	StripeID                      sql.NullString `json:"stripe_id"`
	ContactAccessCode             sql.NullString `json:"contact_access_code"`
	Otp                           sql.NullString `json:"otp"`
	Status                        bool           `json:"status"`
	PasswordResetCode             sql.NullString `json:"password_reset_code"`
	PasswordResetCodeStatus       bool           `json:"password_reset_code_status"`
	AddressType                   string         `json:"address_type"`
	Notes                         sql.NullString `json:"notes"`
	ExpoToken                     sql.NullString `json:"expo_token"`
	NotificationPermissionGivenAt sql.NullTime   `json:"notification_permission_given_at"`
	DeviceID                      sql.NullString `json:"device_id"`
	DevicePlatform                sql.NullString `json:"device_platform"`
	LastActiveTime                sql.NullTime   `json:"last_active_time"`
	LastActiveDevice              sql.NullString `json:"last_active_device"`
	DeletedAt                     sql.NullTime   `json:"deleted_at"`
	IsReal                        bool           `json:"is_real"`
}

type CustomerVoucher struct {
	ID         uint64       `json:"id"`
	CustomerID uint32       `json:"customer_id"`
	VoucherID  uint32       `json:"voucher_id"`
	IsUsed     bool         `json:"is_used"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type DeliveryLocation struct {
	ID             uint64         `json:"id"`
	CustomerID     int32          `json:"customer_id"`
	Label          sql.NullString `json:"label"`
	FlatNo         sql.NullString `json:"flat_no"`
	HouseNo        sql.NullString `json:"house_no"`
	AddressLine1   string         `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	City           sql.NullString `json:"city"`
	Landmark       sql.NullString `json:"landmark"`
	PostalCode     sql.NullString `json:"postal_code"`
	DefaultAddress bool           `json:"default_address"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type DeliveryPlatform struct {
	ID                 uint64         `json:"id"`
	PlatformID         sql.NullInt32  `json:"platform_id"`
	Name               string         `json:"name"`
	WebshopBrandID     sql.NullInt32  `json:"webshop_brand_id"`
	ApiUrl             sql.NullString `json:"api_url"`
	AuthUrl            sql.NullString `json:"auth_url"`
	ApiParameters      sql.NullString `json:"api_parameters"`
	Logo               sql.NullString `json:"logo"`
	Status             string         `json:"status"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	OutletCode         sql.NullString `json:"outlet_code"`
	SiteID             sql.NullString `json:"site_id"`
	BranchID           sql.NullString `json:"branch_id"`
	AccessToken        sql.NullString `json:"access_token"`
	PrimaryColor       sql.NullString `json:"primary_color"`
	CanUpload          bool           `json:"can_upload"`
	AutoAccepting      bool           `json:"auto_accepting"`
	FranchiseID        int32          `json:"franchise_id"`
	OutletID           sql.NullInt64  `json:"outlet_id"`
	MenuID             sql.NullString `json:"menu_id"`
	MenuUploadStatus   sql.NullString `json:"menu_upload_status"`
	StoreStatus        sql.NullString `json:"store_status"`
	AvailableFrom      sql.NullTime   `json:"available_from"`
	TenderTypes        sql.NullString `json:"tender_types"`
	IsMaster           bool           `json:"is_master"`
	ParentPlatform     sql.NullInt32  `json:"parent_platform"`
	PrepTime           sql.NullInt32  `json:"prep_time"`
	OwnDriver          bool           `json:"own_driver"`
	MenuPublishedAt    sql.NullTime   `json:"menu_published_at"`
	WebshopSetupStatus bool           `json:"webshop_setup_status"`
	HasCashPayment     bool           `json:"has_cash_payment"`
	HasCardPayment     bool           `json:"has_card_payment"`
	SelectedMenu       sql.NullInt32  `json:"selected_menu"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type DgPosCashDrawer struct {
	ID        uint64       `json:"id"`
	OutletID  uint64       `json:"outlet_id"`
	IsActive  bool         `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type DgPosCashDrawerExpectedBalance struct {
	CashDrawerSessionID uint64 `json:"cash_drawer_session_id"`
	TotalInAmount       int32  `json:"total_in_amount"`
	TotalOutAmount      int32  `json:"total_out_amount"`
	TotalSalesAmount    int32  `json:"total_sales_amount"`
	TotalRefundAmount   int32  `json:"total_refund_amount"`
	TotalMovements      int32  `json:"total_movements"`
	ExpectedBalance     int32  `json:"expected_balance"`
	Difference          int32  `json:"difference"`
}

type DgPosCashDrawerSession struct {
	ID                     uint64        `json:"id"`
	CashDrawerID           uint64        `json:"cash_drawer_id"`
	SessionStartedUserID   uint64        `json:"session_started_user_id"`
	SessionEndedUserID     sql.NullInt64 `json:"session_ended_user_id"`
	OpenedAt               time.Time     `json:"opened_at"`
	OpeningBalance         int32         `json:"opening_balance"`
	ClosedAt               sql.NullTime  `json:"closed_at"`
	ClosingBalanceCounted  sql.NullInt32 `json:"closing_balance_counted"`
	ClosingBalanceExpected sql.NullInt32 `json:"closing_balance_expected"`
	Difference             sql.NullInt32 `json:"difference"`
	TotalInAmount          sql.NullInt32 `json:"total_in_amount"`
	TotalOutAmount         sql.NullInt32 `json:"total_out_amount"`
	TotalSalesAmount       sql.NullInt32 `json:"total_sales_amount"`
	TotalOtherSalesAmount  sql.NullInt32 `json:"total_other_sales_amount"`
	TotalRefundAmount      sql.NullInt32 `json:"total_refund_amount"`
	Status                 string        `json:"status"`
	CreatedAt              sql.NullTime  `json:"created_at"`
	UpdatedAt              sql.NullTime  `json:"updated_at"`
}

type DgPosCashMovement struct {
	ID                  uint64         `json:"id"`
	CashDrawerSessionID uint64         `json:"cash_drawer_session_id"`
	MovementType        string         `json:"movement_type"`
	Amount              int32          `json:"amount"`
	Note                sql.NullString `json:"note"`
	UserID              uint64         `json:"user_id"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type DgPosOrderLocation struct {
	ID           uint64         `json:"id"`
	OrderID      int32          `json:"order_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	CountryCode  string         `json:"country_code"`
	Country      sql.NullString `json:"country"`
	Phone        string         `json:"phone"`
	FlatNo       sql.NullString `json:"flat_no"`
	HouseNo      sql.NullString `json:"house_no"`
	AddressLine1 string         `json:"address_line_1"`
	AddressLine2 sql.NullString `json:"address_line_2"`
	City         sql.NullString `json:"city"`
	Landmark     sql.NullString `json:"landmark"`
	Postcode     sql.NullString `json:"postcode"`
	Latitude     sql.NullString `json:"latitude"`
	Longitude    sql.NullString `json:"longitude"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type DgPosOrderStatusTimestamp struct {
	ID        uint64       `json:"id"`
	OrderID   int32        `json:"order_id"`
	Queue     sql.NullTime `json:"queue"`
	Preparing sql.NullTime `json:"preparing"`
	Ready     sql.NullTime `json:"ready"`
	Served    sql.NullTime `json:"served"`
	Delivered sql.NullTime `json:"delivered"`
	Completed sql.NullTime `json:"completed"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type DgPosPayment struct {
	ID                   uint64         `json:"id"`
	OrderID              int32          `json:"order_id"`
	DateTime             sql.NullTime   `json:"date_time"`
	Amount               string         `json:"amount"`
	Cash                 string         `json:"cash"`
	Balance              string         `json:"balance"`
	CardTransactionToken sql.NullString `json:"card_transaction_token"`
	TransactionID        sql.NullInt64  `json:"transaction_id"`
	RefundID             sql.NullString `json:"refund_id"`
	PaymentMethodID      sql.NullString `json:"payment_method_id"`
	PaymentType          sql.NullString `json:"payment_type"`
	Status               sql.NullString `json:"status"`
	IsRefund             bool           `json:"is_refund"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type DgPosShopConfig struct {
	ID         uint64          `json:"id"`
	ShopID     int32           `json:"shop_id"`
	BrandID    int32           `json:"brand_id"`
	TerminalID int32           `json:"terminal_id"`
	ConfigType string          `json:"config_type"`
	Data       json.RawMessage `json:"data"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
}

type DgPosTable struct {
	ID               uint64         `json:"id"`
	TableOrderingsID sql.NullInt64  `json:"table_orderings_id"`
	ShopID           int32          `json:"shop_id"`
	BrandID          int32          `json:"brand_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	SeatCount        int32          `json:"seat_count"`
	Status           string         `json:"status"`
	OngoingOrderID   sql.NullInt64  `json:"ongoing_order_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type DgPosTablesOngoingOrder struct {
	ID        uint64       `json:"id"`
	TableID   uint64       `json:"table_id"`
	OrderID   uint64       `json:"order_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type DgPosTmpPayment struct {
	ID            uint64         `json:"id"`
	TypeID        string         `json:"type_id"`
	Type          string         `json:"type"`
	PaymentAmount int32          `json:"payment_amount"`
	PaymentMode   string         `json:"payment_mode"`
	TransactionID sql.NullString `json:"transaction_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type DgPosUserActivity struct {
	ID          uint64         `json:"id"`
	BrandID     sql.NullInt64  `json:"brand_id"`
	ShopID      sql.NullInt64  `json:"shop_id"`
	LogName     string         `json:"log_name"`
	Description sql.NullString `json:"description"`
	Event       string         `json:"event"`
	SubjectID   int64          `json:"subject_id"`
	CauserID    int64          `json:"causer_id"`
}

type DgPosUserShift struct {
	ID        uint64       `json:"id"`
	UserID    int64        `json:"user_id"`
	Login     time.Time    `json:"login"`
	Logout    sql.NullTime `json:"logout"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type EncryptionKey struct {
	ID        uint64       `json:"id"`
	Key       string       `json:"key"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type EntityDeliveryPlatform struct {
	ID                 uint64         `json:"id"`
	EntityID           sql.NullInt32  `json:"entity_id"`
	DeliveryPlatformID int32          `json:"delivery_platform_id"`
	ExternalItemID     string         `json:"external_item_id"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	Plu                sql.NullString `json:"plu"`
	Price              sql.NullString `json:"price"`
	ItemName           sql.NullString `json:"item_name"`
	Allergies          sql.NullString `json:"allergies"`
	Available          bool           `json:"available"`
	AvailableFrom      sql.NullTime   `json:"available_from"`
}

type MainMenuMenu struct {
	ID         uint64       `json:"id"`
	MainMenuID int32        `json:"main_menu_id"`
	MenuID     int32        `json:"menu_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type Order struct {
	ID                        uint64         `json:"id"`
	ShopID                    int32          `json:"shop_id"`
	PlatformID                int32          `json:"platform_id"`
	RemoteOrderID             string         `json:"remote_order_id"`
	DisplayOrderID            sql.NullString `json:"display_order_id"`
	DeliveryDateTime          time.Time      `json:"delivery_date_time"`
	TotalAmount               int32          `json:"total_amount"`
	SubTotal                  sql.NullInt32  `json:"sub_total"`
	TotalFee                  sql.NullInt32  `json:"total_fee"`
	CampaignCode              sql.NullString `json:"campaign_code"`
	Discount                  int32          `json:"discount"`
	VoucherDiscount           int32          `json:"voucher_discount"`
	DiscountModeApplied       sql.NullString `json:"discount_mode_applied"`
	DiscountPercentageApplied sql.NullInt32  `json:"discount_percentage_applied"`
	DiscountType              sql.NullString `json:"discount_type"`
	Vouchers                  sql.NullString `json:"vouchers"`
	Status                    string         `json:"status"`
	CancelledReason           sql.NullString `json:"cancelled_reason"`
	OrderTypeID               sql.NullInt32  `json:"order_type_id"`
	Note                      sql.NullString `json:"note"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
	CustomerName              sql.NullString `json:"customer_name"`
	UserID                    sql.NullInt32  `json:"user_id"`
	CustomerID                sql.NullInt32  `json:"customer_id"`
	DeliveryLocationID        sql.NullInt32  `json:"delivery_location_id"`
	DeliveryTax               sql.NullInt32  `json:"delivery_tax"`
	TaxID                     sql.NullInt32  `json:"tax_id"`
	ShippingMethod            sql.NullString `json:"shipping_method"`
	ShippingTotal             sql.NullString `json:"shipping_total"`
	ShippingTax               sql.NullString `json:"shipping_tax"`
	TotalTax                  sql.NullString `json:"total_tax"`
	CashDue                   string         `json:"cash_due"`
	Surcharge                 string         `json:"surcharge"`
	ContactAccessCode         sql.NullString `json:"contact_access_code"`
	TestingOrder              bool           `json:"testing_order"`
	CancelledByCustomer       bool           `json:"cancelled_by_customer"`
	PaymentMethod             sql.NullString `json:"payment_method"`
	PaymentMode               sql.NullString `json:"payment_mode"`
	IsScheduled               bool           `json:"is_scheduled"`
	IsTableOrder              bool           `json:"is_table_order"`
	Tip                       string         `json:"tip"`
	TipPercentage             string         `json:"tip_percentage"`
	TableID                   sql.NullString `json:"table_id"`
	DgposTableID              sql.NullInt32  `json:"dgpos_table_id"`
	TableOrderMethodID        sql.NullInt32  `json:"table_order_method_id"`
	DevicePlatform            sql.NullString `json:"device_platform"`
	OrderDelayed              bool           `json:"order_delayed"`
	UniqueOrderID             sql.NullString `json:"unique_order_id"`
	OrderSessionID            sql.NullInt32  `json:"order_session_id"`
}

type OrderCommission struct {
	ID         uint64         `json:"id"`
	OrderTmpID sql.NullInt64  `json:"order_tmp_id"`
	OrderID    int64          `json:"order_id"`
	Commission string         `json:"commission"`
	Reference  sql.NullString `json:"reference"`
	ReportID   sql.NullInt32  `json:"report_id"`
	Status     string         `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID             uint64         `json:"id"`
	OrderID        int32          `json:"order_id"`
	ItemID         string         `json:"item_id"`
	Quantity       float64        `json:"quantity"`
	PricePerItem   int32          `json:"price_per_item"`
	Total          int32          `json:"total"`
	OriginalPrice  int32          `json:"original_price"`
	IsSale         bool           `json:"is_sale"`
	DiscountAmount int32          `json:"discount_amount"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ItemName       string         `json:"item_name"`
	CategoryName   sql.NullString `json:"category_name"`
	Modifiers      sql.NullString `json:"modifiers"`
	Tax            int32          `json:"tax"`
	Note           sql.NullString `json:"note"`
}

type OrderItemModifier struct {
	ID                  uint64         `json:"id"`
	OrderItemID         int32          `json:"order_item_id"`
	ParentModifierID    sql.NullString `json:"parent_modifier_id"`
	SubParentModifierID sql.NullString `json:"sub_parent_modifier_id"`
	ModifierID          string         `json:"modifier_id"`
	ModifierGroupName   string         `json:"modifier_group_name"`
	ModifierOptionID    string         `json:"modifier_option_id"`
	ModifierOptionName  string         `json:"modifier_option_name"`
	Amount              string         `json:"amount"`
	Quantity            string         `json:"quantity"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type OrderItemTax struct {
	ID                  uint64        `json:"id"`
	OrderID             int32         `json:"order_id"`
	OrderItemID         int32         `json:"order_item_id"`
	OrderItemModifierID sql.NullInt32 `json:"order_item_modifier_id"`
	ItemPrice           int32         `json:"item_price"`
	TaxID               int32         `json:"tax_id"`
	TaxProfileID        int32         `json:"tax_profile_id"`
	TaxRuleID           int32         `json:"tax_rule_id"`
	Amount              int32         `json:"amount"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	UpdatedAt           sql.NullTime  `json:"updated_at"`
}

type OrderRefund struct {
	ID            uint64         `json:"id"`
	TypeID        uint64         `json:"type_id"`
	Type          string         `json:"type"`
	TransactionID uint64         `json:"transaction_id"`
	RefundAmount  int32          `json:"refund_amount"`
	RefundMode    string         `json:"refund_mode"`
	Reason        sql.NullString `json:"reason"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type OrderSession struct {
	ID                   uint64         `json:"id"`
	ShopID               int32          `json:"shop_id"`
	PlatformID           int32          `json:"platform_id"`
	TotalAmount          int32          `json:"total_amount"`
	SubTotal             sql.NullInt32  `json:"sub_total"`
	TotalFee             sql.NullInt32  `json:"total_fee"`
	TotalCommission      string         `json:"total_commission"`
	Discount             int32          `json:"discount"`
	OrderStatus          string         `json:"order_status"`
	SessionStatus        string         `json:"session_status"`
	SessionStartDatetime sql.NullTime   `json:"session_start_datetime"`
	SessionEndDatetime   sql.NullTime   `json:"session_end_datetime"`
	CustomerName         sql.NullString `json:"customer_name"`
	CustomerID           sql.NullInt32  `json:"customer_id"`
	ShippingTotal        sql.NullString `json:"shipping_total"`
	TotalTax             sql.NullString `json:"total_tax"`
	PaymentMethod        sql.NullString `json:"payment_method"`
	PaymentMode          sql.NullString `json:"payment_mode"`
	IsTableOrder         bool           `json:"is_table_order"`
	TableID              sql.NullString `json:"table_id"`
	TableOrderMethodID   sql.NullInt32  `json:"table_order_method_id"`
	PaymentID            sql.NullString `json:"payment_id"`
	Uid                  sql.NullString `json:"uid"`
	PaymentType          sql.NullString `json:"payment_type"`
	PaymentStatus        sql.NullString `json:"payment_status"`
	BillType             sql.NullString `json:"bill_type"`
	OrderCount           int32          `json:"order_count"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type OrderShopFee struct {
	ID         uint64        `json:"id"`
	OrderID    int32         `json:"order_id"`
	ShopFeeID  int32         `json:"shop_fee_id"`
	Amount     int32         `json:"amount"`
	ShopFeeTax sql.NullInt32 `json:"shop_fee_tax"`
	TaxID      sql.NullInt32 `json:"tax_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type OrderTax struct {
	ID            uint64       `json:"id"`
	OrderID       int32        `json:"order_id"`
	TaxRate       string       `json:"tax_rate"`
	TaxCode       string       `json:"tax_code"`
	TaxAmount     int32        `json:"tax_amount"`
	TaxableAmount int32        `json:"taxable_amount"`
	Type          string       `json:"type"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type OrderTransaction struct {
	ID                uint64         `json:"id"`
	TypeID            uint64         `json:"type_id"`
	Type              string         `json:"type"`
	TransactionType   string         `json:"transaction_type"`
	TransactionAmount int32          `json:"transaction_amount"`
	TransactionMode   sql.NullString `json:"transaction_mode"`
	PaymentType       sql.NullString `json:"payment_type"`
	Platform          sql.NullString `json:"platform"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	ID              uint64         `json:"id"`
	OrderID         int32          `json:"order_id"`
	DateTime        sql.NullTime   `json:"date_time"`
	Amount          string         `json:"amount"`
	Tax             string         `json:"tax"`
	Discount        string         `json:"discount"`
	TransactionID   sql.NullString `json:"transaction_id"`
	PaymentMethodID sql.NullString `json:"payment_method_id"`
	Status          sql.NullString `json:"status"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Platform struct {
	ID         uint64         `json:"id"`
	Name       sql.NullString `json:"name"`
	Type       string         `json:"type"`
	Logo       sql.NullString `json:"logo"`
	Parameters sql.NullString `json:"parameters"`
	Status     bool           `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type PosRefreshToken struct {
	UserID    uint64       `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type PrinterGroup struct {
	ID          uint64         `json:"id"`
	BrandID     int32          `json:"brand_id"`
	ShopID      int32          `json:"shop_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      bool           `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type PrinterGroupItem struct {
	ID             uint64       `json:"id"`
	PrinterGroupID int32        `json:"printer_group_id"`
	ItemID         int32        `json:"item_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type ReportService struct {
	ID                 uint64         `json:"id"`
	Dns                sql.NullString `json:"dns"`
	ServerClientID     sql.NullString `json:"server_client_id"`
	ServerClientSecret sql.NullString `json:"server_client_secret"`
	BearerToken        sql.NullString `json:"bearer_token"`
	ExpireIn           sql.NullTime   `json:"expire_in"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Role struct {
	ID          uint32       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Shop struct {
	ID                           uint64         `json:"id"`
	Name                         string         `json:"name"`
	FranchiseID                  int32          `json:"franchise_id"`
	Code                         string         `json:"code"`
	Email                        sql.NullString `json:"email"`
	Address                      sql.NullString `json:"address"`
	Branch                       sql.NullString `json:"branch"`
	ContactNo                    sql.NullString `json:"contact_no"`
	BusinessRegNo                sql.NullString `json:"business_reg_no"`
	SocketCode                   sql.NullString `json:"socket_code"`
	Status                       string         `json:"status"`
	OrderStatus                  string         `json:"order_status"`
	LastUpdatedMenu              sql.NullInt32  `json:"last_updated_menu"`
	LastPosSynced                sql.NullTime   `json:"last_pos_synced"`
	ServiceAvailability          sql.NullString `json:"service_availability"`
	CreatedAt                    sql.NullTime   `json:"created_at"`
	UpdatedAt                    sql.NullTime   `json:"updated_at"`
	MinimumAmountForFreeDelivery sql.NullString `json:"minimum_amount_for_free_delivery"`
	MinimumAmountForDelivery     sql.NullString `json:"minimum_amount_for_delivery"`
	OneTimePromotionValue        sql.NullString `json:"one_time_promotion_value"`
	OneTimePromotionSpendAmount  sql.NullString `json:"one_time_promotion_spend_amount"`
	Latitude                     sql.NullString `json:"latitude"`
	Longitude                    sql.NullString `json:"longitude"`
	GoogleLocationUrl            sql.NullString `json:"google_location_url"`
	OneTimePromotionType         sql.NullString `json:"one_time_promotion_type"`
	MaximumPromotionValue        string         `json:"maximum_promotion_value"`
	SelectedMenu                 sql.NullInt32  `json:"selected_menu"`
	IsDefault                    bool           `json:"is_default"`
	CountryCode                  sql.NullString `json:"country_code"`
	Timezone                     string         `json:"timezone"`
	Currency                     string         `json:"currency"`
	CurrencyCode                 string         `json:"currency_code"`
	TaxMode                      ShopTaxMode    `json:"tax_mode"`
	TaxRegNo                     sql.NullString `json:"tax_reg_no"`
	PrintReceiptAccept           bool           `json:"print_receipt_accept"`
	NumberOfReceipt              int32          `json:"number_of_receipt"`
	DeliveryPlatformEnable       bool           `json:"delivery_platform_enable"`
	RunTestOrder                 bool           `json:"run_test_order"`
	HasCashPayment               bool           `json:"has_cash_payment"`
	HasCardPayment               bool           `json:"has_card_payment"`
	TblCommissionPerHead         string         `json:"tbl_commission_per_head"`
	TblRefCommissionPerHead      string         `json:"tbl_ref_commission_per_head"`
	TransferDestination          sql.NullString `json:"transfer_destination"`
	DelivergateAccount           bool           `json:"delivergate_account"`
	PrinterStatus                bool           `json:"printer_status"`
	DeletedAt                    sql.NullTime   `json:"deleted_at"`
	HasCollectionPoints          bool           `json:"has_collection_points"`
	CollectionPointsNote         sql.NullString `json:"collection_points_note"`
	UserInteractionStatus        bool           `json:"user_interaction_status"`
	InteractionTimeout           sql.NullInt32  `json:"interaction_timeout"`
}

type ShopBrandDetail struct {
	ID                            uint64         `json:"id"`
	ShopID                        uint32         `json:"shop_id"`
	WebshopBrandID                uint32         `json:"webshop_brand_id"`
	OrderCommission               string         `json:"order_commission"`
	DelivergateAccount            bool           `json:"delivergate_account"`
	TransferDestination           sql.NullString `json:"transfer_destination"`
	GooglePlaceID                 sql.NullString `json:"google_place_id"`
	StreetNo                      sql.NullString `json:"street_no"`
	Route                         sql.NullString `json:"route"`
	Locality                      sql.NullString `json:"locality"`
	AdministrativeAreaLevel1      sql.NullString `json:"administrative_area_level_1"`
	AdministrativeAreaLevel1Short sql.NullString `json:"administrative_area_level_1_short"`
	AdministrativeAreaLevel2      sql.NullString `json:"administrative_area_level_2"`
	AdministrativeAreaLevel2Short sql.NullString `json:"administrative_area_level_2_short"`
	Country                       sql.NullString `json:"country"`
	CountryShort                  sql.NullString `json:"country_short"`
	PostalCode                    sql.NullString `json:"postal_code"`
	FormattedAddress              sql.NullString `json:"formatted_address"`
	FormattedPhoneNumber          sql.NullString `json:"formatted_phone_number"`
	Note                          sql.NullString `json:"note"`
	RateCount                     int32          `json:"rate_count"`
	RateAverage                   string         `json:"rate_average"`
	ShowNote                      bool           `json:"show_note"`
	ContactNumber                 sql.NullString `json:"contact_number"`
	Email                         sql.NullString `json:"email"`
	CreatedAt                     sql.NullTime   `json:"created_at"`
	UpdatedAt                     sql.NullTime   `json:"updated_at"`
}

type ShopFee struct {
	ID             uint64         `json:"id"`
	ShopID         int32          `json:"shop_id"`
	WebshopBrandID uint32         `json:"webshop_brand_id"`
	Platform       sql.NullString `json:"platform"`
	Type           sql.NullString `json:"type"`
	FeeName        string         `json:"fee_name"`
	Fee            string         `json:"fee"`
	FeeType        string         `json:"fee_type"`
	Status         bool           `json:"status"`
	TaxID          sql.NullInt32  `json:"tax_id"`
	Mandatory      bool           `json:"mandatory"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type TableOrderMethod struct {
	ID               uint64         `json:"id"`
	ShopID           uint32         `json:"shop_id"`
	BrandID          uint32         `json:"brand_id"`
	Name             string         `json:"name"`
	LocalizationName sql.NullString `json:"localization_name"`
	Description      sql.NullString `json:"description"`
	Status           bool           `json:"status"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type TableOrdering struct {
	ID          uint64         `json:"id"`
	ShopID      int32          `json:"shop_id"`
	BrandID     int32          `json:"brand_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type TableReservation struct {
	ID                uint64         `json:"id"`
	ReservationCode   string         `json:"reservation_code"`
	Source            string         `json:"source"`
	DisplayCode       sql.NullString `json:"display_code"`
	ShopID            int32          `json:"shop_id"`
	BrandID           sql.NullInt32  `json:"brand_id"`
	ReservationTypeID sql.NullInt32  `json:"reservation_type_id"`
	TableID           sql.NullInt32  `json:"table_id"`
	UserID            sql.NullInt32  `json:"user_id"`
	UserType          sql.NullString `json:"user_type"`
	CustomerID        sql.NullInt32  `json:"customer_id"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	Email             sql.NullString `json:"email"`
	CountryCode       sql.NullString `json:"country_code"`
	MobileNumber      sql.NullString `json:"mobile_number"`
	Note              sql.NullString `json:"note"`
	OfferValue        sql.NullString `json:"offer_value"`
	PartySize         int32          `json:"party_size"`
	Adults            int32          `json:"adults"`
	Kids              int32          `json:"kids"`
	StartDate         time.Time      `json:"start_date"`
	StartTime         time.Time      `json:"start_time"`
	StartDatetime     time.Time      `json:"start_datetime"`
	EndDate           time.Time      `json:"end_date"`
	EndTime           time.Time      `json:"end_time"`
	EndDatetime       time.Time      `json:"end_datetime"`
	Duration          string         `json:"duration"`
	Referrer          sql.NullString `json:"referrer"`
	Commission        string         `json:"commission"`
	ReservationFee    string         `json:"reservation_fee"`
	IsRefundable      bool           `json:"is_refundable"`
	TransactionID     sql.NullString `json:"transaction_id"`
	Status            string         `json:"status"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	ZoneID            sql.NullInt32  `json:"zone_id"`
	DevicePlatform    sql.NullString `json:"device_platform"`
	Occation          sql.NullString `json:"occation"`
}

type TaxProfile struct {
	ID          uint64         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      bool           `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type TaxRule struct {
	ID           uint64       `json:"id"`
	TaxProfileID int32        `json:"tax_profile_id"`
	TaxID        int32        `json:"tax_id"`
	Name         string       `json:"name"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type TaxRuleCondition struct {
	ID             uint64         `json:"id"`
	TaxRuleID      int32          `json:"tax_rule_id"`
	ConditionType  string         `json:"condition_type"`
	ConditionValue sql.NullString `json:"condition_value"`
	MinValue       sql.NullString `json:"min_value"`
	MaxValue       sql.NullString `json:"max_value"`
	StartDate      sql.NullTime   `json:"start_date"`
	EndDate        sql.NullTime   `json:"end_date"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type TaxesMain struct {
	ID          uint64         `json:"id"`
	Name        sql.NullString `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	Rate        sql.NullString `json:"rate"`
	Status      bool           `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Tenant struct {
	ID                  uint64       `json:"id"`
	Host                string       `json:"host"`
	Port                string       `json:"port"`
	DatabaseName        string       `json:"database_name"`
	XTenantCode         string       `json:"x_tenant_code"`
	Username            string       `json:"username"`
	Password            string       `json:"password"`
	ServerClientID      int32        `json:"server_client_id"`
	ServerClientSecret  string       `json:"server_client_secret"`
	SiteName            string       `json:"site_name"`
	PrdDomain           string       `json:"prd_domain"`
	CreatedAt           sql.NullTime `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
	HasWebshop          bool         `json:"has_webshop"`
	EnableDusk          bool         `json:"enable_dusk"`
	DuskPort            string       `json:"dusk_port"`
	SyncStatus          bool         `json:"sync_status"`
	SyncWebshopStatus   bool         `json:"sync_webshop_status"`
	HasMultishop        bool         `json:"has_multishop"`
	SendReports         bool         `json:"send_reports"`
	RetryAuthentication bool         `json:"retry_authentication"`
	EnableEncryption    bool         `json:"enable_encryption"`
	EnablePos           bool         `json:"enable_pos"`
}

type User struct {
	ID                uint64         `json:"id"`
	Name              string         `json:"name"`
	HashedName        sql.NullString `json:"hashed_name"`
	KeyIDName         int32          `json:"key_id_name"`
	LastName          sql.NullString `json:"last_name"`
	HashedLastName    sql.NullString `json:"hashed_last_name"`
	KeyIDLastName     int32          `json:"key_id_last_name"`
	Email             string         `json:"email"`
	HashedEmail       sql.NullString `json:"hashed_email"`
	KeyIDEmail        int32          `json:"key_id_email"`
	Address           sql.NullString `json:"address"`
	HashedAddress     sql.NullString `json:"hashed_address"`
	KeyIDAddress      int32          `json:"key_id_address"`
	ContactNo         sql.NullString `json:"contact_no"`
	HashedContactNo   sql.NullString `json:"hashed_contact_no"`
	KeyIDContactNo    int32          `json:"key_id_contact_no"`
	EmailVerifiedAt   sql.NullTime   `json:"email_verified_at"`
	Password          string         `json:"password"`
	Pin               sql.NullString `json:"pin"`
	Status            sql.NullString `json:"status"`
	RememberToken     sql.NullString `json:"remember_token"`
	ExpoToken         sql.NullString `json:"expo_token"`
	DeviceID          sql.NullString `json:"device_id"`
	OrderAppExpoToken sql.NullString `json:"order_app_expo_token"`
	OrderAppDeviceID  sql.NullString `json:"order_app_device_id"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	ID        uint32       `json:"id"`
	UserID    uint32       `json:"user_id"`
	RoleID    uint32       `json:"role_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type UserShop struct {
	ID        uint64       `json:"id"`
	UserID    uint32       `json:"user_id"`
	ShopID    uint32       `json:"shop_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Voucher struct {
	ID             uint64         `json:"id"`
	CampaignCode   sql.NullString `json:"campaign_code"`
	VoucherType    string         `json:"voucher_type"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	VoucherCode    string         `json:"voucher_code"`
	ExpireyDate    time.Time      `json:"expirey_date"`
	StartDate      time.Time      `json:"start_date"`
	Value          string         `json:"value"`
	ValueType      string         `json:"value_type"`
	CurrentUsage   int32          `json:"current_usage"`
	Status         string         `json:"status"`
	WebshopBrandID uint32         `json:"webshop_brand_id"`
}

type WebshopBrand struct {
	ID                    uint32        `json:"id"`
	BrandName             string        `json:"brand_name"`
	BrandCode             string        `json:"brand_code"`
	Domain                string        `json:"domain"`
	Status                bool          `json:"status"`
	SetupStatus           bool          `json:"setup_status"`
	HasMultishop          bool          `json:"has_multishop"`
	DefaultShop           sql.NullInt32 `json:"default_shop"`
	CreatedAt             sql.NullTime  `json:"created_at"`
	UpdatedAt             sql.NullTime  `json:"updated_at"`
	LoyaltyPointsPerPound string        `json:"loyalty_points_per_pound"`
	PoundsPerPoint        string        `json:"pounds_per_point"`
	LoyaltyExpireDate     sql.NullTime  `json:"loyalty_expire_date"`
}

type WebshopMenu struct {
	ID                 uint64         `json:"id"`
	MainMenuID         int32          `json:"main_menu_id"`
	SubmenuID          sql.NullInt32  `json:"submenu_id"`
	PlatformID         sql.NullInt32  `json:"platform_id"`
	DeliveryPlatformID int32          `json:"delivery_platform_id"`
	Status             sql.NullInt32  `json:"status"`
	OutletID           int32          `json:"outlet_id"`
	Day                sql.NullString `json:"day"`
	From               sql.NullString `json:"from"`
	To                 sql.NullString `json:"to"`
	Menu               sql.NullString `json:"menu"`
	CategoryIds        sql.NullString `json:"category_ids"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type WebshopOrderLocation struct {
	ID           uint64         `json:"id"`
	OrderTmpID   sql.NullInt64  `json:"order_tmp_id"`
	OrderID      sql.NullInt64  `json:"order_id"`
	Type         string         `json:"type"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	CountryCode  sql.NullString `json:"country_code"`
	AddressLine1 sql.NullString `json:"address_line_1"`
	AddressLine2 sql.NullString `json:"address_line_2"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	Postcode     sql.NullString `json:"postcode"`
	Country      sql.NullString `json:"country"`
	Latitude     sql.NullString `json:"latitude"`
	Longitude    sql.NullString `json:"longitude"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type WebshopPayment struct {
	ID                    uint32         `json:"id"`
	OrderTmpID            sql.NullInt32  `json:"order_tmp_id"`
	OrderID               sql.NullInt32  `json:"order_id"`
	PaymentAmount         sql.NullInt32  `json:"payment_amount"`
	StripeFee             int32          `json:"stripe_fee"`
	HasTransferred        bool           `json:"has_transferred"`
	TransferredAmount     int32          `json:"transferred_amount"`
	NetAmount             int32          `json:"net_amount"`
	PaymentID             sql.NullString `json:"payment_id"`
	Uid                   sql.NullString `json:"uid"`
	IsRefund              bool           `json:"is_refund"`
	InitiateRefundProcess bool           `json:"initiate_refund_process"`
	PayoutCreated         bool           `json:"payout_created"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	PaymentType           sql.NullString `json:"payment_type"`
	PaymentStatus         sql.NullString `json:"payment_status"`
}
