// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_transaction.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderTransaction = `-- name: CreateOrderTransaction :execlastid
INSERT INTO
    order_transaction (
        type_id,
        ` + "`" + `type` + "`" + `,
        transaction_type,
        transaction_mode,
        transaction_amount,
        payment_type,
        platform,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        "DG_POS",
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateOrderTransactionParams struct {
	TypeID            uint64         `json:"type_id"`
	Type              string         `json:"type"`
	TransactionType   string         `json:"transaction_type"`
	TransactionMode   sql.NullString `json:"transaction_mode"`
	TransactionAmount int32          `json:"transaction_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
}

// CreateOrderTransaction
//
//	INSERT INTO
//	    order_transaction (
//	        type_id,
//	        `type`,
//	        transaction_type,
//	        transaction_mode,
//	        transaction_amount,
//	        payment_type,
//	        platform,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        "DG_POS",
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateOrderTransaction(ctx context.Context, arg *CreateOrderTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrderTransaction,
		arg.TypeID,
		arg.Type,
		arg.TransactionType,
		arg.TransactionMode,
		arg.TransactionAmount,
		arg.PaymentType,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCashTransactionsByOrderID = `-- name: GetCashTransactionsByOrderID :many
SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
FROM order_transaction
WHERE
    type_id = ?
    AND transaction_mode = 'CASH'
`

// GetCashTransactionsByOrderID
//
//	SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
//	FROM order_transaction
//	WHERE
//	    type_id = ?
//	    AND transaction_mode = 'CASH'
func (q *Queries) GetCashTransactionsByOrderID(ctx context.Context, typeID uint64) ([]*OrderTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getCashTransactionsByOrderID, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrderTransaction{}
	for rows.Next() {
		var i OrderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Type,
			&i.TransactionType,
			&i.TransactionAmount,
			&i.TransactionMode,
			&i.PaymentType,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetCashAndCardSaleByOrderID = `-- name: GetNetCashAndCardSaleByOrderID :one
SELECT 
    0 + SUM(
        CASE
            WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
            WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
            ELSE 0
        END
    ) AS net_sales
FROM
    order_transaction ot
WHERE
    ot.type_id = ?
    AND ot.` + "`" + `type` + "`" + ` = 'ORDER'
GROUP BY
    ot.type_id
`

//	0 + SUM(
//	      CASE
//	          WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
//	              WHEN ot.transaction_type = 'SALE' THEN 1
//	              WHEN ot.transaction_type = 'REFUND' THEN -1
//	              ELSE 0
//	          END
//	          ELSE 0
//	      END
//	  ) AS net_cash_sales,
//	  0 + SUM(
//	      CASE
//	          WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
//	              WHEN ot.transaction_type = 'SALE' THEN 1
//	              WHEN ot.transaction_type = 'REFUND' THEN -1
//	              ELSE 0
//	          END
//	          ELSE 0
//	      END
//	  ) AS net_card_sales,
//
// SELECT
//
//	0 + SUM(
//	    CASE
//	        WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
//	        WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
//	        ELSE 0
//	    END
//	) AS net_sales
//
// FROM
//
//	order_transaction ot
//
// WHERE
//
//	ot.type_id = ?
//	AND ot.`type` = 'ORDER'
//
// GROUP BY
//
//	ot.type_id
func (q *Queries) GetNetCashAndCardSaleByOrderID(ctx context.Context, typeID uint64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNetCashAndCardSaleByOrderID, typeID)
	var net_sales int32
	err := row.Scan(&net_sales)
	return net_sales, err
}

const getOrderTransactionByRefundID = `-- name: GetOrderTransactionByRefundID :one
SELECT ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at, orf.reason, orf.transaction_id AS refund_transaction_id
FROM
    order_transaction ot
    LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
WHERE
    orf.id = ?
`

type GetOrderTransactionByRefundIDRow struct {
	OrderTransaction    OrderTransaction `json:"order_transaction"`
	Reason              sql.NullString   `json:"reason"`
	RefundTransactionID sql.NullInt64    `json:"refund_transaction_id"`
}

// GetOrderTransactionByRefundID
//
//	SELECT ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at, orf.reason, orf.transaction_id AS refund_transaction_id
//	FROM
//	    order_transaction ot
//	    LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
//	WHERE
//	    orf.id = ?
func (q *Queries) GetOrderTransactionByRefundID(ctx context.Context, id uint64) (*GetOrderTransactionByRefundIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderTransactionByRefundID, id)
	var i GetOrderTransactionByRefundIDRow
	err := row.Scan(
		&i.OrderTransaction.ID,
		&i.OrderTransaction.TypeID,
		&i.OrderTransaction.Type,
		&i.OrderTransaction.TransactionType,
		&i.OrderTransaction.TransactionAmount,
		&i.OrderTransaction.TransactionMode,
		&i.OrderTransaction.PaymentType,
		&i.OrderTransaction.Platform,
		&i.OrderTransaction.CreatedAt,
		&i.OrderTransaction.UpdatedAt,
		&i.Reason,
		&i.RefundTransactionID,
	)
	return &i, err
}

const getOrderTransactions = `-- name: GetOrderTransactions :many
SELECT
    ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
    orf.id AS refund_id,
    orf.reason,
    orf.transaction_id AS refund_transaction_id
FROM
    order_transaction ot
    LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
WHERE
    ot.type_id = ?
ORDER BY ot.id DESC
`

type GetOrderTransactionsRow struct {
	OrderTransaction    OrderTransaction `json:"order_transaction"`
	RefundID            sql.NullInt64    `json:"refund_id"`
	Reason              sql.NullString   `json:"reason"`
	RefundTransactionID sql.NullInt64    `json:"refund_transaction_id"`
}

// GetOrderTransactions
//
//	SELECT
//	    ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
//	    orf.id AS refund_id,
//	    orf.reason,
//	    orf.transaction_id AS refund_transaction_id
//	FROM
//	    order_transaction ot
//	    LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
//	WHERE
//	    ot.type_id = ?
//	ORDER BY ot.id DESC
func (q *Queries) GetOrderTransactions(ctx context.Context, typeID uint64) ([]*GetOrderTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderTransactions, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOrderTransactionsRow{}
	for rows.Next() {
		var i GetOrderTransactionsRow
		if err := rows.Scan(
			&i.OrderTransaction.ID,
			&i.OrderTransaction.TypeID,
			&i.OrderTransaction.Type,
			&i.OrderTransaction.TransactionType,
			&i.OrderTransaction.TransactionAmount,
			&i.OrderTransaction.TransactionMode,
			&i.OrderTransaction.PaymentType,
			&i.OrderTransaction.Platform,
			&i.OrderTransaction.CreatedAt,
			&i.OrderTransaction.UpdatedAt,
			&i.RefundID,
			&i.Reason,
			&i.RefundTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaleTransactionByOrderID = `-- name: GetSaleTransactionByOrderID :one
SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
FROM order_transaction
WHERE
    type_id = ?
    AND transaction_type = 'SALE'
    AND ` + "`" + `type` + "`" + ` = 'ORDER'
`

// GetSaleTransactionByOrderID
//
//	SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
//	FROM order_transaction
//	WHERE
//	    type_id = ?
//	    AND transaction_type = 'SALE'
//	    AND `type` = 'ORDER'
func (q *Queries) GetSaleTransactionByOrderID(ctx context.Context, typeID uint64) (*OrderTransaction, error) {
	row := q.db.QueryRowContext(ctx, getSaleTransactionByOrderID, typeID)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Type,
		&i.TransactionType,
		&i.TransactionAmount,
		&i.TransactionMode,
		&i.PaymentType,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSalesAndRefundByTypeID = `-- name: GetSalesAndRefundByTypeID :one
SELECT
    0 + SUM(
        CASE
            WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
                WHEN ot.transaction_type = 'SALE' THEN 1
                ELSE 0
            END
            ELSE 0
        END
    ) AS cash_sale,
    0 + SUM(
        CASE
            WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
                WHEN ot.transaction_type = 'SALE' THEN 1
                ELSE 0
            END
            ELSE 0
        END
    ) AS card_sale,
    0 + SUM(
        CASE
            WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
                WHEN ot.transaction_type = 'REFUND' THEN 1
                ELSE 0
            END
            ELSE 0
        END
    ) AS cash_refund,
    0 + SUM(
        CASE
            WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
                WHEN ot.transaction_type = 'REFUND' THEN 1
                ELSE 0
            END
            ELSE 0
        END
    ) AS card_refund,
    0 + SUM(
        CASE
            WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
            WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
            ELSE 0
        END
    ) AS net_sale
FROM order_transaction ot
WHERE
    ot.type_id = ?
GROUP BY
    ot.type_id
`

type GetSalesAndRefundByTypeIDRow struct {
	CashSale   int32 `json:"cash_sale"`
	CardSale   int32 `json:"card_sale"`
	CashRefund int32 `json:"cash_refund"`
	CardRefund int32 `json:"card_refund"`
	NetSale    int32 `json:"net_sale"`
}

// GetSalesAndRefundByTypeID
//
//	SELECT
//	    0 + SUM(
//	        CASE
//	            WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
//	                WHEN ot.transaction_type = 'SALE' THEN 1
//	                ELSE 0
//	            END
//	            ELSE 0
//	        END
//	    ) AS cash_sale,
//	    0 + SUM(
//	        CASE
//	            WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
//	                WHEN ot.transaction_type = 'SALE' THEN 1
//	                ELSE 0
//	            END
//	            ELSE 0
//	        END
//	    ) AS card_sale,
//	    0 + SUM(
//	        CASE
//	            WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
//	                WHEN ot.transaction_type = 'REFUND' THEN 1
//	                ELSE 0
//	            END
//	            ELSE 0
//	        END
//	    ) AS cash_refund,
//	    0 + SUM(
//	        CASE
//	            WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
//	                WHEN ot.transaction_type = 'REFUND' THEN 1
//	                ELSE 0
//	            END
//	            ELSE 0
//	        END
//	    ) AS card_refund,
//	    0 + SUM(
//	        CASE
//	            WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
//	            WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
//	            ELSE 0
//	        END
//	    ) AS net_sale
//	FROM order_transaction ot
//	WHERE
//	    ot.type_id = ?
//	GROUP BY
//	    ot.type_id
func (q *Queries) GetSalesAndRefundByTypeID(ctx context.Context, typeID uint64) (*GetSalesAndRefundByTypeIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesAndRefundByTypeID, typeID)
	var i GetSalesAndRefundByTypeIDRow
	err := row.Scan(
		&i.CashSale,
		&i.CardSale,
		&i.CashRefund,
		&i.CardRefund,
		&i.NetSale,
	)
	return &i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at FROM order_transaction WHERE id = ?
`

// GetTransactionByID
//
//	SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at FROM order_transaction WHERE id = ?
func (q *Queries) GetTransactionByID(ctx context.Context, id uint64) (*OrderTransaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Type,
		&i.TransactionType,
		&i.TransactionAmount,
		&i.TransactionMode,
		&i.PaymentType,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
