// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_refund.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderRefund = `-- name: CreateOrderRefund :execlastid
INSERT INTO
    order_refund (
        type_id,
        ` + "`" + `type` + "`" + `,
        transaction_id,
        refund_amount,
        refund_mode,
        reason,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateOrderRefundParams struct {
	TypeID        uint64         `json:"type_id"`
	Type          string         `json:"type"`
	TransactionID uint64         `json:"transaction_id"`
	RefundAmount  int32          `json:"refund_amount"`
	RefundMode    string         `json:"refund_mode"`
	Reason        sql.NullString `json:"reason"`
}

// CreateOrderRefund
//
//	INSERT INTO
//	    order_refund (
//	        type_id,
//	        `type`,
//	        transaction_id,
//	        refund_amount,
//	        refund_mode,
//	        reason,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
func (q *Queries) CreateOrderRefund(ctx context.Context, arg *CreateOrderRefundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrderRefund,
		arg.TypeID,
		arg.Type,
		arg.TransactionID,
		arg.RefundAmount,
		arg.RefundMode,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getLatestRefundByOrderID = `-- name: GetLatestRefundByOrderID :one
SELECT 
  ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
  orf.id AS refund_id,
  orf.reason
FROM order_refund orf
JOIN order_transaction ot ON ot.id = orf.transaction_id
WHERE 
  orf.type_id = ?
  AND orf.` + "`" + `type` + "`" + ` = 'ORDER'
ORDER BY id DESC
LIMIT 1
`

type GetLatestRefundByOrderIDRow struct {
	OrderTransaction OrderTransaction `json:"order_transaction"`
	RefundID         uint64           `json:"refund_id"`
	Reason           sql.NullString   `json:"reason"`
}

// GetLatestRefundByOrderID
//
//	SELECT
//	  ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
//	  orf.id AS refund_id,
//	  orf.reason
//	FROM order_refund orf
//	JOIN order_transaction ot ON ot.id = orf.transaction_id
//	WHERE
//	  orf.type_id = ?
//	  AND orf.`type` = 'ORDER'
//	ORDER BY id DESC
//	LIMIT 1
func (q *Queries) GetLatestRefundByOrderID(ctx context.Context, typeID uint64) (*GetLatestRefundByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestRefundByOrderID, typeID)
	var i GetLatestRefundByOrderIDRow
	err := row.Scan(
		&i.OrderTransaction.ID,
		&i.OrderTransaction.TypeID,
		&i.OrderTransaction.Type,
		&i.OrderTransaction.TransactionType,
		&i.OrderTransaction.TransactionAmount,
		&i.OrderTransaction.TransactionMode,
		&i.OrderTransaction.PaymentType,
		&i.OrderTransaction.Platform,
		&i.OrderTransaction.CreatedAt,
		&i.OrderTransaction.UpdatedAt,
		&i.RefundID,
		&i.Reason,
	)
	return &i, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE id = ?
`

// GetRefundByID
//
//	SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE id = ?
func (q *Queries) GetRefundByID(ctx context.Context, id uint64) (*OrderRefund, error) {
	row := q.db.QueryRowContext(ctx, getRefundByID, id)
	var i OrderRefund
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Type,
		&i.TransactionID,
		&i.RefundAmount,
		&i.RefundMode,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRefundsByOrderID = `-- name: GetRefundsByOrderID :many
SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE type_id = ? AND ` + "`" + `type` + "`" + ` = 'ORDER'
`

// GetRefundsByOrderID
//
//	SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE type_id = ? AND `type` = 'ORDER'
func (q *Queries) GetRefundsByOrderID(ctx context.Context, typeID uint64) ([]*OrderRefund, error) {
	rows, err := q.db.QueryContext(ctx, getRefundsByOrderID, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrderRefund{}
	for rows.Next() {
		var i OrderRefund
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Type,
			&i.TransactionID,
			&i.RefundAmount,
			&i.RefundMode,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
