// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_taxes_query.sql

package db

import (
	"context"
)

const deleteOrderTaxes = `-- name: DeleteOrderTaxes :exec
DELETE FROM order_taxes WHERE order_id = ?
`

// DeleteOrderTaxes
//
//	DELETE FROM order_taxes WHERE order_id = ?
func (q *Queries) DeleteOrderTaxes(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrderTaxes, orderID)
	return err
}

const getOrderSalesTaxes = `-- name: GetOrderSalesTaxes :many
SELECT id, order_id, tax_rate, tax_code, tax_amount, taxable_amount, type, created_at, updated_at FROM order_taxes WHERE order_id = ? AND type = 'SALE'
`

// GetOrderSalesTaxes
//
//	SELECT id, order_id, tax_rate, tax_code, tax_amount, taxable_amount, type, created_at, updated_at FROM order_taxes WHERE order_id = ? AND type = 'SALE'
func (q *Queries) GetOrderSalesTaxes(ctx context.Context, orderID int32) ([]*OrderTax, error) {
	rows, err := q.db.QueryContext(ctx, getOrderSalesTaxes, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrderTax{}
	for rows.Next() {
		var i OrderTax
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TaxRate,
			&i.TaxCode,
			&i.TaxAmount,
			&i.TaxableAmount,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrderTaxable = `-- name: InsertOrderTaxable :exec
INSERT INTO
    order_taxes (
        order_id,
        tax_rate,
        tax_code,
        tax_amount,
        taxable_amount,
        type,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type InsertOrderTaxableParams struct {
	OrderID       int32  `json:"order_id"`
	TaxRate       string `json:"tax_rate"`
	TaxCode       string `json:"tax_code"`
	TaxAmount     int32  `json:"tax_amount"`
	TaxableAmount int32  `json:"taxable_amount"`
	Type          string `json:"type"`
}

// InsertOrderTaxable
//
//	INSERT INTO
//	    order_taxes (
//	        order_id,
//	        tax_rate,
//	        tax_code,
//	        tax_amount,
//	        taxable_amount,
//	        type,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
func (q *Queries) InsertOrderTaxable(ctx context.Context, arg *InsertOrderTaxableParams) error {
	_, err := q.db.ExecContext(ctx, insertOrderTaxable,
		arg.OrderID,
		arg.TaxRate,
		arg.TaxCode,
		arg.TaxAmount,
		arg.TaxableAmount,
		arg.Type,
	)
	return err
}
