// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_shop_fee.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderShopFee = `-- name: CreateOrderShopFee :exec
INSERT INTO
    order_shop_fee (
        order_id,
        shop_fee_id,
        amount,
        shop_fee_tax,
        tax_id,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderShopFeeParams struct {
	OrderID    int32         `json:"order_id"`
	ShopFeeID  int32         `json:"shop_fee_id"`
	Amount     int32         `json:"amount"`
	ShopFeeTax sql.NullInt32 `json:"shop_fee_tax"`
	TaxID      sql.NullInt32 `json:"tax_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

// CreateOrderShopFee
//
//	INSERT INTO
//	    order_shop_fee (
//	        order_id,
//	        shop_fee_id,
//	        amount,
//	        shop_fee_tax,
//	        tax_id,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateOrderShopFee(ctx context.Context, arg *CreateOrderShopFeeParams) error {
	_, err := q.db.ExecContext(ctx, createOrderShopFee,
		arg.OrderID,
		arg.ShopFeeID,
		arg.Amount,
		arg.ShopFeeTax,
		arg.TaxID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
