// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_item_modifier_query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createOrderItemModifier = `-- name: CreateOrderItemModifier :execlastid
INSERT INTO
    order_item_modifier (
        order_item_id,
        parent_modifier_id,
        sub_parent_modifier_id,
        modifier_id,
        modifier_group_name,
        modifier_option_id,
        modifier_option_name,
        amount,
        quantity,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
`

type CreateOrderItemModifierParams struct {
	OrderItemID         int32          `json:"order_item_id"`
	ParentModifierID    sql.NullString `json:"parent_modifier_id"`
	SubParentModifierID sql.NullString `json:"sub_parent_modifier_id"`
	ModifierID          string         `json:"modifier_id"`
	ModifierGroupName   string         `json:"modifier_group_name"`
	ModifierOptionID    string         `json:"modifier_option_id"`
	ModifierOptionName  string         `json:"modifier_option_name"`
	Amount              string         `json:"amount"`
	Quantity            string         `json:"quantity"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

// CreateOrderItemModifier
//
//	INSERT INTO
//	    order_item_modifier (
//	        order_item_id,
//	        parent_modifier_id,
//	        sub_parent_modifier_id,
//	        modifier_id,
//	        modifier_group_name,
//	        modifier_option_id,
//	        modifier_option_name,
//	        amount,
//	        quantity,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?
//	    )
func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg *CreateOrderItemModifierParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrderItemModifier,
		arg.OrderItemID,
		arg.ParentModifierID,
		arg.SubParentModifierID,
		arg.ModifierID,
		arg.ModifierGroupName,
		arg.ModifierOptionID,
		arg.ModifierOptionName,
		arg.Amount,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteOrderItemModifiers = `-- name: DeleteOrderItemModifiers :exec
DELETE FROM order_item_modifier
WHERE
    order_item_id IN (/*SLICE:order_item_ids*/?)
`

// DeleteOrderItemModifiers
//
//	DELETE FROM order_item_modifier
//	WHERE
//	    order_item_id IN (/*SLICE:order_item_ids*/?)
func (q *Queries) DeleteOrderItemModifiers(ctx context.Context, orderItemIds []int32) error {
	query := deleteOrderItemModifiers
	var queryParams []interface{}
	if len(orderItemIds) > 0 {
		for _, v := range orderItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_item_ids*/?", strings.Repeat(",?", len(orderItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_item_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
