// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_item_query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createOrderItem = `-- name: CreateOrderItem :execlastid
INSERT INTO
    order_items (
        order_id,
        item_id,
        quantity,
        price_per_item,
        total,
        original_price,
        is_sale,
        discount_amount,
        status,
        created_at,
        updated_at,
        item_name,
        category_name,
        modifiers,
        tax,
        note
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
`

type CreateOrderItemParams struct {
	OrderID        int32          `json:"order_id"`
	ItemID         string         `json:"item_id"`
	Quantity       float64        `json:"quantity"`
	PricePerItem   int32          `json:"price_per_item"`
	Total          int32          `json:"total"`
	OriginalPrice  int32          `json:"original_price"`
	IsSale         bool           `json:"is_sale"`
	DiscountAmount int32          `json:"discount_amount"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ItemName       string         `json:"item_name"`
	CategoryName   sql.NullString `json:"category_name"`
	Modifiers      sql.NullString `json:"modifiers"`
	Tax            int32          `json:"tax"`
	Note           sql.NullString `json:"note"`
}

// CreateOrderItem
//
//	INSERT INTO
//	    order_items (
//	        order_id,
//	        item_id,
//	        quantity,
//	        price_per_item,
//	        total,
//	        original_price,
//	        is_sale,
//	        discount_amount,
//	        status,
//	        created_at,
//	        updated_at,
//	        item_name,
//	        category_name,
//	        modifiers,
//	        tax,
//	        note
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?
//	    )
func (q *Queries) CreateOrderItem(ctx context.Context, arg *CreateOrderItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ItemID,
		arg.Quantity,
		arg.PricePerItem,
		arg.Total,
		arg.OriginalPrice,
		arg.IsSale,
		arg.DiscountAmount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ItemName,
		arg.CategoryName,
		arg.Modifiers,
		arg.Tax,
		arg.Note,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items WHERE order_id = ?
`

// DeleteOrderItems
//
//	DELETE FROM order_items WHERE order_id = ?
func (q *Queries) DeleteOrderItems(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItems, orderID)
	return err
}

const getAllOrderItemIDs = `-- name: GetAllOrderItemIDs :many
SELECT id FROM order_items WHERE order_id = ?
`

// GetAllOrderItemIDs
//
//	SELECT id FROM order_items WHERE order_id = ?
func (q *Queries) GetAllOrderItemIDs(ctx context.Context, orderID int32) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrderItemIDs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableOrderItems = `-- name: GetAvailableOrderItems :many
SELECT id, entity_id, delivery_platform_id, external_item_id, created_at, updated_at, plu, price, item_name, allergies, available, available_from
FROM entity_delivery_platform
WHERE
    entity_id IN (/*SLICE:item_ids*/?)
    AND delivery_platform_id = ?
    AND available = 1
`

type GetAvailableOrderItemsParams struct {
	ItemIds            []sql.NullInt32 `json:"item_ids"`
	DeliveryPlatformID int32           `json:"delivery_platform_id"`
}

// GetAvailableOrderItems
//
//	SELECT id, entity_id, delivery_platform_id, external_item_id, created_at, updated_at, plu, price, item_name, allergies, available, available_from
//	FROM entity_delivery_platform
//	WHERE
//	    entity_id IN (/*SLICE:item_ids*/?)
//	    AND delivery_platform_id = ?
//	    AND available = 1
func (q *Queries) GetAvailableOrderItems(ctx context.Context, arg *GetAvailableOrderItemsParams) ([]*EntityDeliveryPlatform, error) {
	query := getAvailableOrderItems
	var queryParams []interface{}
	if len(arg.ItemIds) > 0 {
		for _, v := range arg.ItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_ids*/?", strings.Repeat(",?", len(arg.ItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.DeliveryPlatformID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EntityDeliveryPlatform{}
	for rows.Next() {
		var i EntityDeliveryPlatform
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.DeliveryPlatformID,
			&i.ExternalItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Plu,
			&i.Price,
			&i.ItemName,
			&i.Allergies,
			&i.Available,
			&i.AvailableFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
select 
  oi.id, oi.order_id, oi.item_id, oi.quantity, oi.price_per_item, oi.total, oi.original_price, oi.is_sale, oi.discount_amount, oi.status, oi.created_at, oi.updated_at, oi.item_name, oi.category_name, oi.modifiers, oi.tax, oi.note,
  oit.id as order_item_tax_id,
  oit.tax_profile_id as tax_profile_id,
  oit.tax_rule_id as tax_rule_id,
  oit.tax_id as tax_id,
  oit.amount as tax_amount,
  t.code as tax_code,
  t.rate as tax_rate
from order_items oi
left join order_item_tax oit on oit.order_item_id = oi.id and oit.order_item_modifier_id is null
left join taxes_main t on t.id = oit.tax_id
where oi.order_id = ?
`

type GetOrderItemsByOrderIDRow struct {
	ID             uint64         `json:"id"`
	OrderID        int32          `json:"order_id"`
	ItemID         string         `json:"item_id"`
	Quantity       float64        `json:"quantity"`
	PricePerItem   int32          `json:"price_per_item"`
	Total          int32          `json:"total"`
	OriginalPrice  int32          `json:"original_price"`
	IsSale         bool           `json:"is_sale"`
	DiscountAmount int32          `json:"discount_amount"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ItemName       string         `json:"item_name"`
	CategoryName   sql.NullString `json:"category_name"`
	Modifiers      sql.NullString `json:"modifiers"`
	Tax            int32          `json:"tax"`
	Note           sql.NullString `json:"note"`
	OrderItemTaxID sql.NullInt64  `json:"order_item_tax_id"`
	TaxProfileID   sql.NullInt32  `json:"tax_profile_id"`
	TaxRuleID      sql.NullInt32  `json:"tax_rule_id"`
	TaxID          sql.NullInt32  `json:"tax_id"`
	TaxAmount      sql.NullInt32  `json:"tax_amount"`
	TaxCode        sql.NullString `json:"tax_code"`
	TaxRate        sql.NullString `json:"tax_rate"`
}

// GetOrderItemsByOrderID
//
//	select
//	  oi.id, oi.order_id, oi.item_id, oi.quantity, oi.price_per_item, oi.total, oi.original_price, oi.is_sale, oi.discount_amount, oi.status, oi.created_at, oi.updated_at, oi.item_name, oi.category_name, oi.modifiers, oi.tax, oi.note,
//	  oit.id as order_item_tax_id,
//	  oit.tax_profile_id as tax_profile_id,
//	  oit.tax_rule_id as tax_rule_id,
//	  oit.tax_id as tax_id,
//	  oit.amount as tax_amount,
//	  t.code as tax_code,
//	  t.rate as tax_rate
//	from order_items oi
//	left join order_item_tax oit on oit.order_item_id = oi.id and oit.order_item_modifier_id is null
//	left join taxes_main t on t.id = oit.tax_id
//	where oi.order_id = ?
func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int32) ([]*GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ItemID,
			&i.Quantity,
			&i.PricePerItem,
			&i.Total,
			&i.OriginalPrice,
			&i.IsSale,
			&i.DiscountAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemName,
			&i.CategoryName,
			&i.Modifiers,
			&i.Tax,
			&i.Note,
			&i.OrderItemTaxID,
			&i.TaxProfileID,
			&i.TaxRuleID,
			&i.TaxID,
			&i.TaxAmount,
			&i.TaxCode,
			&i.TaxRate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItemsStatus = `-- name: UpdateOrderItemsStatus :exec
UPDATE ` + "`" + `order_items` + "`" + ` SET status = ? WHERE order_id = ?
`

type UpdateOrderItemsStatusParams struct {
	Status  string `json:"status"`
	OrderID int32  `json:"order_id"`
}

// UpdateOrderItemsStatus
//
//	UPDATE `order_items` SET status = ? WHERE order_id = ?
func (q *Queries) UpdateOrderItemsStatus(ctx context.Context, arg *UpdateOrderItemsStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderItemsStatus, arg.Status, arg.OrderID)
	return err
}
