// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_item_taxes_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderItemTax = `-- name: CreateOrderItemTax :exec
INSERT INTO
    order_item_tax (
        order_id,
        order_item_id,
        order_item_modifier_id,
        item_price,
        tax_id,
        tax_profile_id,
        tax_rule_id,
        amount,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateOrderItemTaxParams struct {
	OrderID             int32         `json:"order_id"`
	OrderItemID         int32         `json:"order_item_id"`
	OrderItemModifierID sql.NullInt32 `json:"order_item_modifier_id"`
	ItemPrice           int32         `json:"item_price"`
	TaxID               int32         `json:"tax_id"`
	TaxProfileID        int32         `json:"tax_profile_id"`
	TaxRuleID           int32         `json:"tax_rule_id"`
	Amount              int32         `json:"amount"`
}

// CreateOrderItemTax
//
//	INSERT INTO
//	    order_item_tax (
//	        order_id,
//	        order_item_id,
//	        order_item_modifier_id,
//	        item_price,
//	        tax_id,
//	        tax_profile_id,
//	        tax_rule_id,
//	        amount,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
func (q *Queries) CreateOrderItemTax(ctx context.Context, arg *CreateOrderItemTaxParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItemTax,
		arg.OrderID,
		arg.OrderItemID,
		arg.OrderItemModifierID,
		arg.ItemPrice,
		arg.TaxID,
		arg.TaxProfileID,
		arg.TaxRuleID,
		arg.Amount,
	)
	return err
}

const deleteOrderItemTaxes = `-- name: DeleteOrderItemTaxes :exec
DELETE FROM order_item_tax WHERE order_id = ?
`

// DeleteOrderItemTaxes
//
//	DELETE FROM order_item_tax WHERE order_id = ?
func (q *Queries) DeleteOrderItemTaxes(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItemTaxes, orderID)
	return err
}

const getOrderItemTaxes = `-- name: GetOrderItemTaxes :many
SELECT 
  oit.id, oit.order_id, oit.order_item_id, oit.order_item_modifier_id, oit.item_price, oit.tax_id, oit.tax_profile_id, oit.tax_rule_id, oit.amount, oit.created_at, oit.updated_at,
  t.code AS tax_code,
  t.rate AS tax_rate
FROM 
  order_item_tax oit 
  JOIN taxes_main t ON t.id = oit.tax_id
WHERE 
  oit.order_id = ?
`

type GetOrderItemTaxesRow struct {
	ID                  uint64         `json:"id"`
	OrderID             int32          `json:"order_id"`
	OrderItemID         int32          `json:"order_item_id"`
	OrderItemModifierID sql.NullInt32  `json:"order_item_modifier_id"`
	ItemPrice           int32          `json:"item_price"`
	TaxID               int32          `json:"tax_id"`
	TaxProfileID        int32          `json:"tax_profile_id"`
	TaxRuleID           int32          `json:"tax_rule_id"`
	Amount              int32          `json:"amount"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	TaxCode             string         `json:"tax_code"`
	TaxRate             sql.NullString `json:"tax_rate"`
}

// GetOrderItemTaxes
//
//	SELECT
//	  oit.id, oit.order_id, oit.order_item_id, oit.order_item_modifier_id, oit.item_price, oit.tax_id, oit.tax_profile_id, oit.tax_rule_id, oit.amount, oit.created_at, oit.updated_at,
//	  t.code AS tax_code,
//	  t.rate AS tax_rate
//	FROM
//	  order_item_tax oit
//	  JOIN taxes_main t ON t.id = oit.tax_id
//	WHERE
//	  oit.order_id = ?
func (q *Queries) GetOrderItemTaxes(ctx context.Context, orderID int32) ([]*GetOrderItemTaxesRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemTaxes, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOrderItemTaxesRow{}
	for rows.Next() {
		var i GetOrderItemTaxesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrderItemID,
			&i.OrderItemModifierID,
			&i.ItemPrice,
			&i.TaxID,
			&i.TaxProfileID,
			&i.TaxRuleID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaxCode,
			&i.TaxRate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
