// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_status_timestamps_query.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderStatusTimestamps = `-- name: CreateOrderStatusTimestamps :exec
INSERT INTO
    dg_pos_order_status_timestamps (
        order_id,
        queue,
        preparing,
        ready,
        served,
        delivered,
        completed,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderStatusTimestampsParams struct {
	OrderID   int32        `json:"order_id"`
	Queue     sql.NullTime `json:"queue"`
	Preparing sql.NullTime `json:"preparing"`
	Ready     sql.NullTime `json:"ready"`
	Served    sql.NullTime `json:"served"`
	Delivered sql.NullTime `json:"delivered"`
	Completed sql.NullTime `json:"completed"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// CreateOrderStatusTimestamps
//
//	INSERT INTO
//	    dg_pos_order_status_timestamps (
//	        order_id,
//	        queue,
//	        preparing,
//	        ready,
//	        served,
//	        delivered,
//	        completed,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateOrderStatusTimestamps(ctx context.Context, arg *CreateOrderStatusTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, createOrderStatusTimestamps,
		arg.OrderID,
		arg.Queue,
		arg.Preparing,
		arg.Ready,
		arg.Served,
		arg.Delivered,
		arg.Completed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrderStatusTimestamps = `-- name: GetOrderStatusTimestamps :one
SELECT id, order_id, queue, preparing, ready, served, delivered, completed, created_at, updated_at FROM dg_pos_order_status_timestamps WHERE order_id = ?
`

// GetOrderStatusTimestamps
//
//	SELECT id, order_id, queue, preparing, ready, served, delivered, completed, created_at, updated_at FROM dg_pos_order_status_timestamps WHERE order_id = ?
func (q *Queries) GetOrderStatusTimestamps(ctx context.Context, orderID int32) (*DgPosOrderStatusTimestamp, error) {
	row := q.db.QueryRowContext(ctx, getOrderStatusTimestamps, orderID)
	var i DgPosOrderStatusTimestamp
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Queue,
		&i.Preparing,
		&i.Ready,
		&i.Served,
		&i.Delivered,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateOrderTimestamps = `-- name: UpdateOrderTimestamps :exec
UPDATE dg_pos_order_status_timestamps
SET
    queue = ?,
    preparing = ?,
    ready = ?,
    served = ?,
    delivered = ?,
    completed = ?,
    updated_at = ?
WHERE
    order_id = ?
`

type UpdateOrderTimestampsParams struct {
	Queue     sql.NullTime `json:"queue"`
	Preparing sql.NullTime `json:"preparing"`
	Ready     sql.NullTime `json:"ready"`
	Served    sql.NullTime `json:"served"`
	Delivered sql.NullTime `json:"delivered"`
	Completed sql.NullTime `json:"completed"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	OrderID   int32        `json:"order_id"`
}

// UpdateOrderTimestamps
//
//	UPDATE dg_pos_order_status_timestamps
//	SET
//	    queue = ?,
//	    preparing = ?,
//	    ready = ?,
//	    served = ?,
//	    delivered = ?,
//	    completed = ?,
//	    updated_at = ?
//	WHERE
//	    order_id = ?
func (q *Queries) UpdateOrderTimestamps(ctx context.Context, arg *UpdateOrderTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTimestamps,
		arg.Queue,
		arg.Preparing,
		arg.Ready,
		arg.Served,
		arg.Delivered,
		arg.Completed,
		arg.UpdatedAt,
		arg.OrderID,
	)
	return err
}
