// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createOrder = `-- name: CreateOrder :execlastid
INSERT INTO
    ` + "`" + `order` + "`" + ` (
        shop_id,
        platform_id,
        remote_order_id,
        display_order_id,
        delivery_date_time,
        total_amount,
        sub_total,
        total_fee,
        campaign_code,
        discount,
        voucher_discount,
        discount_mode_applied,
        discount_percentage_applied,
        discount_type,
        vouchers,
        status,
        cancelled_reason,
        order_type_id,
        note,
        customer_name,
        user_id,
        customer_id,
        delivery_location_id,
        shipping_method,
        shipping_total,
        shipping_tax,
        tax_id,
        delivery_tax,
        total_tax,
        cash_due,
        surcharge,
        contact_access_code,
        testing_order,
        cancelled_by_customer,
        payment_method,
        payment_mode,
        is_scheduled,
        is_table_order,
        tip,
        tip_percentage,
        dgpos_table_id,
        table_order_method_id,
        device_platform,
        order_delayed,
        unique_order_id,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
`

type CreateOrderParams struct {
	ShopID                    int32          `json:"shop_id"`
	DeliveryPlatformID        int32          `json:"delivery_platform_id"`
	RemoteOrderID             string         `json:"remote_order_id"`
	DisplayOrderID            sql.NullString `json:"display_order_id"`
	DeliveryDateTime          time.Time      `json:"delivery_date_time"`
	TotalAmount               int32          `json:"total_amount"`
	SubTotal                  sql.NullInt32  `json:"sub_total"`
	TotalFee                  sql.NullInt32  `json:"total_fee"`
	CampaignCode              sql.NullString `json:"campaign_code"`
	Discount                  int32          `json:"discount"`
	VoucherDiscount           int32          `json:"voucher_discount"`
	DiscountModeApplied       sql.NullString `json:"discount_mode_applied"`
	DiscountPercentageApplied sql.NullInt32  `json:"discount_percentage_applied"`
	DiscountType              sql.NullString `json:"discount_type"`
	Vouchers                  sql.NullString `json:"vouchers"`
	Status                    string         `json:"status"`
	CancelledReason           sql.NullString `json:"cancelled_reason"`
	OrderTypeID               sql.NullInt32  `json:"order_type_id"`
	Note                      sql.NullString `json:"note"`
	CustomerName              sql.NullString `json:"customer_name"`
	UserID                    sql.NullInt32  `json:"user_id"`
	CustomerID                sql.NullInt32  `json:"customer_id"`
	DeliveryLocationID        sql.NullInt32  `json:"delivery_location_id"`
	ShippingMethod            sql.NullString `json:"shipping_method"`
	ShippingTotal             sql.NullString `json:"shipping_total"`
	ShippingTax               sql.NullString `json:"shipping_tax"`
	TaxID                     sql.NullInt32  `json:"tax_id"`
	DeliveryTax               sql.NullInt32  `json:"delivery_tax"`
	TotalTax                  sql.NullString `json:"total_tax"`
	CashDue                   string         `json:"cash_due"`
	Surcharge                 string         `json:"surcharge"`
	ContactAccessCode         sql.NullString `json:"contact_access_code"`
	TestingOrder              bool           `json:"testing_order"`
	CancelledByCustomer       bool           `json:"cancelled_by_customer"`
	PaymentMethod             sql.NullString `json:"payment_method"`
	PaymentMode               sql.NullString `json:"payment_mode"`
	IsScheduled               bool           `json:"is_scheduled"`
	IsTableOrder              bool           `json:"is_table_order"`
	Tip                       string         `json:"tip"`
	TipPercentage             string         `json:"tip_percentage"`
	DgposTableID              sql.NullInt32  `json:"dgpos_table_id"`
	TableOrderMethodID        sql.NullInt32  `json:"table_order_method_id"`
	DevicePlatform            sql.NullString `json:"device_platform"`
	OrderDelayed              bool           `json:"order_delayed"`
	UniqueOrderID             sql.NullString `json:"unique_order_id"`
}

// CreateOrder
//
//	INSERT INTO
//	    `order` (
//	        shop_id,
//	        platform_id,
//	        remote_order_id,
//	        display_order_id,
//	        delivery_date_time,
//	        total_amount,
//	        sub_total,
//	        total_fee,
//	        campaign_code,
//	        discount,
//	        voucher_discount,
//	        discount_mode_applied,
//	        discount_percentage_applied,
//	        discount_type,
//	        vouchers,
//	        status,
//	        cancelled_reason,
//	        order_type_id,
//	        note,
//	        customer_name,
//	        user_id,
//	        customer_id,
//	        delivery_location_id,
//	        shipping_method,
//	        shipping_total,
//	        shipping_tax,
//	        tax_id,
//	        delivery_tax,
//	        total_tax,
//	        cash_due,
//	        surcharge,
//	        contact_access_code,
//	        testing_order,
//	        cancelled_by_customer,
//	        payment_method,
//	        payment_mode,
//	        is_scheduled,
//	        is_table_order,
//	        tip,
//	        tip_percentage,
//	        dgpos_table_id,
//	        table_order_method_id,
//	        device_platform,
//	        order_delayed,
//	        unique_order_id,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        CURRENT_TIMESTAMP,
//	        CURRENT_TIMESTAMP
//	    )
func (q *Queries) CreateOrder(ctx context.Context, arg *CreateOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrder,
		arg.ShopID,
		arg.DeliveryPlatformID,
		arg.RemoteOrderID,
		arg.DisplayOrderID,
		arg.DeliveryDateTime,
		arg.TotalAmount,
		arg.SubTotal,
		arg.TotalFee,
		arg.CampaignCode,
		arg.Discount,
		arg.VoucherDiscount,
		arg.DiscountModeApplied,
		arg.DiscountPercentageApplied,
		arg.DiscountType,
		arg.Vouchers,
		arg.Status,
		arg.CancelledReason,
		arg.OrderTypeID,
		arg.Note,
		arg.CustomerName,
		arg.UserID,
		arg.CustomerID,
		arg.DeliveryLocationID,
		arg.ShippingMethod,
		arg.ShippingTotal,
		arg.ShippingTax,
		arg.TaxID,
		arg.DeliveryTax,
		arg.TotalTax,
		arg.CashDue,
		arg.Surcharge,
		arg.ContactAccessCode,
		arg.TestingOrder,
		arg.CancelledByCustomer,
		arg.PaymentMethod,
		arg.PaymentMode,
		arg.IsScheduled,
		arg.IsTableOrder,
		arg.Tip,
		arg.TipPercentage,
		arg.DgposTableID,
		arg.TableOrderMethodID,
		arg.DevicePlatform,
		arg.OrderDelayed,
		arg.UniqueOrderID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCustomerOrders = `-- name: GetCustomerOrders :many

SELECT
    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
    dp.platform_id AS dp_id,
    p.name AS platform_name,
    p.logo AS platform_logo
FROM
    ` + "`" + `order` + "`" + ` o
    LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
    LEFT JOIN platform p ON dp.platform_id = p.id
WHERE
    o.customer_id = ?
`

type GetCustomerOrdersRow struct {
	Order        Order          `json:"order"`
	DpID         sql.NullInt32  `json:"dp_id"`
	PlatformName sql.NullString `json:"platform_name"`
	PlatformLogo sql.NullString `json:"platform_logo"`
}

// SELECT
//
//	o.*,
//	cds.id AS cash_drawer_session_id,
//	p.name AS platform_name,
//	c.phone AS customer_contact_number,
//	c.key_id_phone AS customer_key_id_contact_number,
//	c.country_code AS customer_country_code
//
// FROM
//
//	 `order` o
//	JOIN delivery_platform dp ON o.platform_id = dp.id
//	JOIN platform p ON dp.platform_id = p.id
//	JOIN dg_pos_cash_drawer cd ON cd.outlet_id = o.shop_id
//	JOIN dg_pos_cash_drawer_sessions cds ON cds.cash_drawer_id = cd.id
//	AND o.created_at BETWEEN cds.opened_at AND COALESCE(cds.closed_at, NOW())
//	LEFT JOIN customers c ON o.customer_id = c.id
//
// WHERE
//
//	o.status != 'TEMP'
//	AND p.id IN (9,6)
//	AND o.status = 'COMPLETED'
//	AND o.shop_id = 2
//	AND o.created_at BETWEEN '2025-11-03 00:00:00' AND '2025-11-03 23:59:59'
//
// ORDER BY
//
//	   o.id DESC;
//
//
//	SELECT
//	    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
//	    dp.platform_id AS dp_id,
//	    p.name AS platform_name,
//	    p.logo AS platform_logo
//	FROM
//	    `order` o
//	    LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
//	    LEFT JOIN platform p ON dp.platform_id = p.id
//	WHERE
//	    o.customer_id = ?
func (q *Queries) GetCustomerOrders(ctx context.Context, customerID sql.NullInt32) ([]*GetCustomerOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerOrders, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCustomerOrdersRow{}
	for rows.Next() {
		var i GetCustomerOrdersRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.ShopID,
			&i.Order.PlatformID,
			&i.Order.RemoteOrderID,
			&i.Order.DisplayOrderID,
			&i.Order.DeliveryDateTime,
			&i.Order.TotalAmount,
			&i.Order.SubTotal,
			&i.Order.TotalFee,
			&i.Order.CampaignCode,
			&i.Order.Discount,
			&i.Order.VoucherDiscount,
			&i.Order.DiscountModeApplied,
			&i.Order.DiscountPercentageApplied,
			&i.Order.DiscountType,
			&i.Order.Vouchers,
			&i.Order.Status,
			&i.Order.CancelledReason,
			&i.Order.OrderTypeID,
			&i.Order.Note,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CustomerName,
			&i.Order.UserID,
			&i.Order.CustomerID,
			&i.Order.DeliveryLocationID,
			&i.Order.DeliveryTax,
			&i.Order.TaxID,
			&i.Order.ShippingMethod,
			&i.Order.ShippingTotal,
			&i.Order.ShippingTax,
			&i.Order.TotalTax,
			&i.Order.CashDue,
			&i.Order.Surcharge,
			&i.Order.ContactAccessCode,
			&i.Order.TestingOrder,
			&i.Order.CancelledByCustomer,
			&i.Order.PaymentMethod,
			&i.Order.PaymentMode,
			&i.Order.IsScheduled,
			&i.Order.IsTableOrder,
			&i.Order.Tip,
			&i.Order.TipPercentage,
			&i.Order.TableID,
			&i.Order.DgposTableID,
			&i.Order.TableOrderMethodID,
			&i.Order.DevicePlatform,
			&i.Order.OrderDelayed,
			&i.Order.UniqueOrderID,
			&i.Order.OrderSessionID,
			&i.DpID,
			&i.PlatformName,
			&i.PlatformLogo,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMobileAppOrdersCount = `-- name: GetMobileAppOrdersCount :one
SELECT COUNT(o.id) AS mobile_app_orders
FROM ` + "`" + `order` + "`" + ` o
WHERE
    o.device_platform = 'mobile'
    AND o.customer_id = ?
`

// GetMobileAppOrdersCount
//
//	SELECT COUNT(o.id) AS mobile_app_orders
//	FROM `order` o
//	WHERE
//	    o.device_platform = 'mobile'
//	    AND o.customer_id = ?
func (q *Queries) GetMobileAppOrdersCount(ctx context.Context, customerID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMobileAppOrdersCount, customerID)
	var mobile_app_orders int64
	err := row.Scan(&mobile_app_orders)
	return mobile_app_orders, err
}

const getMobileAppReservationsCount = `-- name: GetMobileAppReservationsCount :one
SELECT COUNT(tr.id) AS mobile_app_reservations
FROM table_reservation tr
WHERE
    tr.user_type = 'CUSTOMER'
    AND tr.device_platform = 'mobile'
    AND tr.customer_id = ?
`

// GetMobileAppReservationsCount
//
//	SELECT COUNT(tr.id) AS mobile_app_reservations
//	FROM table_reservation tr
//	WHERE
//	    tr.user_type = 'CUSTOMER'
//	    AND tr.device_platform = 'mobile'
//	    AND tr.customer_id = ?
func (q *Queries) GetMobileAppReservationsCount(ctx context.Context, customerID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMobileAppReservationsCount, customerID)
	var mobile_app_reservations int64
	err := row.Scan(&mobile_app_reservations)
	return mobile_app_reservations, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT
    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
    t.code AS delivery_tax_code,
    t.rate AS delivery_tax_rate,
    0 + COALESCE(
        (
            SELECT cds.id
        FROM dg_pos_cash_drawer cd
        JOIN dg_pos_cash_drawer_sessions cds 
            ON cds.cash_drawer_id = cd.id
        WHERE cd.outlet_id = o.shop_id
          AND o.created_at >= cds.opened_at
          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
        ORDER BY cds.opened_at DESC
        LIMIT 1
        ),
        0
    ) AS shift_id,
    dp.name AS dp_name,
    p.id AS platform_id,
    p.name AS platform_name,
    p.logo AS platform_logo,
    tom.name AS table_order_method_name,
    os.payment_type AS session_payment_type
FROM
    ` + "`" + `order` + "`" + ` o
    LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
    LEFT JOIN platform p ON dp.platform_id = p.id
    LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
    LEFT JOIN taxes_main t ON t.id = o.tax_id
    LEFT JOIN order_session os ON os.id = o.order_session_id
WHERE
    o.id = ?
`

type GetOrderByIdRow struct {
	Order                Order          `json:"order"`
	DeliveryTaxCode      sql.NullString `json:"delivery_tax_code"`
	DeliveryTaxRate      sql.NullString `json:"delivery_tax_rate"`
	ShiftID              int32          `json:"shift_id"`
	DpName               sql.NullString `json:"dp_name"`
	PlatformID           sql.NullInt64  `json:"platform_id"`
	PlatformName         sql.NullString `json:"platform_name"`
	PlatformLogo         sql.NullString `json:"platform_logo"`
	TableOrderMethodName sql.NullString `json:"table_order_method_name"`
	SessionPaymentType   sql.NullString `json:"session_payment_type"`
}

// GetOrderById
//
//	SELECT
//	    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
//	    t.code AS delivery_tax_code,
//	    t.rate AS delivery_tax_rate,
//	    0 + COALESCE(
//	        (
//	            SELECT cds.id
//	        FROM dg_pos_cash_drawer cd
//	        JOIN dg_pos_cash_drawer_sessions cds
//	            ON cds.cash_drawer_id = cd.id
//	        WHERE cd.outlet_id = o.shop_id
//	          AND o.created_at >= cds.opened_at
//	          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
//	        ORDER BY cds.opened_at DESC
//	        LIMIT 1
//	        ),
//	        0
//	    ) AS shift_id,
//	    dp.name AS dp_name,
//	    p.id AS platform_id,
//	    p.name AS platform_name,
//	    p.logo AS platform_logo,
//	    tom.name AS table_order_method_name,
//	    os.payment_type AS session_payment_type
//	FROM
//	    `order` o
//	    LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
//	    LEFT JOIN platform p ON dp.platform_id = p.id
//	    LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
//	    LEFT JOIN taxes_main t ON t.id = o.tax_id
//	    LEFT JOIN order_session os ON os.id = o.order_session_id
//	WHERE
//	    o.id = ?
func (q *Queries) GetOrderById(ctx context.Context, id uint64) (*GetOrderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.Order.ID,
		&i.Order.ShopID,
		&i.Order.PlatformID,
		&i.Order.RemoteOrderID,
		&i.Order.DisplayOrderID,
		&i.Order.DeliveryDateTime,
		&i.Order.TotalAmount,
		&i.Order.SubTotal,
		&i.Order.TotalFee,
		&i.Order.CampaignCode,
		&i.Order.Discount,
		&i.Order.VoucherDiscount,
		&i.Order.DiscountModeApplied,
		&i.Order.DiscountPercentageApplied,
		&i.Order.DiscountType,
		&i.Order.Vouchers,
		&i.Order.Status,
		&i.Order.CancelledReason,
		&i.Order.OrderTypeID,
		&i.Order.Note,
		&i.Order.CreatedAt,
		&i.Order.UpdatedAt,
		&i.Order.CustomerName,
		&i.Order.UserID,
		&i.Order.CustomerID,
		&i.Order.DeliveryLocationID,
		&i.Order.DeliveryTax,
		&i.Order.TaxID,
		&i.Order.ShippingMethod,
		&i.Order.ShippingTotal,
		&i.Order.ShippingTax,
		&i.Order.TotalTax,
		&i.Order.CashDue,
		&i.Order.Surcharge,
		&i.Order.ContactAccessCode,
		&i.Order.TestingOrder,
		&i.Order.CancelledByCustomer,
		&i.Order.PaymentMethod,
		&i.Order.PaymentMode,
		&i.Order.IsScheduled,
		&i.Order.IsTableOrder,
		&i.Order.Tip,
		&i.Order.TipPercentage,
		&i.Order.TableID,
		&i.Order.DgposTableID,
		&i.Order.TableOrderMethodID,
		&i.Order.DevicePlatform,
		&i.Order.OrderDelayed,
		&i.Order.UniqueOrderID,
		&i.Order.OrderSessionID,
		&i.DeliveryTaxCode,
		&i.DeliveryTaxRate,
		&i.ShiftID,
		&i.DpName,
		&i.PlatformID,
		&i.PlatformName,
		&i.PlatformLogo,
		&i.TableOrderMethodName,
		&i.SessionPaymentType,
	)
	return &i, err
}

const getOrders = `-- name: GetOrders :many
SELECT
    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
    0 + COALESCE(
        (
            SELECT cds.id
        FROM dg_pos_cash_drawer cd
        JOIN dg_pos_cash_drawer_sessions cds 
            ON cds.cash_drawer_id = cd.id
        WHERE cd.outlet_id = o.shop_id
          AND o.created_at >= cds.opened_at
          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
        ORDER BY cds.opened_at DESC
        LIMIT 1
        ),
        0
    ) AS cash_drawer_session_id,
    CASE WHEN payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
    dp.platform_id AS dp_id,
    dp.name AS delivery_platform_name,
    p.name AS platform_name,
    p.logo AS platform_logo,
    tbl.table_orderings_id AS table_orderings_id,
    tom.name AS table_order_method_name,
    tbl.name AS table_name
FROM
    ` + "`" + `order` + "`" + ` o
    LEFT JOIN dg_pos_tables tbl ON tbl.id = o.dgpos_table_id
    LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
    JOIN delivery_platform dp ON o.platform_id = dp.id
    JOIN platform p ON dp.platform_id = p.id
WHERE
    o.status != 'TEMP'
    AND dp.platform_id IN (/*SLICE:platform_ids*/?)
    AND (
        ? IS NULL
        OR o.status = ?
    )
    AND (
        ? IS NULL
        OR o.shop_id = ?
    )
    AND (
        ? IS NULL
        OR o.created_at >= ?
    )
    AND (
        ? IS NULL
        OR o.created_at <= ?
    )
ORDER BY
    CASE
        WHEN ? = 'asc' THEN o.id
    END ASC,
    CASE
        WHEN ? = 'desc' THEN o.id
    END DESC
`

type GetOrdersParams struct {
	PlatformIds    []sql.NullInt32 `json:"platform_ids"`
	ApplyStatus    interface{}     `json:"apply_status"`
	Status         string          `json:"status"`
	ApplyOutletID  interface{}     `json:"apply_outlet_id"`
	OutletID       int32           `json:"outlet_id"`
	ApplyStartDate interface{}     `json:"apply_start_date"`
	StartDate      sql.NullTime    `json:"start_date"`
	ApplyEndDate   interface{}     `json:"apply_end_date"`
	EndDate        sql.NullTime    `json:"end_date"`
	SortBy         interface{}     `json:"sort_by"`
}

type GetOrdersRow struct {
	Order                Order          `json:"order"`
	CashDrawerSessionID  int32          `json:"cash_drawer_session_id"`
	PaymentStatus        string         `json:"payment_status"`
	DpID                 sql.NullInt32  `json:"dp_id"`
	DeliveryPlatformName string         `json:"delivery_platform_name"`
	PlatformName         sql.NullString `json:"platform_name"`
	PlatformLogo         sql.NullString `json:"platform_logo"`
	TableOrderingsID     sql.NullInt64  `json:"table_orderings_id"`
	TableOrderMethodName sql.NullString `json:"table_order_method_name"`
	TableName            sql.NullString `json:"table_name"`
}

// GetOrders
//
//	SELECT
//	    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
//	    0 + COALESCE(
//	        (
//	            SELECT cds.id
//	        FROM dg_pos_cash_drawer cd
//	        JOIN dg_pos_cash_drawer_sessions cds
//	            ON cds.cash_drawer_id = cd.id
//	        WHERE cd.outlet_id = o.shop_id
//	          AND o.created_at >= cds.opened_at
//	          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
//	        ORDER BY cds.opened_at DESC
//	        LIMIT 1
//	        ),
//	        0
//	    ) AS cash_drawer_session_id,
//	    CASE WHEN payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
//	    dp.platform_id AS dp_id,
//	    dp.name AS delivery_platform_name,
//	    p.name AS platform_name,
//	    p.logo AS platform_logo,
//	    tbl.table_orderings_id AS table_orderings_id,
//	    tom.name AS table_order_method_name,
//	    tbl.name AS table_name
//	FROM
//	    `order` o
//	    LEFT JOIN dg_pos_tables tbl ON tbl.id = o.dgpos_table_id
//	    LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
//	    JOIN delivery_platform dp ON o.platform_id = dp.id
//	    JOIN platform p ON dp.platform_id = p.id
//	WHERE
//	    o.status != 'TEMP'
//	    AND dp.platform_id IN (/*SLICE:platform_ids*/?)
//	    AND (
//	        ? IS NULL
//	        OR o.status = ?
//	    )
//	    AND (
//	        ? IS NULL
//	        OR o.shop_id = ?
//	    )
//	    AND (
//	        ? IS NULL
//	        OR o.created_at >= ?
//	    )
//	    AND (
//	        ? IS NULL
//	        OR o.created_at <= ?
//	    )
//	ORDER BY
//	    CASE
//	        WHEN ? = 'asc' THEN o.id
//	    END ASC,
//	    CASE
//	        WHEN ? = 'desc' THEN o.id
//	    END DESC
func (q *Queries) GetOrders(ctx context.Context, arg *GetOrdersParams) ([]*GetOrdersRow, error) {
	query := getOrders
	var queryParams []interface{}
	if len(arg.PlatformIds) > 0 {
		for _, v := range arg.PlatformIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:platform_ids*/?", strings.Repeat(",?", len(arg.PlatformIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:platform_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.ApplyStatus)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.ApplyOutletID)
	queryParams = append(queryParams, arg.OutletID)
	queryParams = append(queryParams, arg.ApplyStartDate)
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.ApplyEndDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.SortBy)
	queryParams = append(queryParams, arg.SortBy)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOrdersRow{}
	for rows.Next() {
		var i GetOrdersRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.ShopID,
			&i.Order.PlatformID,
			&i.Order.RemoteOrderID,
			&i.Order.DisplayOrderID,
			&i.Order.DeliveryDateTime,
			&i.Order.TotalAmount,
			&i.Order.SubTotal,
			&i.Order.TotalFee,
			&i.Order.CampaignCode,
			&i.Order.Discount,
			&i.Order.VoucherDiscount,
			&i.Order.DiscountModeApplied,
			&i.Order.DiscountPercentageApplied,
			&i.Order.DiscountType,
			&i.Order.Vouchers,
			&i.Order.Status,
			&i.Order.CancelledReason,
			&i.Order.OrderTypeID,
			&i.Order.Note,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CustomerName,
			&i.Order.UserID,
			&i.Order.CustomerID,
			&i.Order.DeliveryLocationID,
			&i.Order.DeliveryTax,
			&i.Order.TaxID,
			&i.Order.ShippingMethod,
			&i.Order.ShippingTotal,
			&i.Order.ShippingTax,
			&i.Order.TotalTax,
			&i.Order.CashDue,
			&i.Order.Surcharge,
			&i.Order.ContactAccessCode,
			&i.Order.TestingOrder,
			&i.Order.CancelledByCustomer,
			&i.Order.PaymentMethod,
			&i.Order.PaymentMode,
			&i.Order.IsScheduled,
			&i.Order.IsTableOrder,
			&i.Order.Tip,
			&i.Order.TipPercentage,
			&i.Order.TableID,
			&i.Order.DgposTableID,
			&i.Order.TableOrderMethodID,
			&i.Order.DevicePlatform,
			&i.Order.OrderDelayed,
			&i.Order.UniqueOrderID,
			&i.Order.OrderSessionID,
			&i.CashDrawerSessionID,
			&i.PaymentStatus,
			&i.DpID,
			&i.DeliveryPlatformName,
			&i.PlatformName,
			&i.PlatformLogo,
			&i.TableOrderingsID,
			&i.TableOrderMethodName,
			&i.TableName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersForExport = `-- name: GetOrdersForExport :many
WITH order_card_transaction_payment_type AS (
    SELECT
        type_id,
        GROUP_CONCAT(payment_type) AS payment_types
    FROM
        order_transaction
    WHERE
        type = 'ORDER' AND transaction_mode = 'CARD'
    GROUP BY
        type_id
)
SELECT
    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
    0 + COALESCE(
        (
            SELECT cds.id
        FROM dg_pos_cash_drawer cd
        JOIN dg_pos_cash_drawer_sessions cds 
            ON cds.cash_drawer_id = cd.id
        WHERE cd.outlet_id = o.shop_id
          AND o.created_at >= cds.opened_at
          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
        ORDER BY cds.opened_at DESC
        LIMIT 1
        ),
        0
    ) AS cash_drawer_session_id,
    p.name AS platform_name,
    c.phone AS customer_contact_number,
    c.key_id_phone AS customer_key_id_contact_number,
    c.country_code AS customer_country_code,
    otp.payment_types AS payment_types
FROM
    ` + "`" + `order` + "`" + ` o
    JOIN delivery_platform dp ON o.platform_id = dp.id
    JOIN platform p ON dp.platform_id = p.id
    LEFT JOIN customers c ON o.customer_id = c.id
    LEFT JOIN order_card_transaction_payment_type otp ON otp.type_id = o.id
WHERE
    o.status != 'TEMP'
    AND p.id IN (/*SLICE:platform_ids*/?)
    AND (
        ? IS NULL
        OR o.status = ?
    )
    AND (
        ? IS NULL
        OR o.shop_id = ?
    )
    AND o.created_at >= ? AND o.created_at <= ?
GROUP BY o.id
ORDER BY
    CASE
        WHEN ? = 'asc' THEN o.id
    END ASC,
    CASE
        WHEN ? = 'desc' THEN o.id
    END DESC
`

type GetOrdersForExportParams struct {
	PlatformIds []uint64       `json:"platform_ids"`
	Status      sql.NullString `json:"status"`
	OutletID    sql.NullInt32  `json:"outlet_id"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	SortBy      interface{}    `json:"sort_by"`
}

type GetOrdersForExportRow struct {
	Order                      Order          `json:"order"`
	CashDrawerSessionID        int32          `json:"cash_drawer_session_id"`
	PlatformName               sql.NullString `json:"platform_name"`
	CustomerContactNumber      sql.NullString `json:"customer_contact_number"`
	CustomerKeyIDContactNumber sql.NullInt32  `json:"customer_key_id_contact_number"`
	CustomerCountryCode        sql.NullString `json:"customer_country_code"`
	PaymentTypes               sql.NullString `json:"payment_types"`
}

// GetOrdersForExport
//
//	WITH order_card_transaction_payment_type AS (
//	    SELECT
//	        type_id,
//	        GROUP_CONCAT(payment_type) AS payment_types
//	    FROM
//	        order_transaction
//	    WHERE
//	        type = 'ORDER' AND transaction_mode = 'CARD'
//	    GROUP BY
//	        type_id
//	)
//	SELECT
//	    o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
//	    0 + COALESCE(
//	        (
//	            SELECT cds.id
//	        FROM dg_pos_cash_drawer cd
//	        JOIN dg_pos_cash_drawer_sessions cds
//	            ON cds.cash_drawer_id = cd.id
//	        WHERE cd.outlet_id = o.shop_id
//	          AND o.created_at >= cds.opened_at
//	          AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
//	        ORDER BY cds.opened_at DESC
//	        LIMIT 1
//	        ),
//	        0
//	    ) AS cash_drawer_session_id,
//	    p.name AS platform_name,
//	    c.phone AS customer_contact_number,
//	    c.key_id_phone AS customer_key_id_contact_number,
//	    c.country_code AS customer_country_code,
//	    otp.payment_types AS payment_types
//	FROM
//	    `order` o
//	    JOIN delivery_platform dp ON o.platform_id = dp.id
//	    JOIN platform p ON dp.platform_id = p.id
//	    LEFT JOIN customers c ON o.customer_id = c.id
//	    LEFT JOIN order_card_transaction_payment_type otp ON otp.type_id = o.id
//	WHERE
//	    o.status != 'TEMP'
//	    AND p.id IN (/*SLICE:platform_ids*/?)
//	    AND (
//	        ? IS NULL
//	        OR o.status = ?
//	    )
//	    AND (
//	        ? IS NULL
//	        OR o.shop_id = ?
//	    )
//	    AND o.created_at >= ? AND o.created_at <= ?
//	GROUP BY o.id
//	ORDER BY
//	    CASE
//	        WHEN ? = 'asc' THEN o.id
//	    END ASC,
//	    CASE
//	        WHEN ? = 'desc' THEN o.id
//	    END DESC
func (q *Queries) GetOrdersForExport(ctx context.Context, arg *GetOrdersForExportParams) ([]*GetOrdersForExportRow, error) {
	query := getOrdersForExport
	var queryParams []interface{}
	if len(arg.PlatformIds) > 0 {
		for _, v := range arg.PlatformIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:platform_ids*/?", strings.Repeat(",?", len(arg.PlatformIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:platform_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.OutletID)
	queryParams = append(queryParams, arg.OutletID)
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.SortBy)
	queryParams = append(queryParams, arg.SortBy)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOrdersForExportRow{}
	for rows.Next() {
		var i GetOrdersForExportRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.ShopID,
			&i.Order.PlatformID,
			&i.Order.RemoteOrderID,
			&i.Order.DisplayOrderID,
			&i.Order.DeliveryDateTime,
			&i.Order.TotalAmount,
			&i.Order.SubTotal,
			&i.Order.TotalFee,
			&i.Order.CampaignCode,
			&i.Order.Discount,
			&i.Order.VoucherDiscount,
			&i.Order.DiscountModeApplied,
			&i.Order.DiscountPercentageApplied,
			&i.Order.DiscountType,
			&i.Order.Vouchers,
			&i.Order.Status,
			&i.Order.CancelledReason,
			&i.Order.OrderTypeID,
			&i.Order.Note,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CustomerName,
			&i.Order.UserID,
			&i.Order.CustomerID,
			&i.Order.DeliveryLocationID,
			&i.Order.DeliveryTax,
			&i.Order.TaxID,
			&i.Order.ShippingMethod,
			&i.Order.ShippingTotal,
			&i.Order.ShippingTax,
			&i.Order.TotalTax,
			&i.Order.CashDue,
			&i.Order.Surcharge,
			&i.Order.ContactAccessCode,
			&i.Order.TestingOrder,
			&i.Order.CancelledByCustomer,
			&i.Order.PaymentMethod,
			&i.Order.PaymentMode,
			&i.Order.IsScheduled,
			&i.Order.IsTableOrder,
			&i.Order.Tip,
			&i.Order.TipPercentage,
			&i.Order.TableID,
			&i.Order.DgposTableID,
			&i.Order.TableOrderMethodID,
			&i.Order.DevicePlatform,
			&i.Order.OrderDelayed,
			&i.Order.UniqueOrderID,
			&i.Order.OrderSessionID,
			&i.CashDrawerSessionID,
			&i.PlatformName,
			&i.CustomerContactNumber,
			&i.CustomerKeyIDContactNumber,
			&i.CustomerCountryCode,
			&i.PaymentTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    shop_id = ?,
    platform_id = ?,
    remote_order_id = ?,
    display_order_id = ?,
    delivery_date_time = ?,
    total_amount = ?,
    sub_total = ?,
    total_fee = ?,
    campaign_code = ?,
    discount = ?,
    voucher_discount = ?,
    discount_mode_applied = ?,
    discount_percentage_applied = ?,
    discount_type = ?,
    vouchers = ?,
    status = ?,
    cancelled_reason = ?,
    order_type_id = ?,
    note = ?,
    customer_name = ?,
    user_id = ?,
    customer_id = ?,
    delivery_location_id = ?,
    shipping_method = ?,
    shipping_total = ?,
    shipping_tax = ?,
    total_tax = ?,
    cash_due = ?,
    surcharge = ?,
    contact_access_code = ?,
    testing_order = ?,
    cancelled_by_customer = ?,
    payment_method = ?,
    is_scheduled = ?,
    is_table_order = ?,
    tip = ?,
    tip_percentage = ?,
    dgpos_table_id = ?,
    table_order_method_id = ?,
    device_platform = ?,
    order_delayed = ?,
    unique_order_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateOrderParams struct {
	ShopID                    int32          `json:"shop_id"`
	DeliveryPlatformID        int32          `json:"delivery_platform_id"`
	RemoteOrderID             string         `json:"remote_order_id"`
	DisplayOrderID            sql.NullString `json:"display_order_id"`
	DeliveryDateTime          time.Time      `json:"delivery_date_time"`
	TotalAmount               int32          `json:"total_amount"`
	SubTotal                  sql.NullInt32  `json:"sub_total"`
	TotalFee                  sql.NullInt32  `json:"total_fee"`
	CampaignCode              sql.NullString `json:"campaign_code"`
	Discount                  int32          `json:"discount"`
	VoucherDiscount           int32          `json:"voucher_discount"`
	DiscountModeApplied       sql.NullString `json:"discount_mode_applied"`
	DiscountPercentageApplied sql.NullInt32  `json:"discount_percentage_applied"`
	DiscountType              sql.NullString `json:"discount_type"`
	Vouchers                  sql.NullString `json:"vouchers"`
	Status                    string         `json:"status"`
	CancelledReason           sql.NullString `json:"cancelled_reason"`
	OrderTypeID               sql.NullInt32  `json:"order_type_id"`
	Note                      sql.NullString `json:"note"`
	CustomerName              sql.NullString `json:"customer_name"`
	UserID                    sql.NullInt32  `json:"user_id"`
	CustomerID                sql.NullInt32  `json:"customer_id"`
	DeliveryLocationID        sql.NullInt32  `json:"delivery_location_id"`
	ShippingMethod            sql.NullString `json:"shipping_method"`
	ShippingTotal             sql.NullString `json:"shipping_total"`
	ShippingTax               sql.NullString `json:"shipping_tax"`
	TotalTax                  sql.NullString `json:"total_tax"`
	CashDue                   string         `json:"cash_due"`
	Surcharge                 string         `json:"surcharge"`
	ContactAccessCode         sql.NullString `json:"contact_access_code"`
	TestingOrder              bool           `json:"testing_order"`
	CancelledByCustomer       bool           `json:"cancelled_by_customer"`
	PaymentMethod             sql.NullString `json:"payment_method"`
	IsScheduled               bool           `json:"is_scheduled"`
	IsTableOrder              bool           `json:"is_table_order"`
	Tip                       string         `json:"tip"`
	TipPercentage             string         `json:"tip_percentage"`
	DgposTableID              sql.NullInt32  `json:"dgpos_table_id"`
	TableOrderMethodID        sql.NullInt32  `json:"table_order_method_id"`
	DevicePlatform            sql.NullString `json:"device_platform"`
	OrderDelayed              bool           `json:"order_delayed"`
	UniqueOrderID             sql.NullString `json:"unique_order_id"`
	ID                        uint64         `json:"id"`
}

// UpdateOrder
//
//	UPDATE `order`
//	SET
//	    shop_id = ?,
//	    platform_id = ?,
//	    remote_order_id = ?,
//	    display_order_id = ?,
//	    delivery_date_time = ?,
//	    total_amount = ?,
//	    sub_total = ?,
//	    total_fee = ?,
//	    campaign_code = ?,
//	    discount = ?,
//	    voucher_discount = ?,
//	    discount_mode_applied = ?,
//	    discount_percentage_applied = ?,
//	    discount_type = ?,
//	    vouchers = ?,
//	    status = ?,
//	    cancelled_reason = ?,
//	    order_type_id = ?,
//	    note = ?,
//	    customer_name = ?,
//	    user_id = ?,
//	    customer_id = ?,
//	    delivery_location_id = ?,
//	    shipping_method = ?,
//	    shipping_total = ?,
//	    shipping_tax = ?,
//	    total_tax = ?,
//	    cash_due = ?,
//	    surcharge = ?,
//	    contact_access_code = ?,
//	    testing_order = ?,
//	    cancelled_by_customer = ?,
//	    payment_method = ?,
//	    is_scheduled = ?,
//	    is_table_order = ?,
//	    tip = ?,
//	    tip_percentage = ?,
//	    dgpos_table_id = ?,
//	    table_order_method_id = ?,
//	    device_platform = ?,
//	    order_delayed = ?,
//	    unique_order_id = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrder(ctx context.Context, arg *UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder,
		arg.ShopID,
		arg.DeliveryPlatformID,
		arg.RemoteOrderID,
		arg.DisplayOrderID,
		arg.DeliveryDateTime,
		arg.TotalAmount,
		arg.SubTotal,
		arg.TotalFee,
		arg.CampaignCode,
		arg.Discount,
		arg.VoucherDiscount,
		arg.DiscountModeApplied,
		arg.DiscountPercentageApplied,
		arg.DiscountType,
		arg.Vouchers,
		arg.Status,
		arg.CancelledReason,
		arg.OrderTypeID,
		arg.Note,
		arg.CustomerName,
		arg.UserID,
		arg.CustomerID,
		arg.DeliveryLocationID,
		arg.ShippingMethod,
		arg.ShippingTotal,
		arg.ShippingTax,
		arg.TotalTax,
		arg.CashDue,
		arg.Surcharge,
		arg.ContactAccessCode,
		arg.TestingOrder,
		arg.CancelledByCustomer,
		arg.PaymentMethod,
		arg.IsScheduled,
		arg.IsTableOrder,
		arg.Tip,
		arg.TipPercentage,
		arg.DgposTableID,
		arg.TableOrderMethodID,
		arg.DevicePlatform,
		arg.OrderDelayed,
		arg.UniqueOrderID,
		arg.ID,
	)
	return err
}

const updateOrderCancelledReason = `-- name: UpdateOrderCancelledReason :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    cancelled_reason = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateOrderCancelledReasonParams struct {
	CancelledReason sql.NullString `json:"cancelled_reason"`
	ID              uint64         `json:"id"`
}

// UpdateOrderCancelledReason
//
//	UPDATE `order`
//	SET
//	    cancelled_reason = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrderCancelledReason(ctx context.Context, arg *UpdateOrderCancelledReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderCancelledReason, arg.CancelledReason, arg.ID)
	return err
}

const updateOrderPaymentMode = `-- name: UpdateOrderPaymentMode :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    payment_mode = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateOrderPaymentModeParams struct {
	PaymentMode sql.NullString `json:"payment_mode"`
	ID          uint64         `json:"id"`
}

// UpdateOrderPaymentMode
//
//	UPDATE `order`
//	SET
//	    payment_mode = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrderPaymentMode(ctx context.Context, arg *UpdateOrderPaymentModeParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPaymentMode, arg.PaymentMode, arg.ID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
}

// UpdateOrderStatus
//
//	UPDATE `order`
//	SET
//	    status = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg *UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}

const updateOrderTableId = `-- name: UpdateOrderTableId :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    dgpos_table_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateOrderTableIdParams struct {
	DgposTableID sql.NullInt32 `json:"dgpos_table_id"`
	ID           uint64        `json:"id"`
}

// UpdateOrderTableId
//
//	UPDATE `order`
//	SET
//	    dgpos_table_id = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrderTableId(ctx context.Context, arg *UpdateOrderTableIdParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTableId, arg.DgposTableID, arg.ID)
	return err
}

const updateOrderUserID = `-- name: UpdateOrderUserID :exec
UPDATE ` + "`" + `order` + "`" + `
SET
    user_id = ?
WHERE
    id = ?
`

type UpdateOrderUserIDParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	ID     uint64        `json:"id"`
}

// UpdateOrderUserID
//
//	UPDATE `order`
//	SET
//	    user_id = ?
//	WHERE
//	    id = ?
func (q *Queries) UpdateOrderUserID(ctx context.Context, arg *UpdateOrderUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderUserID, arg.UserID, arg.ID)
	return err
}
