// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_query.sql

package db

import (
	"context"
	"database/sql"
)

const createDgPosPayments = `-- name: CreateDgPosPayments :exec
INSERT INTO
    ` + "`" + `dg_pos_payments` + "`" + ` (
        order_id,
        date_time,
        amount,
        cash,
        balance,
        card_transaction_token,
        transaction_id,
        refund_id,
        payment_method_id,
        payment_type,
        status,
        is_refund,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
`

type CreateDgPosPaymentsParams struct {
	OrderID              int32          `json:"order_id"`
	DateTime             sql.NullTime   `json:"date_time"`
	Amount               string         `json:"amount"`
	Cash                 string         `json:"cash"`
	Balance              string         `json:"balance"`
	CardTransactionToken sql.NullString `json:"card_transaction_token"`
	TransactionID        sql.NullInt64  `json:"transaction_id"`
	RefundID             sql.NullString `json:"refund_id"`
	PaymentMethodID      sql.NullString `json:"payment_method_id"`
	PaymentType          sql.NullString `json:"payment_type"`
	Status               sql.NullString `json:"status"`
	IsRefund             bool           `json:"is_refund"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// Active: 1748425317602@@127.0.0.1@3306@subway
//
//	INSERT INTO
//	    `dg_pos_payments` (
//	        order_id,
//	        date_time,
//	        amount,
//	        cash,
//	        balance,
//	        card_transaction_token,
//	        transaction_id,
//	        refund_id,
//	        payment_method_id,
//	        payment_type,
//	        status,
//	        is_refund,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?,
//	        ?
//	    )
func (q *Queries) CreateDgPosPayments(ctx context.Context, arg *CreateDgPosPaymentsParams) error {
	_, err := q.db.ExecContext(ctx, createDgPosPayments,
		arg.OrderID,
		arg.DateTime,
		arg.Amount,
		arg.Cash,
		arg.Balance,
		arg.CardTransactionToken,
		arg.TransactionID,
		arg.RefundID,
		arg.PaymentMethodID,
		arg.PaymentType,
		arg.Status,
		arg.IsRefund,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPayment = `-- name: CreatePayment :exec
INSERT INTO
    payments (
        order_id,
        date_time,
        amount,
        tax,
        discount,
        transaction_id,
        payment_method_id,
        status,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	OrderID         int32          `json:"order_id"`
	DateTime        sql.NullTime   `json:"date_time"`
	Amount          string         `json:"amount"`
	Tax             string         `json:"tax"`
	Discount        string         `json:"discount"`
	TransactionID   sql.NullString `json:"transaction_id"`
	PaymentMethodID sql.NullString `json:"payment_method_id"`
	Status          sql.NullString `json:"status"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

// CreatePayment
//
//	INSERT INTO
//	    payments (
//	        order_id,
//	        date_time,
//	        amount,
//	        tax,
//	        discount,
//	        transaction_id,
//	        payment_method_id,
//	        status,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreatePayment(ctx context.Context, arg *CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.OrderID,
		arg.DateTime,
		arg.Amount,
		arg.Tax,
		arg.Discount,
		arg.TransactionID,
		arg.PaymentMethodID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDgPosPayments = `-- name: DeleteDgPosPayments :exec
DELETE FROM ` + "`" + `dg_pos_payments` + "`" + ` WHERE order_id = ?
`

// DeleteDgPosPayments
//
//	DELETE FROM `dg_pos_payments` WHERE order_id = ?
func (q *Queries) DeleteDgPosPayments(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteDgPosPayments, orderID)
	return err
}

const deletePayments = `-- name: DeletePayments :exec
DELETE FROM ` + "`" + `payments` + "`" + ` WHERE order_id = ?
`

// DeletePayments
//
//	DELETE FROM `payments` WHERE order_id = ?
func (q *Queries) DeletePayments(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deletePayments, orderID)
	return err
}

const getDgPaymentStatusByOrderId = `-- name: GetDgPaymentStatusByOrderId :one
SELECT status, payment_type FROM dg_pos_payments WHERE order_id = ?
`

type GetDgPaymentStatusByOrderIdRow struct {
	Status      sql.NullString `json:"status"`
	PaymentType sql.NullString `json:"payment_type"`
}

// GetDgPaymentStatusByOrderId
//
//	SELECT status, payment_type FROM dg_pos_payments WHERE order_id = ?
func (q *Queries) GetDgPaymentStatusByOrderId(ctx context.Context, orderID int32) (*GetDgPaymentStatusByOrderIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDgPaymentStatusByOrderId, orderID)
	var i GetDgPaymentStatusByOrderIdRow
	err := row.Scan(&i.Status, &i.PaymentType)
	return &i, err
}

const getPaymentDetails = `-- name: GetPaymentDetails :many
SELECT id, order_id, date_time, amount, cash, balance, card_transaction_token, transaction_id, refund_id, payment_method_id, payment_type, status, is_refund, created_at, updated_at FROM dg_pos_payments WHERE order_id = ?
`

// GetPaymentDetails
//
//	SELECT id, order_id, date_time, amount, cash, balance, card_transaction_token, transaction_id, refund_id, payment_method_id, payment_type, status, is_refund, created_at, updated_at FROM dg_pos_payments WHERE order_id = ?
func (q *Queries) GetPaymentDetails(ctx context.Context, orderID int32) ([]*DgPosPayment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentDetails, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DgPosPayment{}
	for rows.Next() {
		var i DgPosPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DateTime,
			&i.Amount,
			&i.Cash,
			&i.Balance,
			&i.CardTransactionToken,
			&i.TransactionID,
			&i.RefundID,
			&i.PaymentMethodID,
			&i.PaymentType,
			&i.Status,
			&i.IsRefund,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebshopPaymentStatusByOrderId = `-- name: GetWebshopPaymentStatusByOrderId :one
SELECT payment_status, payment_type FROM webshop_payments WHERE order_id = ?
`

type GetWebshopPaymentStatusByOrderIdRow struct {
	PaymentStatus sql.NullString `json:"payment_status"`
	PaymentType   sql.NullString `json:"payment_type"`
}

// GetWebshopPaymentStatusByOrderId
//
//	SELECT payment_status, payment_type FROM webshop_payments WHERE order_id = ?
func (q *Queries) GetWebshopPaymentStatusByOrderId(ctx context.Context, orderID sql.NullInt32) (*GetWebshopPaymentStatusByOrderIdRow, error) {
	row := q.db.QueryRowContext(ctx, getWebshopPaymentStatusByOrderId, orderID)
	var i GetWebshopPaymentStatusByOrderIdRow
	err := row.Scan(&i.PaymentStatus, &i.PaymentType)
	return &i, err
}

const updateDgPosPayment = `-- name: UpdateDgPosPayment :exec
UPDATE ` + "`" + `dg_pos_payments` + "`" + `
SET
    amount = ?,
    cash = ?,
    balance = ?,
    transaction_id = ?,
    card_transaction_token = ?,
    payment_method_id = ?,
    status = ?,
    updated_at = ?
WHERE
    order_id = ?
`

type UpdateDgPosPaymentParams struct {
	Amount               string         `json:"amount"`
	Cash                 string         `json:"cash"`
	Balance              string         `json:"balance"`
	TransactionID        sql.NullInt64  `json:"transaction_id"`
	CardTransactionToken sql.NullString `json:"card_transaction_token"`
	PaymentMethodID      sql.NullString `json:"payment_method_id"`
	Status               sql.NullString `json:"status"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	OrderID              int32          `json:"order_id"`
}

// UpdateDgPosPayment
//
//	UPDATE `dg_pos_payments`
//	SET
//	    amount = ?,
//	    cash = ?,
//	    balance = ?,
//	    transaction_id = ?,
//	    card_transaction_token = ?,
//	    payment_method_id = ?,
//	    status = ?,
//	    updated_at = ?
//	WHERE
//	    order_id = ?
func (q *Queries) UpdateDgPosPayment(ctx context.Context, arg *UpdateDgPosPaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateDgPosPayment,
		arg.Amount,
		arg.Cash,
		arg.Balance,
		arg.TransactionID,
		arg.CardTransactionToken,
		arg.PaymentMethodID,
		arg.Status,
		arg.UpdatedAt,
		arg.OrderID,
	)
	return err
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE ` + "`" + `payments` + "`" + `
SET
    amount = ?,
    tax = ?,
    discount = ?,
    payment_method_id = ?,
    updated_at = ?
WHERE
    order_id = ?
`

type UpdatePaymentParams struct {
	Amount          string         `json:"amount"`
	Tax             string         `json:"tax"`
	Discount        string         `json:"discount"`
	PaymentMethodID sql.NullString `json:"payment_method_id"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	OrderID         int32          `json:"order_id"`
}

// UpdatePayment
//
//	UPDATE `payments`
//	SET
//	    amount = ?,
//	    tax = ?,
//	    discount = ?,
//	    payment_method_id = ?,
//	    updated_at = ?
//	WHERE
//	    order_id = ?
func (q *Queries) UpdatePayment(ctx context.Context, arg *UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment,
		arg.Amount,
		arg.Tax,
		arg.Discount,
		arg.PaymentMethodID,
		arg.UpdatedAt,
		arg.OrderID,
	)
	return err
}
