// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: printer_group_items.sql

package db

import (
	"context"
)

const getPrinterGroupsByItemID = `-- name: GetPrinterGroupsByItemID :many
SELECT 
  pg.id, pg.brand_id, pg.shop_id, pg.name, pg.description, pg.status, pg.created_at, pg.updated_at
FROM printer_group_item pgi
JOIN printer_group pg ON pg.id = pgi.printer_group_id
WHERE 
  pgi.item_id = ?
`

// GetPrinterGroupsByItemID
//
//	SELECT
//	  pg.id, pg.brand_id, pg.shop_id, pg.name, pg.description, pg.status, pg.created_at, pg.updated_at
//	FROM printer_group_item pgi
//	JOIN printer_group pg ON pg.id = pgi.printer_group_id
//	WHERE
//	  pgi.item_id = ?
func (q *Queries) GetPrinterGroupsByItemID(ctx context.Context, itemID int32) ([]*PrinterGroup, error) {
	rows, err := q.db.QueryContext(ctx, getPrinterGroupsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PrinterGroup{}
	for rows.Next() {
		var i PrinterGroup
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
