// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: printer_group.sql

package db

import (
	"context"
)

const getPrinterGroupsByShopID = `-- name: GetPrinterGroupsByShopID :many
SELECT id, brand_id, shop_id, name, description, status, created_at, updated_at FROM printer_group WHERE shop_id = ? AND brand_id = ?
`

type GetPrinterGroupsByShopIDParams struct {
	ShopID  int32 `json:"shop_id"`
	BrandID int32 `json:"brand_id"`
}

// GetPrinterGroupsByShopID
//
//	SELECT id, brand_id, shop_id, name, description, status, created_at, updated_at FROM printer_group WHERE shop_id = ? AND brand_id = ?
func (q *Queries) GetPrinterGroupsByShopID(ctx context.Context, arg *GetPrinterGroupsByShopIDParams) ([]*PrinterGroup, error) {
	rows, err := q.db.QueryContext(ctx, getPrinterGroupsByShopID, arg.ShopID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PrinterGroup{}
	for rows.Next() {
		var i PrinterGroup
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
