// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	//AddOngoingOrderForTable
	//
	//  INSERT INTO
	//      dg_pos_tables_ongoing_orders (table_id, order_id)
	//  VALUES (?, ?)
	AddOngoingOrderForTable(ctx context.Context, arg *AddOngoingOrderForTableParams) error
	//CloseCashDrawerSession
	//
	//  UPDATE dg_pos_cash_drawer_sessions
	//  SET
	//      closed_at = CURRENT_TIMESTAMP,
	//      session_ended_user_id = ?,
	//      closing_balance_expected = ?,
	//      difference = ?,
	//      total_in_amount = ?,
	//      total_out_amount = ?,
	//      total_sales_amount = ?,
	//      total_other_sales_amount = ?,
	//      total_refund_amount = ?,
	//      status = 'CLOSED',
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	CloseCashDrawerSession(ctx context.Context, arg *CloseCashDrawerSessionParams) error
	//CreateActivityLog
	//
	//  INSERT INTO
	//      `dg_pos_user_activities` (
	//          brand_id,
	//          shop_id,
	//          log_name,
	//          description,
	//          event,
	//          subject_id,
	//          causer_id
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?)
	CreateActivityLog(ctx context.Context, arg *CreateActivityLogParams) error
	//CreateCashDrawer
	//
	//  INSERT INTO
	//      dg_pos_cash_drawer (
	//          outlet_id,
	//          is_active,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateCashDrawer(ctx context.Context, arg *CreateCashDrawerParams) error
	//CreateCashDrawerSession
	//
	//  INSERT INTO
	//      dg_pos_cash_drawer_sessions (
	//          cash_drawer_id,
	//          session_started_user_id,
	//          opened_at,
	//          opening_balance,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateCashDrawerSession(ctx context.Context, arg *CreateCashDrawerSessionParams) error
	//CreateCustomer
	//
	//  INSERT INTO
	//      customers (
	//          first_name,
	//          hashed_first_name,
	//          key_id_first_name,
	//          last_name,
	//          hashed_last_name,
	//          key_id_last_name,
	//          phone,
	//          hashed_phone,
	//          key_id_phone,
	//          country_code,
	//          `type`,
	//          device_platform,
	//          status,
	//          account_brand,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateCustomer(ctx context.Context, arg *CreateCustomerParams) (int64, error)
	//CreateCustomerVoucher
	//
	//  INSERT INTO
	//      customer_vouchers (
	//          customer_id,
	//          voucher_id,
	//          is_used,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	CreateCustomerVoucher(ctx context.Context, arg *CreateCustomerVoucherParams) error
	//CreateDeliveryLocation
	//
	//  INSERT INTO
	//      delivery_location (
	//          customer_id,
	//          label,
	//          flat_no,
	//          house_no,
	//          address_line_1,
	//          address_line_2,
	//          latitude,
	//          longitude,
	//          city,
	//          landmark,
	//          postal_code,
	//          default_address,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateDeliveryLocation(ctx context.Context, arg *CreateDeliveryLocationParams) (int64, error)
	//CreateDgPosOrderLocation
	//
	//  INSERT INTO
	//      `dg_pos_order_location` (
	//          order_id,
	//          first_name,
	//          last_name,
	//          email,
	//          country_code,
	//          country,
	//          phone,
	//          flat_no,
	//          house_no,
	//          address_line_1,
	//          address_line_2,
	//          city,
	//          landmark,
	//          postcode,
	//          latitude,
	//          longitude,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateDgPosOrderLocation(ctx context.Context, arg *CreateDgPosOrderLocationParams) error
	// Active: 1748425317602@@127.0.0.1@3306@subway
	//
	//  INSERT INTO
	//      `dg_pos_payments` (
	//          order_id,
	//          date_time,
	//          amount,
	//          cash,
	//          balance,
	//          card_transaction_token,
	//          transaction_id,
	//          refund_id,
	//          payment_method_id,
	//          payment_type,
	//          status,
	//          is_refund,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?
	//      )
	CreateDgPosPayments(ctx context.Context, arg *CreateDgPosPaymentsParams) error
	//CreateLogin
	//
	//  INSERT INTO dg_pos_user_shifts (user_id, login) VALUES (?, ?)
	CreateLogin(ctx context.Context, arg *CreateLoginParams) error
	//CreateOrder
	//
	//  INSERT INTO
	//      `order` (
	//          shop_id,
	//          platform_id,
	//          remote_order_id,
	//          display_order_id,
	//          delivery_date_time,
	//          total_amount,
	//          sub_total,
	//          total_fee,
	//          campaign_code,
	//          discount,
	//          voucher_discount,
	//          discount_mode_applied,
	//          discount_percentage_applied,
	//          discount_type,
	//          vouchers,
	//          status,
	//          cancelled_reason,
	//          order_type_id,
	//          note,
	//          customer_name,
	//          user_id,
	//          customer_id,
	//          delivery_location_id,
	//          shipping_method,
	//          shipping_total,
	//          shipping_tax,
	//          tax_id,
	//          delivery_tax,
	//          total_tax,
	//          cash_due,
	//          surcharge,
	//          contact_access_code,
	//          testing_order,
	//          cancelled_by_customer,
	//          payment_method,
	//          payment_mode,
	//          is_scheduled,
	//          is_table_order,
	//          tip,
	//          tip_percentage,
	//          dgpos_table_id,
	//          table_order_method_id,
	//          device_platform,
	//          order_delayed,
	//          unique_order_id,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateOrder(ctx context.Context, arg *CreateOrderParams) (int64, error)
	//CreateOrderCommission
	//
	//  INSERT INTO
	//      order_commission (
	//          order_tmp_id,
	//          order_id,
	//          commission,
	//          reference,
	//          report_id,
	//          status,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	CreateOrderCommission(ctx context.Context, arg *CreateOrderCommissionParams) error
	//CreateOrderItem
	//
	//  INSERT INTO
	//      order_items (
	//          order_id,
	//          item_id,
	//          quantity,
	//          price_per_item,
	//          total,
	//          original_price,
	//          is_sale,
	//          discount_amount,
	//          status,
	//          created_at,
	//          updated_at,
	//          item_name,
	//          category_name,
	//          modifiers,
	//          tax,
	//          note
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?
	//      )
	CreateOrderItem(ctx context.Context, arg *CreateOrderItemParams) (int64, error)
	//CreateOrderItemModifier
	//
	//  INSERT INTO
	//      order_item_modifier (
	//          order_item_id,
	//          parent_modifier_id,
	//          sub_parent_modifier_id,
	//          modifier_id,
	//          modifier_group_name,
	//          modifier_option_id,
	//          modifier_option_name,
	//          amount,
	//          quantity,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?
	//      )
	CreateOrderItemModifier(ctx context.Context, arg *CreateOrderItemModifierParams) (int64, error)
	//CreateOrderItemTax
	//
	//  INSERT INTO
	//      order_item_tax (
	//          order_id,
	//          order_item_id,
	//          order_item_modifier_id,
	//          item_price,
	//          tax_id,
	//          tax_profile_id,
	//          tax_rule_id,
	//          amount,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	CreateOrderItemTax(ctx context.Context, arg *CreateOrderItemTaxParams) error
	//CreateOrderRefund
	//
	//  INSERT INTO
	//      order_refund (
	//          type_id,
	//          `type`,
	//          transaction_id,
	//          refund_amount,
	//          refund_mode,
	//          reason,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	CreateOrderRefund(ctx context.Context, arg *CreateOrderRefundParams) (int64, error)
	//CreateOrderShopFee
	//
	//  INSERT INTO
	//      order_shop_fee (
	//          order_id,
	//          shop_fee_id,
	//          amount,
	//          shop_fee_tax,
	//          tax_id,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?)
	CreateOrderShopFee(ctx context.Context, arg *CreateOrderShopFeeParams) error
	//CreateOrderStatusTimestamps
	//
	//  INSERT INTO
	//      dg_pos_order_status_timestamps (
	//          order_id,
	//          queue,
	//          preparing,
	//          ready,
	//          served,
	//          delivered,
	//          completed,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	CreateOrderStatusTimestamps(ctx context.Context, arg *CreateOrderStatusTimestampsParams) error
	//CreateOrderTransaction
	//
	//  INSERT INTO
	//      order_transaction (
	//          type_id,
	//          `type`,
	//          transaction_type,
	//          transaction_mode,
	//          transaction_amount,
	//          payment_type,
	//          platform,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          "DG_POS",
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	CreateOrderTransaction(ctx context.Context, arg *CreateOrderTransactionParams) (int64, error)
	//CreatePayment
	//
	//  INSERT INTO
	//      payments (
	//          order_id,
	//          date_time,
	//          amount,
	//          tax,
	//          discount,
	//          transaction_id,
	//          payment_method_id,
	//          status,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	CreatePayment(ctx context.Context, arg *CreatePaymentParams) error
	//CreateRefreshToken
	//
	//  INSERT INTO pos_refresh_tokens (user_id, token, expires_at) VALUES (?, ?, ?)
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) error
	//DeleteCustomerVoucher
	//
	//  DELETE FROM customer_vouchers
	//  WHERE
	//      customer_id = ?
	//      AND voucher_id = ?
	DeleteCustomerVoucher(ctx context.Context, arg *DeleteCustomerVoucherParams) error
	//DeleteDeliveryLocation
	//
	//  DELETE FROM delivery_location WHERE id = ?
	DeleteDeliveryLocation(ctx context.Context, id uint64) error
	//DeleteDgPosPayments
	//
	//  DELETE FROM `dg_pos_payments` WHERE order_id = ?
	DeleteDgPosPayments(ctx context.Context, orderID int32) error
	//DeleteDgPosTmpPayment
	//
	//  DELETE FROM dg_pos_tmp_payments WHERE type_id = ?
	DeleteDgPosTmpPayment(ctx context.Context, typeID string) error
	//DeleteOrderCommission
	//
	//  DELETE FROM order_commission WHERE order_id = ?
	DeleteOrderCommission(ctx context.Context, orderID int64) error
	//DeleteOrderItemModifiers
	//
	//  DELETE FROM order_item_modifier
	//  WHERE
	//      order_item_id IN (/*SLICE:order_item_ids*/?)
	DeleteOrderItemModifiers(ctx context.Context, orderItemIds []int32) error
	//DeleteOrderItemTaxes
	//
	//  DELETE FROM order_item_tax WHERE order_id = ?
	DeleteOrderItemTaxes(ctx context.Context, orderID int32) error
	//DeleteOrderItems
	//
	//  DELETE FROM order_items WHERE order_id = ?
	DeleteOrderItems(ctx context.Context, orderID int32) error
	//DeleteOrderShopFees
	//
	//  DELETE FROM order_shop_fee WHERE order_id = ?
	DeleteOrderShopFees(ctx context.Context, orderID int32) error
	//DeleteOrderTaxes
	//
	//  DELETE FROM order_taxes WHERE order_id = ?
	DeleteOrderTaxes(ctx context.Context, orderID int32) error
	//DeletePayments
	//
	//  DELETE FROM `payments` WHERE order_id = ?
	DeletePayments(ctx context.Context, orderID int32) error
	//DeleteRefreshToken
	//
	//  DELETE FROM pos_refresh_tokens WHERE user_id = ?
	DeleteRefreshToken(ctx context.Context, userID uint64) error
	//GetActiveShift
	//
	//  SELECT id, user_id, login, logout, created_at, updated_at
	//  FROM dg_pos_user_shifts
	//  WHERE
	//      user_id = ?
	//      AND logout IS NULL
	GetActiveShift(ctx context.Context, userID int64) (*DgPosUserShift, error)
	//GetAllOrderItemIDs
	//
	//  SELECT id FROM order_items WHERE order_id = ?
	GetAllOrderItemIDs(ctx context.Context, orderID int32) ([]uint64, error)
	//GetAvailableOrderItems
	//
	//  SELECT id, entity_id, delivery_platform_id, external_item_id, created_at, updated_at, plu, price, item_name, allergies, available, available_from
	//  FROM entity_delivery_platform
	//  WHERE
	//      entity_id IN (/*SLICE:item_ids*/?)
	//      AND delivery_platform_id = ?
	//      AND available = 1
	GetAvailableOrderItems(ctx context.Context, arg *GetAvailableOrderItemsParams) ([]*EntityDeliveryPlatform, error)
	//GetCashDrawerByOutletID
	//
	//  SELECT id, outlet_id, is_active, created_at, updated_at FROM dg_pos_cash_drawer WHERE is_active AND outlet_id = ?
	GetCashDrawerByOutletID(ctx context.Context, outletID uint64) (*DgPosCashDrawer, error)
	//GetCashDrawerSessionByID
	//
	//  SELECT
	//      cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
	//      u_started.name AS session_started_user_name,
	//      u_started.key_id_name AS session_started_user_key_id_name,
	//      u_started.last_name AS session_started_user_last_name,
	//      u_started.key_id_last_name AS session_started_user_key_id_last_name,
	//      u_ended.name AS session_ended_user_name,
	//      u_ended.key_id_name AS session_ended_user_key_id_name,
	//      u_ended.last_name AS session_ended_user_last_name,
	//      u_ended.key_id_last_name AS session_ended_user_key_id_last_name
	//  FROM
	//      dg_pos_cash_drawer_sessions cds
	//      JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
	//      JOIN users u_started ON u_started.id = cds.session_started_user_id
	//      JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
	//  WHERE
	//      cds.id = ?
	GetCashDrawerSessionByID(ctx context.Context, id uint64) (*GetCashDrawerSessionByIDRow, error)
	//GetCashDrawerSessionSummary
	//
	//  SELECT
	//      cds.id AS cash_drawer_session_id,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'PAY_IN' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_in_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'PAY_OUT' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_out_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'SALE' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_sales_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'OTHER_SALES' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_other_sales_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_cash_sale_cash_refund_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'CARD_SALE_CASH_REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_card_sale_cash_refund_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_pos_card_sale_cash_refund_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_other_refund_amount,
	//      0 + SUM(
	//          CASE
	//              WHEN cdm.movement_type = 'REFUND'
	//              OR cdm.movement_type = 'CARD_SALE_CASH_REFUND'
	//              OR cdm.movement_type = 'POS_CARD_SALE_CASH_REFUND'
	//              OR cdm.movement_type = 'OTHER_REFUND' THEN cdm.amount
	//              ELSE 0
	//          END
	//      ) AS total_refund_amount,
	//      0 + COALESCE(SUM(cdm.amount), 0) AS total_movements,
	//      cds.opening_balance + COALESCE(SUM(cdm.amount), 0) AS expected_balance,
	//      cds.closing_balance_counted - (
	//          cds.opening_balance + COALESCE(SUM(cdm.amount), 0)
	//      ) AS difference
	//  FROM
	//      dg_pos_cash_drawer_sessions cds
	//      LEFT JOIN dg_pos_cash_movements cdm ON cds.id = cdm.cash_drawer_session_id
	//  WHERE
	//      cds.id = ?
	//  GROUP BY
	//      cds.id
	GetCashDrawerSessionSummary(ctx context.Context, id uint64) (*GetCashDrawerSessionSummaryRow, error)
	//GetCashDrawerSessions
	//
	//  SELECT
	//      cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
	//      u_started.name AS session_started_user_name,
	//      u_started.key_id_name AS session_started_user_key_id_name,
	//      u_started.last_name AS session_started_user_last_name,
	//      u_started.key_id_last_name AS session_started_user_key_id_last_name,
	//      u_ended.name AS session_ended_user_name,
	//      u_ended.key_id_name AS session_ended_user_key_id_name,
	//      u_ended.last_name AS session_ended_user_last_name,
	//      u_ended.key_id_last_name AS session_ended_user_key_id_last_name
	//  FROM
	//      dg_pos_cash_drawer_sessions cds
	//      JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
	//      JOIN users u_started ON u_started.id = cds.session_started_user_id
	//      JOIN users u_ended ON u_ended.id = cds.session_ended_user_id
	//  WHERE
	//      cd.outlet_id = ?
	//      AND cds.status = 'CLOSED'
	//      AND cds.created_at >= ?
	//      AND cds.created_at <= ?
	GetCashDrawerSessions(ctx context.Context, arg *GetCashDrawerSessionsParams) ([]*GetCashDrawerSessionsRow, error)
	//GetCashDrawerTransactionHistory
	//
	//  SELECT
	//      cd.id AS cash_drawer_id,
	//      cds.id AS cash_drawer_session_id,
	//      cm.id AS cash_movement_id,
	//      cm.created_at,
	//      cm.movement_type,
	//      cm.note,
	//      cm.amount,
	//      users.name AS user_name,
	//      users.key_id_name AS user_key_id_name,
	//      users.last_name AS user_last_name,
	//      users.key_id_last_name AS user_key_id_last_name
	//  FROM
	//      dg_pos_cash_movements cm
	//      LEFT JOIN users ON users.id = cm.user_id
	//      JOIN dg_pos_cash_drawer_sessions cds ON cds.id = cm.cash_drawer_session_id
	//      JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
	//  WHERE
	//      cd.outlet_id = ?
	//      AND cm.movement_type IN ('PAY_IN', 'PAY_OUT')
	//      AND cm.created_at >= ?
	//      AND cm.created_at <= ?
	//  ORDER BY cm.id DESC
	GetCashDrawerTransactionHistory(ctx context.Context, arg *GetCashDrawerTransactionHistoryParams) ([]*GetCashDrawerTransactionHistoryRow, error)
	//GetCashMovement
	//
	//  SELECT cm.id, cm.cash_drawer_session_id, cm.movement_type, cm.amount, cm.note, cm.user_id, cm.created_at, cm.updated_at
	//  FROM dg_pos_cash_movements cm
	//  WHERE
	//      cash_drawer_session_id = ?
	//      AND movement_type = ?
	GetCashMovement(ctx context.Context, arg *GetCashMovementParams) (*DgPosCashMovement, error)
	//GetCashPaidPosOrderIdsWithinTimeRange
	//
	//  SELECT
	//      DISTINCT odr.id
	//  FROM
	//      `order` odr
	//      JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
	//  WHERE
	//      -- ot.transaction_type = 'SALE'
	//      ot.transaction_mode = 'CASH'
	//      AND odr.status IN ('COMPLETED', 'CANCELED')
	//      AND odr.device_platform = 'dg_pos'
	//      AND odr.testing_order = 0
	//      AND odr.created_at >= ?
	//      AND odr.created_at <= ?
	//      AND odr.shop_id = ?
	GetCashPaidPosOrderIdsWithinTimeRange(ctx context.Context, arg *GetCashPaidPosOrderIdsWithinTimeRangeParams) ([]uint64, error)
	//GetCashTransactionsByOrderID
	//
	//  SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
	//  FROM order_transaction
	//  WHERE
	//      type_id = ?
	//      AND transaction_mode = 'CASH'
	GetCashTransactionsByOrderID(ctx context.Context, typeID uint64) ([]*OrderTransaction, error)
	//GetCategoryItemsByMenuIdAndShopId
	//
	//  SELECT id, main_menu_id, submenu_id, platform_id, delivery_platform_id, status, outlet_id, day, `from`, `to`, menu, category_ids, created_at, updated_at
	//  FROM webshop_menu wm
	//  WHERE
	//      wm.status = 1
	//      AND wm.main_menu_id = ?
	//      AND wm.submenu_id IN (
	//          SELECT menu_id
	//          FROM main_menu_menu mmm
	//          WHERE
	//              mmm.main_menu_id = ?
	//      )
	//      AND wm.delivery_platform_id = ?
	//      AND wm.outlet_id = ?
	//      AND (
	//          ? IS NULL
	//          OR wm.day = ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR wm.from <= ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR wm.to >= ?
	//      )
	//  ORDER BY wm.id DESC
	GetCategoryItemsByMenuIdAndShopId(ctx context.Context, arg *GetCategoryItemsByMenuIdAndShopIdParams) (*WebshopMenu, error)
	//GetCommissionAmount
	//
	//  SELECT order_commission
	//  FROM shop_brand_details
	//  WHERE
	//      shop_id = ?
	//      AND webshop_brand_id = ?
	GetCommissionAmount(ctx context.Context, arg *GetCommissionAmountParams) (string, error)
	//GetCustomerAddresses
	//
	//  SELECT id, customer_id, label, flat_no, house_no, address_line_1, address_line_2, latitude, longitude, city, landmark, postal_code, default_address, created_at, updated_at
	//  FROM delivery_location
	//  WHERE
	//      customer_id = ?
	//      AND label IS NOT NULL
	//      AND address_line_1 IS NOT NULL
	GetCustomerAddresses(ctx context.Context, customerID int32) ([]*DeliveryLocation, error)
	//GetCustomerByID
	//
	//  SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real FROM customers WHERE id = ?
	GetCustomerByID(ctx context.Context, id uint64) (*Customer, error)
	//GetCustomerByPhone
	//
	//  SELECT id, source, order_id, first_order_offer_eligible, subscribe_to_promotion_emails, promotion_emails_subscribed_at, first_name, hashed_first_name, key_id_first_name, last_name, hashed_last_name, key_id_last_name, account_brand, dob, hashed_dob, key_id_dob, address_1, hashed_address_1, key_id_address_1, address_2, hashed_address_2, key_id_address_2, email, hashed_email, key_id_email, password, apple_id, phone, hashed_phone, key_id_phone, country_code, city, hashed_city, key_id_city, state, hashed_state, key_id_state, postcode, hashed_postcode, key_id_postcode, country, hashed_country, key_id_country, remote_id, type, created_at, updated_at, latitude, hashed_latitude, key_id_latitude, longitude, hashed_longitude, key_id_longitude, reset_token, remember_token, stripe_id, contact_access_code, otp, status, password_reset_code, password_reset_code_status, address_type, notes, expo_token, notification_permission_given_at, device_id, device_platform, last_active_time, last_active_device, deleted_at, is_real
	//  FROM customers
	//  WHERE
	//      hashed_phone IN (
	//          /*SLICE:phone_number_formats*/?
	//      )
	//      AND country_code = ?
	GetCustomerByPhone(ctx context.Context, arg *GetCustomerByPhoneParams) (*Customer, error)
	// SELECT
	//     o.*,
	//     cds.id AS cash_drawer_session_id,
	//     p.name AS platform_name,
	//     c.phone AS customer_contact_number,
	//     c.key_id_phone AS customer_key_id_contact_number,
	//     c.country_code AS customer_country_code
	// FROM
	//      `order` o
	//     JOIN delivery_platform dp ON o.platform_id = dp.id
	//     JOIN platform p ON dp.platform_id = p.id
	//     JOIN dg_pos_cash_drawer cd ON cd.outlet_id = o.shop_id
	//     JOIN dg_pos_cash_drawer_sessions cds ON cds.cash_drawer_id = cd.id
	//     AND o.created_at BETWEEN cds.opened_at AND COALESCE(cds.closed_at, NOW())
	//     LEFT JOIN customers c ON o.customer_id = c.id
	// WHERE
	//     o.status != 'TEMP'
	//     AND p.id IN (9,6)
	//     AND o.status = 'COMPLETED'
	//     AND o.shop_id = 2
	//     AND o.created_at BETWEEN '2025-11-03 00:00:00' AND '2025-11-03 23:59:59'
	// ORDER BY
	//     o.id DESC;
	//
	//
	//  SELECT
	//      o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
	//      dp.platform_id AS dp_id,
	//      p.name AS platform_name,
	//      p.logo AS platform_logo
	//  FROM
	//      `order` o
	//      LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
	//      LEFT JOIN platform p ON dp.platform_id = p.id
	//  WHERE
	//      o.customer_id = ?
	GetCustomerOrders(ctx context.Context, customerID sql.NullInt32) ([]*GetCustomerOrdersRow, error)
	//GetCustomersWithAddresses
	//
	//  SELECT c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real, dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at
	//  FROM
	//      customers c
	//      LEFT JOIN delivery_location dl ON c.id = dl.customer_id
	//  WHERE
	//      c.deleted_at IS NULL
	//  ORDER BY c.id DESC
	GetCustomersWithAddresses(ctx context.Context) ([]*GetCustomersWithAddressesRow, error)
	//GetDeliveryPlatform
	//
	//  SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name, wb.brand_name AS brand_name
	//  FROM delivery_platform dp
	//  LEFT JOIN platform p ON dp.platform_id = p.id
	//  LEFT JOIN webshop_brand wb ON dp.webshop_brand_id = wb.id
	//  WHERE
	//      outlet_id = ?
	//      AND webshop_brand_id = ?
	//      AND platform_id = ?
	GetDeliveryPlatform(ctx context.Context, arg *GetDeliveryPlatformParams) (*GetDeliveryPlatformRow, error)
	//GetDeliveryPlatformById
	//
	//  SELECT id, platform_id, name, webshop_brand_id, api_url, auth_url, api_parameters, logo, status, created_at, updated_at, outlet_code, site_id, branch_id, access_token, primary_color, can_upload, auto_accepting, franchise_id, outlet_id, menu_id, menu_upload_status, store_status, available_from, tender_types, is_master, parent_platform, prep_time, own_driver, menu_published_at, webshop_setup_status, has_cash_payment, has_card_payment, selected_menu, deleted_at FROM delivery_platform WHERE id = ?
	GetDeliveryPlatformById(ctx context.Context, id uint64) (*DeliveryPlatform, error)
	//GetDeliveryPlatforms
	//
	//  SELECT dp.id, dp.platform_id, dp.name, dp.webshop_brand_id, dp.api_url, dp.auth_url, dp.api_parameters, dp.logo, dp.status, dp.created_at, dp.updated_at, dp.outlet_code, dp.site_id, dp.branch_id, dp.access_token, dp.primary_color, dp.can_upload, dp.auto_accepting, dp.franchise_id, dp.outlet_id, dp.menu_id, dp.menu_upload_status, dp.store_status, dp.available_from, dp.tender_types, dp.is_master, dp.parent_platform, dp.prep_time, dp.own_driver, dp.menu_published_at, dp.webshop_setup_status, dp.has_cash_payment, dp.has_card_payment, dp.selected_menu, dp.deleted_at, p.name AS platform_name
	//  FROM
	//      delivery_platform dp
	//      LEFT JOIN platform p ON dp.platform_id = p.id
	//      WHERE
	//          (
	//              ? IS NULL
	//              OR dp.outlet_id = ?
	//          )
	//          AND (
	//              ? IS NULL
	//              OR dp.webshop_brand_id = ?
	//          )
	GetDeliveryPlatforms(ctx context.Context, arg *GetDeliveryPlatformsParams) ([]*GetDeliveryPlatformsRow, error)
	//GetDgPaymentStatusByOrderId
	//
	//  SELECT status, payment_type FROM dg_pos_payments WHERE order_id = ?
	GetDgPaymentStatusByOrderId(ctx context.Context, orderID int32) (*GetDgPaymentStatusByOrderIdRow, error)
	//GetDgPosOrderLocation
	//
	//  SELECT id, order_id, first_name, last_name, email, country_code, country, phone, flat_no, house_no, address_line_1, address_line_2, city, landmark, postcode, latitude, longitude, created_at, updated_at FROM dg_pos_order_location WHERE order_id = ?
	GetDgPosOrderLocation(ctx context.Context, orderID int32) (*DgPosOrderLocation, error)
	//GetDgPosTableName
	//
	//  SELECT name FROM dg_pos_tables WHERE id = ?
	GetDgPosTableName(ctx context.Context, id uint64) (string, error)
	//GetDgPosTableNameByTableOrderingsID
	//
	//  SELECT name FROM dg_pos_tables WHERE table_orderings_id = ?
	GetDgPosTableNameByTableOrderingsID(ctx context.Context, tableOrderingsID sql.NullInt64) (string, error)
	//GetDgPosTmpPayments
	//
	//  SELECT id, type_id, type, payment_amount, payment_mode, transaction_id, created_at, updated_at FROM dg_pos_tmp_payments WHERE type_id = ?
	GetDgPosTmpPayments(ctx context.Context, typeID string) ([]*DgPosTmpPayment, error)
	//GetEncryptionKeys
	//
	//  SELECT id, `key`, created_at, updated_at FROM encryption_keys
	GetEncryptionKeys(ctx context.Context) ([]*EncryptionKey, error)
	//GetGuestCustomer
	//
	//  SELECT id, first_name, hashed_first_name, last_name, hashed_last_name
	//  FROM customers
	//  WHERE
	//      hashed_email = 'b2dba1e9d647b1efa184223800731c18ddae80ddf38ca728b138ef59ff872be0'
	GetGuestCustomer(ctx context.Context) (*GetGuestCustomerRow, error)
	// -- name: GetSalesCashAmountPOS :one
	// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS sales_total
	// FROM
	//     `order` odr
	//     JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
	// WHERE
	//     ot.transaction_type = 'SALE'
	//     AND ot.transaction_mode = 'CASH'
	//     AND odr.status IN ('COMPLETED', 'CANCELED')
	//     AND odr.device_platform = 'dg_pos'
	//     AND odr.testing_order = 0
	//     AND odr.created_at >= sqlc.arg (from_created_at)
	//     AND odr.created_at <= sqlc.arg (to_created_at)
	//     AND odr.shop_id = ?;
	// -- name: GetRefundCashAmountPOS :one
	// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
	// FROM
	//     `order` odr
	//     JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
	// WHERE
	//     ot.transaction_type = 'REFUND'
	//     AND ot.transaction_mode = 'CASH'
	//     AND odr.status IN ('COMPLETED', 'CANCELED')
	//     AND odr.device_platform = 'dg_pos'
	//     AND odr.testing_order = 0
	//     AND odr.created_at >= sqlc.arg (from_created_at)
	//     AND odr.created_at <= sqlc.arg (to_created_at)
	//     AND odr.shop_id = ?;
	// -- name: GetCashSaleCashRefundAmountPOS :one
	// WITH cash_paid_orders_within_time_range AS (
	//     SELECT odr.id
	//     FROM
	//         `order` odr
	//         JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
	//     WHERE
	//         ot.transaction_type = 'SALE'
	//         AND ot.transaction_mode = 'CASH'
	//         AND odr.status IN ('COMPLETED', 'CANCELED')
	//         AND odr.device_platform = 'dg_pos'
	//         AND odr.testing_order = 0
	//         AND odr.created_at >= sqlc.arg (from_created_at)
	//         AND odr.created_at <= sqlc.arg (to_created_at)
	//         AND odr.shop_id = ?
	// )
	// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
	// FROM order_transaction ot
	//     JOIN cash_paid_orders_within_time_range cpo ON cpo.id = ot.type_id
	// WHERE
	//     ot.transaction_type = 'REFUND'
	//     AND ot.transaction_mode = 'CASH';
	// -- name: GetRefundCardAmount :one
	// WITH card_paid_orders_within_time_range AS (
	//     SELECT odr.id
	//     FROM
	//         `order` odr
	//         JOIN order_transaction ot ON odr.id = ot.type_id AND ot.`type` = 'ORDER'
	//     WHERE
	//         ot.transaction_type = 'SALE'
	//         AND ot.transaction_mode = 'CARD'
	//         AND odr.status IN ('COMPLETED', 'CANCELED')
	//         AND odr.testing_order = 0
	//         AND odr.created_at >= sqlc.arg (from_created_at)
	//         AND odr.created_at <= sqlc.arg (to_created_at)
	//         AND odr.shop_id = ?
	// )
	// SELECT 0 + COALESCE(SUM(ot.transaction_amount), 0) AS refund_total
	// FROM order_transaction ot
	//     JOIN card_paid_orders_within_time_range cpo ON cpo.id = ot.type_id
	// WHERE
	//     ot.transaction_type = 'REFUND'
	//     AND ot.transaction_mode = 'CASH';
	//
	//
	//
	//
	//
	//  SELECT id, shop_id, platform_id, remote_order_id, display_order_id, delivery_date_time, total_amount, sub_total, total_fee, campaign_code, discount, voucher_discount, discount_mode_applied, discount_percentage_applied, discount_type, vouchers, status, cancelled_reason, order_type_id, note, created_at, updated_at, customer_name, user_id, customer_id, delivery_location_id, delivery_tax, tax_id, shipping_method, shipping_total, shipping_tax, total_tax, cash_due, surcharge, contact_access_code, testing_order, cancelled_by_customer, payment_method, payment_mode, is_scheduled, is_table_order, tip, tip_percentage, table_id, dgpos_table_id, table_order_method_id, device_platform, order_delayed, unique_order_id, order_session_id
	//  FROM `order` odr
	//  WHERE
	//      odr.status NOT IN(
	//          'COMPLETED',
	//          'CANCELED',
	//          'MISSED',
	//          'DENIED',
	//          'CREATED',
	//          'TEMP'
	//      )
	//      AND odr.created_at BETWEEN ? AND ?
	//      AND odr.shop_id = ?
	GetIncompleteOrders(ctx context.Context, arg *GetIncompleteOrdersParams) ([]*Order, error)
	//GetLatestEncryptionKey
	//
	//  SELECT id, `key`, created_at, updated_at FROM encryption_keys ORDER BY id DESC LIMIT 1
	GetLatestEncryptionKey(ctx context.Context) (*EncryptionKey, error)
	//GetLatestRefundByOrderID
	//
	//  SELECT
	//    ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
	//    orf.id AS refund_id,
	//    orf.reason
	//  FROM order_refund orf
	//  JOIN order_transaction ot ON ot.id = orf.transaction_id
	//  WHERE
	//    orf.type_id = ?
	//    AND orf.`type` = 'ORDER'
	//  ORDER BY id DESC
	//  LIMIT 1
	GetLatestRefundByOrderID(ctx context.Context, typeID uint64) (*GetLatestRefundByOrderIDRow, error)
	//GetLatestReportServiceToken
	//
	//  SELECT id, dns, server_client_id, server_client_secret, bearer_token, expire_in, created_at, updated_at FROM report_service ORDER BY id DESC LIMIT 1
	GetLatestReportServiceToken(ctx context.Context) (*ReportService, error)
	//GetMobileAppOrdersCount
	//
	//  SELECT COUNT(o.id) AS mobile_app_orders
	//  FROM `order` o
	//  WHERE
	//      o.device_platform = 'mobile'
	//      AND o.customer_id = ?
	GetMobileAppOrdersCount(ctx context.Context, customerID sql.NullInt32) (int64, error)
	//GetMobileAppReservationsCount
	//
	//  SELECT COUNT(tr.id) AS mobile_app_reservations
	//  FROM table_reservation tr
	//  WHERE
	//      tr.user_type = 'CUSTOMER'
	//      AND tr.device_platform = 'mobile'
	//      AND tr.customer_id = ?
	GetMobileAppReservationsCount(ctx context.Context, customerID sql.NullInt32) (int64, error)
	//   0 + SUM(
	//         CASE
	//             WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
	//                 WHEN ot.transaction_type = 'SALE' THEN 1
	//                 WHEN ot.transaction_type = 'REFUND' THEN -1
	//                 ELSE 0
	//             END
	//             ELSE 0
	//         END
	//     ) AS net_cash_sales,
	//     0 + SUM(
	//         CASE
	//             WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
	//                 WHEN ot.transaction_type = 'SALE' THEN 1
	//                 WHEN ot.transaction_type = 'REFUND' THEN -1
	//                 ELSE 0
	//             END
	//             ELSE 0
	//         END
	//     ) AS net_card_sales,
	//
	//  SELECT
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
	//              WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
	//              ELSE 0
	//          END
	//      ) AS net_sales
	//  FROM
	//      order_transaction ot
	//  WHERE
	//      ot.type_id = ?
	//      AND ot.`type` = 'ORDER'
	//  GROUP BY
	//      ot.type_id
	GetNetCashAndCardSaleByOrderID(ctx context.Context, typeID uint64) (int32, error)
	//GetOngoingOrdersForTable
	//
	//  SELECT
	//      too.id, too.table_id, too.order_id, too.created_at, too.updated_at,
	//      o.display_order_id,
	//      o.status,
	//      o.total_amount,
	//      o.customer_name,
	//      o.order_session_id,
	//      o.is_table_order,
	//      o.shipping_method,
	//      o.created_at,
	//      CASE WHEN o.payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
	//      p.logo AS platform_logo,
	//      tom.name AS table_order_method_name
	//  FROM dg_pos_tables_ongoing_orders too
	//  JOIN `order` o ON too.order_id = o.id
	//  JOIN delivery_platform dp ON o.platform_id = dp.id
	//  JOIN platform p ON dp.platform_id = p.id
	//  LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
	//  WHERE too.table_id = ?
	GetOngoingOrdersForTable(ctx context.Context, tableID uint64) ([]*GetOngoingOrdersForTableRow, error)
	//GetOpenCashDrawerSession
	//
	//  SELECT
	//      cds.id, cds.cash_drawer_id, cds.session_started_user_id, cds.session_ended_user_id, cds.opened_at, cds.opening_balance, cds.closed_at, cds.closing_balance_counted, cds.closing_balance_expected, cds.difference, cds.total_in_amount, cds.total_out_amount, cds.total_sales_amount, cds.total_other_sales_amount, cds.total_refund_amount, cds.status, cds.created_at, cds.updated_at,
	//      u_started.name AS session_started_user_name,
	//      u_started.key_id_name AS session_started_user_key_id_name,
	//      u_started.last_name AS session_started_user_last_name,
	//      u_started.key_id_last_name AS session_started_user_key_id_last_name
	//  FROM
	//      dg_pos_cash_drawer_sessions cds
	//      JOIN dg_pos_cash_drawer cd ON cd.id = cds.cash_drawer_id
	//      JOIN users u_started ON u_started.id = cds.session_started_user_id
	//  WHERE
	//      cd.outlet_id = ?
	//      AND cds.status = 'OPEN'
	//  LIMIT 1
	GetOpenCashDrawerSession(ctx context.Context, outletID uint64) (*GetOpenCashDrawerSessionRow, error)
	//GetOrderById
	//
	//  SELECT
	//      o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
	//      t.code AS delivery_tax_code,
	//      t.rate AS delivery_tax_rate,
	//      0 + COALESCE(
	//          (
	//              SELECT cds.id
	//          FROM dg_pos_cash_drawer cd
	//          JOIN dg_pos_cash_drawer_sessions cds
	//              ON cds.cash_drawer_id = cd.id
	//          WHERE cd.outlet_id = o.shop_id
	//            AND o.created_at >= cds.opened_at
	//            AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
	//          ORDER BY cds.opened_at DESC
	//          LIMIT 1
	//          ),
	//          0
	//      ) AS shift_id,
	//      dp.name AS dp_name,
	//      p.id AS platform_id,
	//      p.name AS platform_name,
	//      p.logo AS platform_logo,
	//      tom.name AS table_order_method_name,
	//      os.payment_type AS session_payment_type
	//  FROM
	//      `order` o
	//      LEFT JOIN delivery_platform dp ON o.platform_id = dp.id
	//      LEFT JOIN platform p ON dp.platform_id = p.id
	//      LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
	//      LEFT JOIN taxes_main t ON t.id = o.tax_id
	//      LEFT JOIN order_session os ON os.id = o.order_session_id
	//  WHERE
	//      o.id = ?
	GetOrderById(ctx context.Context, id uint64) (*GetOrderByIdRow, error)
	//GetOrderCommission
	//
	//  SELECT id, order_tmp_id, order_id, commission, reference, report_id, status, created_at, updated_at FROM order_commission WHERE order_id = ?
	GetOrderCommission(ctx context.Context, orderID int64) (*OrderCommission, error)
	//GetOrderItemTaxes
	//
	//  SELECT
	//    oit.id, oit.order_id, oit.order_item_id, oit.order_item_modifier_id, oit.item_price, oit.tax_id, oit.tax_profile_id, oit.tax_rule_id, oit.amount, oit.created_at, oit.updated_at,
	//    t.code AS tax_code,
	//    t.rate AS tax_rate
	//  FROM
	//    order_item_tax oit
	//    JOIN taxes_main t ON t.id = oit.tax_id
	//  WHERE
	//    oit.order_id = ?
	GetOrderItemTaxes(ctx context.Context, orderID int32) ([]*GetOrderItemTaxesRow, error)
	//GetOrderItemsByOrderID
	//
	//  select
	//    oi.id, oi.order_id, oi.item_id, oi.quantity, oi.price_per_item, oi.total, oi.original_price, oi.is_sale, oi.discount_amount, oi.status, oi.created_at, oi.updated_at, oi.item_name, oi.category_name, oi.modifiers, oi.tax, oi.note,
	//    oit.id as order_item_tax_id,
	//    oit.tax_profile_id as tax_profile_id,
	//    oit.tax_rule_id as tax_rule_id,
	//    oit.tax_id as tax_id,
	//    oit.amount as tax_amount,
	//    t.code as tax_code,
	//    t.rate as tax_rate
	//  from order_items oi
	//  left join order_item_tax oit on oit.order_item_id = oi.id and oit.order_item_modifier_id is null
	//  left join taxes_main t on t.id = oit.tax_id
	//  where oi.order_id = ?
	GetOrderItemsByOrderID(ctx context.Context, orderID int32) ([]*GetOrderItemsByOrderIDRow, error)
	//GetOrderReceiver
	//
	//  SELECT dl.id, dl.customer_id, dl.label, dl.flat_no, dl.house_no, dl.address_line_1, dl.address_line_2, dl.latitude, dl.longitude, dl.city, dl.landmark, dl.postal_code, dl.default_address, dl.created_at, dl.updated_at, c.id, c.source, c.order_id, c.first_order_offer_eligible, c.subscribe_to_promotion_emails, c.promotion_emails_subscribed_at, c.first_name, c.hashed_first_name, c.key_id_first_name, c.last_name, c.hashed_last_name, c.key_id_last_name, c.account_brand, c.dob, c.hashed_dob, c.key_id_dob, c.address_1, c.hashed_address_1, c.key_id_address_1, c.address_2, c.hashed_address_2, c.key_id_address_2, c.email, c.hashed_email, c.key_id_email, c.password, c.apple_id, c.phone, c.hashed_phone, c.key_id_phone, c.country_code, c.city, c.hashed_city, c.key_id_city, c.state, c.hashed_state, c.key_id_state, c.postcode, c.hashed_postcode, c.key_id_postcode, c.country, c.hashed_country, c.key_id_country, c.remote_id, c.type, c.created_at, c.updated_at, c.latitude, c.hashed_latitude, c.key_id_latitude, c.longitude, c.hashed_longitude, c.key_id_longitude, c.reset_token, c.remember_token, c.stripe_id, c.contact_access_code, c.otp, c.status, c.password_reset_code, c.password_reset_code_status, c.address_type, c.notes, c.expo_token, c.notification_permission_given_at, c.device_id, c.device_platform, c.last_active_time, c.last_active_device, c.deleted_at, c.is_real
	//  FROM
	//      delivery_location dl
	//      JOIN customers c ON dl.customer_id = c.id
	//  WHERE
	//      dl.id = ?
	//      AND customer_id = ?
	GetOrderReceiver(ctx context.Context, arg *GetOrderReceiverParams) (*GetOrderReceiverRow, error)
	//GetOrderSalesTaxes
	//
	//  SELECT id, order_id, tax_rate, tax_code, tax_amount, taxable_amount, type, created_at, updated_at FROM order_taxes WHERE order_id = ? AND type = 'SALE'
	GetOrderSalesTaxes(ctx context.Context, orderID int32) ([]*OrderTax, error)
	//GetOrderStatusTimestamps
	//
	//  SELECT id, order_id, queue, preparing, ready, served, delivered, completed, created_at, updated_at FROM dg_pos_order_status_timestamps WHERE order_id = ?
	GetOrderStatusTimestamps(ctx context.Context, orderID int32) (*DgPosOrderStatusTimestamp, error)
	//GetOrderTransactionByRefundID
	//
	//  SELECT ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at, orf.reason, orf.transaction_id AS refund_transaction_id
	//  FROM
	//      order_transaction ot
	//      LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
	//  WHERE
	//      orf.id = ?
	GetOrderTransactionByRefundID(ctx context.Context, id uint64) (*GetOrderTransactionByRefundIDRow, error)
	//GetOrderTransactions
	//
	//  SELECT
	//      ot.id, ot.type_id, ot.type, ot.transaction_type, ot.transaction_amount, ot.transaction_mode, ot.payment_type, ot.platform, ot.created_at, ot.updated_at,
	//      orf.id AS refund_id,
	//      orf.reason,
	//      orf.transaction_id AS refund_transaction_id
	//  FROM
	//      order_transaction ot
	//      LEFT JOIN order_refund orf ON orf.transaction_id = ot.id
	//  WHERE
	//      ot.type_id = ?
	//  ORDER BY ot.id DESC
	GetOrderTransactions(ctx context.Context, typeID uint64) ([]*GetOrderTransactionsRow, error)
	//GetOrders
	//
	//  SELECT
	//      o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
	//      0 + COALESCE(
	//          (
	//              SELECT cds.id
	//          FROM dg_pos_cash_drawer cd
	//          JOIN dg_pos_cash_drawer_sessions cds
	//              ON cds.cash_drawer_id = cd.id
	//          WHERE cd.outlet_id = o.shop_id
	//            AND o.created_at >= cds.opened_at
	//            AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
	//          ORDER BY cds.opened_at DESC
	//          LIMIT 1
	//          ),
	//          0
	//      ) AS cash_drawer_session_id,
	//      CASE WHEN payment_mode IS NULL THEN 'UNPAID' ELSE 'PAID' END AS payment_status,
	//      dp.platform_id AS dp_id,
	//      dp.name AS delivery_platform_name,
	//      p.name AS platform_name,
	//      p.logo AS platform_logo,
	//      tbl.table_orderings_id AS table_orderings_id,
	//      tom.name AS table_order_method_name,
	//      tbl.name AS table_name
	//  FROM
	//      `order` o
	//      LEFT JOIN dg_pos_tables tbl ON tbl.id = o.dgpos_table_id
	//      LEFT JOIN table_order_methods tom ON tom.id = o.table_order_method_id
	//      JOIN delivery_platform dp ON o.platform_id = dp.id
	//      JOIN platform p ON dp.platform_id = p.id
	//  WHERE
	//      o.status != 'TEMP'
	//      AND dp.platform_id IN (/*SLICE:platform_ids*/?)
	//      AND (
	//          ? IS NULL
	//          OR o.status = ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR o.shop_id = ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR o.created_at >= ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR o.created_at <= ?
	//      )
	//  ORDER BY
	//      CASE
	//          WHEN ? = 'asc' THEN o.id
	//      END ASC,
	//      CASE
	//          WHEN ? = 'desc' THEN o.id
	//      END DESC
	GetOrders(ctx context.Context, arg *GetOrdersParams) ([]*GetOrdersRow, error)
	//GetOrdersForExport
	//
	//  WITH order_card_transaction_payment_type AS (
	//      SELECT
	//          type_id,
	//          GROUP_CONCAT(payment_type) AS payment_types
	//      FROM
	//          order_transaction
	//      WHERE
	//          type = 'ORDER' AND transaction_mode = 'CARD'
	//      GROUP BY
	//          type_id
	//  )
	//  SELECT
	//      o.id, o.shop_id, o.platform_id, o.remote_order_id, o.display_order_id, o.delivery_date_time, o.total_amount, o.sub_total, o.total_fee, o.campaign_code, o.discount, o.voucher_discount, o.discount_mode_applied, o.discount_percentage_applied, o.discount_type, o.vouchers, o.status, o.cancelled_reason, o.order_type_id, o.note, o.created_at, o.updated_at, o.customer_name, o.user_id, o.customer_id, o.delivery_location_id, o.delivery_tax, o.tax_id, o.shipping_method, o.shipping_total, o.shipping_tax, o.total_tax, o.cash_due, o.surcharge, o.contact_access_code, o.testing_order, o.cancelled_by_customer, o.payment_method, o.payment_mode, o.is_scheduled, o.is_table_order, o.tip, o.tip_percentage, o.table_id, o.dgpos_table_id, o.table_order_method_id, o.device_platform, o.order_delayed, o.unique_order_id, o.order_session_id,
	//      0 + COALESCE(
	//          (
	//              SELECT cds.id
	//          FROM dg_pos_cash_drawer cd
	//          JOIN dg_pos_cash_drawer_sessions cds
	//              ON cds.cash_drawer_id = cd.id
	//          WHERE cd.outlet_id = o.shop_id
	//            AND o.created_at >= cds.opened_at
	//            AND (cds.closed_at IS NULL OR o.created_at < cds.closed_at)
	//          ORDER BY cds.opened_at DESC
	//          LIMIT 1
	//          ),
	//          0
	//      ) AS cash_drawer_session_id,
	//      p.name AS platform_name,
	//      c.phone AS customer_contact_number,
	//      c.key_id_phone AS customer_key_id_contact_number,
	//      c.country_code AS customer_country_code,
	//      otp.payment_types AS payment_types
	//  FROM
	//      `order` o
	//      JOIN delivery_platform dp ON o.platform_id = dp.id
	//      JOIN platform p ON dp.platform_id = p.id
	//      LEFT JOIN customers c ON o.customer_id = c.id
	//      LEFT JOIN order_card_transaction_payment_type otp ON otp.type_id = o.id
	//  WHERE
	//      o.status != 'TEMP'
	//      AND p.id IN (/*SLICE:platform_ids*/?)
	//      AND (
	//          ? IS NULL
	//          OR o.status = ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR o.shop_id = ?
	//      )
	//      AND o.created_at >= ? AND o.created_at <= ?
	//  GROUP BY o.id
	//  ORDER BY
	//      CASE
	//          WHEN ? = 'asc' THEN o.id
	//      END ASC,
	//      CASE
	//          WHEN ? = 'desc' THEN o.id
	//      END DESC
	GetOrdersForExport(ctx context.Context, arg *GetOrdersForExportParams) ([]*GetOrdersForExportRow, error)
	//GetPaymentDetails
	//
	//  SELECT id, order_id, date_time, amount, cash, balance, card_transaction_token, transaction_id, refund_id, payment_method_id, payment_type, status, is_refund, created_at, updated_at FROM dg_pos_payments WHERE order_id = ?
	GetPaymentDetails(ctx context.Context, orderID int32) ([]*DgPosPayment, error)
	//GetPrinterGroupsByItemID
	//
	//  SELECT
	//    pg.id, pg.brand_id, pg.shop_id, pg.name, pg.description, pg.status, pg.created_at, pg.updated_at
	//  FROM printer_group_item pgi
	//  JOIN printer_group pg ON pg.id = pgi.printer_group_id
	//  WHERE
	//    pgi.item_id = ?
	GetPrinterGroupsByItemID(ctx context.Context, itemID int32) ([]*PrinterGroup, error)
	//GetPrinterGroupsByShopID
	//
	//  SELECT id, brand_id, shop_id, name, description, status, created_at, updated_at FROM printer_group WHERE shop_id = ? AND brand_id = ?
	GetPrinterGroupsByShopID(ctx context.Context, arg *GetPrinterGroupsByShopIDParams) ([]*PrinterGroup, error)
	//GetRefreshToken
	//
	//  SELECT user_id, token, expires_at, created_at, updated_at FROM pos_refresh_tokens WHERE user_id = ?
	GetRefreshToken(ctx context.Context, userID uint64) (*PosRefreshToken, error)
	//GetRefundByID
	//
	//  SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE id = ?
	GetRefundByID(ctx context.Context, id uint64) (*OrderRefund, error)
	//GetRefundsByOrderID
	//
	//  SELECT id, type_id, type, transaction_id, refund_amount, refund_mode, reason, created_at, updated_at FROM order_refund WHERE type_id = ? AND `type` = 'ORDER'
	GetRefundsByOrderID(ctx context.Context, typeID uint64) ([]*OrderRefund, error)
	//GetSaleTransactionByOrderID
	//
	//  SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at
	//  FROM order_transaction
	//  WHERE
	//      type_id = ?
	//      AND transaction_type = 'SALE'
	//      AND `type` = 'ORDER'
	GetSaleTransactionByOrderID(ctx context.Context, typeID uint64) (*OrderTransaction, error)
	//GetSalesAndRefundByTypeID
	//
	//  SELECT
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
	//                  WHEN ot.transaction_type = 'SALE' THEN 1
	//                  ELSE 0
	//              END
	//              ELSE 0
	//          END
	//      ) AS cash_sale,
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
	//                  WHEN ot.transaction_type = 'SALE' THEN 1
	//                  ELSE 0
	//              END
	//              ELSE 0
	//          END
	//      ) AS card_sale,
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
	//                  WHEN ot.transaction_type = 'REFUND' THEN 1
	//                  ELSE 0
	//              END
	//              ELSE 0
	//          END
	//      ) AS cash_refund,
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
	//                  WHEN ot.transaction_type = 'REFUND' THEN 1
	//                  ELSE 0
	//              END
	//              ELSE 0
	//          END
	//      ) AS card_refund,
	//      0 + SUM(
	//          CASE
	//              WHEN ot.transaction_type = 'SALE' THEN ot.transaction_amount
	//              WHEN ot.transaction_type = 'REFUND' THEN -ot.transaction_amount
	//              ELSE 0
	//          END
	//      ) AS net_sale
	//  FROM order_transaction ot
	//  WHERE
	//      ot.type_id = ?
	//  GROUP BY
	//      ot.type_id
	GetSalesAndRefundByTypeID(ctx context.Context, typeID uint64) (*GetSalesAndRefundByTypeIDRow, error)
	//GetShiftInfoByShop
	//
	//  WITH
	//      orders_and_net_totals AS (
	//          SELECT
	//              odr.id,
	//              odr.user_id,
	//              0 + SUM(
	//                  CASE
	//                      WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
	//                          WHEN ot.transaction_type = 'SALE' THEN 1
	//                          WHEN ot.transaction_type = 'REFUND' THEN -1
	//                          ELSE 0
	//                      END
	//                      ELSE 0
	//                  END
	//              ) AS cash_sales_total,
	//              0 + SUM(
	//                  CASE
	//                      WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
	//                          WHEN ot.transaction_type = 'SALE' THEN 1
	//                          WHEN ot.transaction_type = 'REFUND' THEN -1
	//                          ELSE 0
	//                      END
	//                      ELSE 0
	//                  END
	//              ) AS card_sales_total,
	//              0 + SUM(
	//                  ot.transaction_amount * CASE
	//                      WHEN ot.transaction_type = 'SALE' THEN 1
	//                      WHEN ot.transaction_type = 'REFUND' THEN -1
	//                      ELSE 0
	//                  END
	//              ) AS net_sales
	//          FROM
	//              `order` odr
	//              JOIN order_transaction ot ON odr.id = ot.type_id
	//          WHERE
	//              odr.status IN ('COMPLETED', 'CANCELED')
	//              AND odr.device_platform = 'dg_pos'
	//              AND odr.created_at >= ?
	//              AND odr.created_at <= ?
	//              AND odr.shop_id = ?
	//          GROUP BY
	//              odr.id
	//      )
	//  SELECT
	//      user_id,
	//      COUNT(id) AS orders_created,
	//      0 + SUM(cash_sales_total) AS total_cash_sales,
	//      0 + SUM(card_sales_total) AS total_card_sales,
	//      0 + SUM(net_sales) AS total_net_sales
	//  FROM orders_and_net_totals
	//  GROUP BY
	//      user_id
	GetShiftInfoByShop(ctx context.Context, arg *GetShiftInfoByShopParams) ([]*GetShiftInfoByShopRow, error)
	//GetShiftInfoByUser
	//
	//  WITH
	//      orders_and_net_totals AS (
	//          SELECT
	//              odr.id,
	//              odr.user_id,
	//              odr.created_at,
	//              0 + SUM(
	//                  CASE
	//                      WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
	//                          WHEN ot.transaction_type = 'SALE' THEN 1
	//                          WHEN ot.transaction_type = 'REFUND' THEN -1
	//                          ELSE 0
	//                      END
	//                      ELSE 0
	//                  END
	//              ) AS cash_sales_total,
	//              0 + SUM(
	//                  CASE
	//                      WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
	//                          WHEN ot.transaction_type = 'SALE' THEN 1
	//                          WHEN ot.transaction_type = 'REFUND' THEN -1
	//                          ELSE 0
	//                      END
	//                      ELSE 0
	//                  END
	//              ) AS card_sales_total,
	//              0 + SUM(
	//                  ot.transaction_amount * CASE
	//                      WHEN ot.transaction_type = 'SALE' THEN 1
	//                      WHEN ot.transaction_type = 'REFUND' THEN -1
	//                      ELSE 0
	//                  END
	//              ) AS net_sales
	//          FROM
	//              `order` odr
	//              JOIN order_transaction ot ON odr.id = ot.type_id
	//          WHERE
	//              odr.status IN ('COMPLETED', 'CANCELED')
	//              AND odr.device_platform = 'dg_pos'
	//              AND odr.created_at >= ?
	//              AND odr.created_at <= ?
	//              AND odr.shop_id = ?
	//              AND odr.user_id = ?
	//          GROUP BY
	//              odr.id
	//      )
	//  SELECT
	//      shifts.id AS shift_id,
	//      shifts.login,
	//      shifts.logout,
	//      COUNT(odr.id) AS orders_created,
	//      0 + SUM(odr.cash_sales_total) AS cash_total,
	//      0 + SUM(odr.card_sales_total) AS card_total,
	//      0 + SUM(odr.net_sales) AS total
	//  FROM
	//      orders_and_net_totals odr
	//      JOIN dg_pos_user_shifts shifts ON shifts.user_id = odr.user_id
	//      AND odr.created_at BETWEEN shifts.login AND COALESCE(shifts.logout, NOW())
	//  GROUP BY
	//      shifts.id
	GetShiftInfoByUser(ctx context.Context, arg *GetShiftInfoByUserParams) ([]*GetShiftInfoByUserRow, error)
	//GetShopByCode
	//
	//  SELECT id, name, franchise_id, code, email, address, branch, contact_no, business_reg_no, socket_code, status, order_status, last_updated_menu, last_pos_synced, service_availability, created_at, updated_at, minimum_amount_for_free_delivery, minimum_amount_for_delivery, one_time_promotion_value, one_time_promotion_spend_amount, latitude, longitude, google_location_url, one_time_promotion_type, maximum_promotion_value, selected_menu, is_default, country_code, timezone, currency, currency_code, tax_mode, tax_reg_no, print_receipt_accept, number_of_receipt, delivery_platform_enable, run_test_order, has_cash_payment, has_card_payment, tbl_commission_per_head, tbl_ref_commission_per_head, transfer_destination, delivergate_account, printer_status, deleted_at, has_collection_points, collection_points_note, user_interaction_status, interaction_timeout FROM shop WHERE code = ?
	GetShopByCode(ctx context.Context, code string) (*Shop, error)
	//GetShopByID
	//
	//  SELECT id, name, franchise_id, code, email, address, branch, contact_no, business_reg_no, socket_code, status, order_status, last_updated_menu, last_pos_synced, service_availability, created_at, updated_at, minimum_amount_for_free_delivery, minimum_amount_for_delivery, one_time_promotion_value, one_time_promotion_spend_amount, latitude, longitude, google_location_url, one_time_promotion_type, maximum_promotion_value, selected_menu, is_default, country_code, timezone, currency, currency_code, tax_mode, tax_reg_no, print_receipt_accept, number_of_receipt, delivery_platform_enable, run_test_order, has_cash_payment, has_card_payment, tbl_commission_per_head, tbl_ref_commission_per_head, transfer_destination, delivergate_account, printer_status, deleted_at, has_collection_points, collection_points_note, user_interaction_status, interaction_timeout FROM shop WHERE id = ?
	GetShopByID(ctx context.Context, id uint64) (*Shop, error)
	//GetShopConfig
	//
	//  SELECT id, shop_id, brand_id, terminal_id, config_type, data, created_at, updated_at
	//  FROM dg_pos_shop_config
	//  WHERE
	//      config_type = ?
	//      AND shop_id = ?
	//      AND brand_id = ?
	//      AND terminal_id = ?
	GetShopConfig(ctx context.Context, arg *GetShopConfigParams) (*DgPosShopConfig, error)
	//GetShopFees
	//
	//  SELECT
	//    sf.id, sf.shop_id, sf.webshop_brand_id, sf.platform, sf.type, sf.fee_name, sf.fee, sf.fee_type, sf.status, sf.tax_id, sf.mandatory, sf.created_at, sf.updated_at, sf.deleted_at,
	//    t.id, t.name, t.code, t.description, t.rate, t.status, t.created_at, t.updated_at
	//  FROM shop_fee sf
	//  LEFT JOIN taxes_main t ON t.id = sf.tax_id
	//  WHERE
	//      sf.shop_id = ?
	//      AND sf.webshop_brand_id = ?
	//      AND sf.status = 1
	//      AND sf.platform = 'DG_POS'
	GetShopFees(ctx context.Context, arg *GetShopFeesParams) ([]*GetShopFeesRow, error)
	//GetShopFeesByOrderID
	//
	//  SELECT
	//    osf.id, osf.order_id, osf.shop_fee_id, osf.amount, osf.shop_fee_tax, osf.tax_id, osf.created_at, osf.updated_at,
	//    t.code AS tax_code,
	//    t.rate AS tax_rate,
	//    sf.fee_name,
	//    sf.fee_type
	//  FROM
	//    order_shop_fee osf
	//    JOIN shop_fee sf ON sf.id = osf.shop_fee_id
	//    LEFT JOIN taxes_main t ON t.id = osf.tax_id
	//  WHERE
	//    osf.order_id = ?
	GetShopFeesByOrderID(ctx context.Context, orderID int32) ([]*GetShopFeesByOrderIDRow, error)
	//GetShopLogo
	//
	//  SELECT brand_logo FROM basic_details WHERE webshop_brand_id = ?
	GetShopLogo(ctx context.Context, webshopBrandID int32) (string, error)
	//GetTableByID
	//
	//  SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE id = ? LIMIT 1
	GetTableByID(ctx context.Context, id uint64) (*DgPosTable, error)
	//GetTableByTableOrderingsID
	//
	//  SELECT id, table_orderings_id, shop_id, brand_id, name, description, seat_count, status, ongoing_order_id, created_at, updated_at FROM dg_pos_tables WHERE table_orderings_id = ? LIMIT 1
	GetTableByTableOrderingsID(ctx context.Context, tableOrderingsID sql.NullInt64) (*DgPosTable, error)
	//GetTables
	//
	//  SELECT tbs.id, tbs.table_orderings_id, tbs.shop_id, tbs.brand_id, tbs.name, tbs.description, tbs.seat_count, tbs.status, tbs.ongoing_order_id, tbs.created_at, tbs.updated_at
	//  FROM
	//      dg_pos_tables tbs
	//  WHERE (
	//          ? IS NULL
	//          OR tbs.shop_id = ?
	//      )
	//      AND (
	//          ? IS NULL
	//          OR tbs.brand_id = ?
	//      )
	GetTables(ctx context.Context, arg *GetTablesParams) ([]*DgPosTable, error)
	//GetTax
	//
	//  SELECT id, name, code, description, rate, status, created_at, updated_at FROM taxes_main WHERE id = ?
	GetTax(ctx context.Context, id uint64) (*TaxesMain, error)
	//GetTaxProfilesWithRulesConditions
	//
	//  SELECT tp.id, tp.name, tp.description, tp.status, tp.created_at, tp.updated_at, tr.id, tax_profile_id, tax_id, tr.name, tr.created_at, tr.updated_at, trc.id, tax_rule_id, condition_type, condition_value, min_value, max_value, start_date, end_date, trc.created_at, trc.updated_at, t.id, t.name, code, t.description, rate, t.status, t.created_at, t.updated_at FROM tax_profiles tp
	//  JOIN tax_rules tr ON tr.tax_profile_id = tp.id
	//  JOIN tax_rule_conditions trc ON trc.tax_rule_id = tr.id
	//  JOIN taxes_main t ON t.id = tr.tax_id
	GetTaxProfilesWithRulesConditions(ctx context.Context) ([]*GetTaxProfilesWithRulesConditionsRow, error)
	//GetTenantInfo
	//
	//  SELECT id, host, port, database_name, x_tenant_code, username, password, server_client_id, server_client_secret, site_name, prd_domain, created_at, updated_at, has_webshop, enable_dusk, dusk_port, sync_status, sync_webshop_status, has_multishop, send_reports, retry_authentication, enable_encryption, enable_pos FROM tenants WHERE x_tenant_code = ?
	GetTenantInfo(ctx context.Context, xTenantCode string) (*Tenant, error)
	//GetTenants
	//
	//  SELECT id, host, port, database_name, x_tenant_code, username, password, server_client_id, server_client_secret, site_name, prd_domain, created_at, updated_at, has_webshop, enable_dusk, dusk_port, sync_status, sync_webshop_status, has_multishop, send_reports, retry_authentication, enable_encryption, enable_pos FROM tenants
	GetTenants(ctx context.Context) ([]*Tenant, error)
	//GetTransactionByID
	//
	//  SELECT id, type_id, type, transaction_type, transaction_amount, transaction_mode, payment_type, platform, created_at, updated_at FROM order_transaction WHERE id = ?
	GetTransactionByID(ctx context.Context, id uint64) (*OrderTransaction, error)
	//GetUserByID
	//
	//  SELECT
	//      u.id,
	//      u.name,
	//      u.key_id_name,
	//      u.last_name,
	//      u.key_id_last_name,
	//      u.email,
	//      u.key_id_email,
	//      u.address,
	//      u.key_id_address,
	//      u.contact_no,
	//      u.key_id_contact_no,
	//      u.status,
	//      u.created_at,
	//      u.updated_at,
	//      r.id AS role_id,
	//      r.name AS role_name
	//  FROM
	//      users u
	//      LEFT JOIN user_roles ur ON u.id = ur.user_id
	//      LEFT JOIN roles r ON ur.role_id = r.id
	//  WHERE
	//      u.id = ?
	GetUserByID(ctx context.Context, id uint64) (*GetUserByIDRow, error)
	//GetUserByOutletCodeAndEmail
	//
	//  SELECT u.id, u.pin, u.status, s.id AS outlet_id
	//  FROM
	//      users u
	//      JOIN user_shop us ON us.user_id = u.id
	//      JOIN shop s ON us.shop_id = s.id
	//  WHERE
	//      u.hashed_email = ?
	//      AND s.code = ?
	GetUserByOutletCodeAndEmail(ctx context.Context, arg *GetUserByOutletCodeAndEmailParams) (*GetUserByOutletCodeAndEmailRow, error)
	//GetUsers
	//
	//  SELECT
	//      u.id,
	//      u.name,
	//      u.key_id_name,
	//      u.last_name,
	//      u.key_id_last_name,
	//      u.email,
	//      u.key_id_email,
	//      u.contact_no,
	//      u.key_id_contact_no,
	//      u.address,
	//      u.key_id_address,
	//      r.id AS role_id,
	//      r.name AS role_name
	//  FROM
	//      users u
	//      LEFT JOIN user_roles ur ON u.id = ur.user_id
	//      LEFT JOIN roles r ON ur.role_id = r.id
	//      JOIN user_shop us ON us.user_id = u.id
	//      JOIN shop s ON s.id = us.shop_id
	//  WHERE
	//      r.id IN (/*SLICE:role_ids*/?)
	//      AND s.code = ?
	//  ORDER BY u.name
	GetUsers(ctx context.Context, arg *GetUsersParams) ([]*GetUsersRow, error)
	//GetVoucherIdAndType
	//
	//  SELECT id, voucher_type FROM vouchers WHERE voucher_code = ?
	GetVoucherIdAndType(ctx context.Context, voucherCode string) (*GetVoucherIdAndTypeRow, error)
	//GetWebshopBrandById
	//
	//  SELECT id, brand_name, brand_code, domain, status, setup_status, has_multishop, default_shop, created_at, updated_at, loyalty_points_per_pound, pounds_per_point, loyalty_expire_date FROM webshop_brand WHERE id = ?
	GetWebshopBrandById(ctx context.Context, id uint32) (*WebshopBrand, error)
	//GetWebshopOrderLocation
	//
	//  SELECT id, order_tmp_id, order_id, type, first_name, last_name, email, phone, country_code, address_line_1, address_line_2, city, state, postcode, country, latitude, longitude, created_at, updated_at FROM webshop_order_location WHERE order_id = ?
	GetWebshopOrderLocation(ctx context.Context, orderID sql.NullInt64) (*WebshopOrderLocation, error)
	//GetWebshopPaymentStatusByOrderId
	//
	//  SELECT payment_status, payment_type FROM webshop_payments WHERE order_id = ?
	GetWebshopPaymentStatusByOrderId(ctx context.Context, orderID sql.NullInt32) (*GetWebshopPaymentStatusByOrderIdRow, error)
	//InsertDgPosTmpPayment
	//
	//  INSERT INTO
	//      dg_pos_tmp_payments (
	//          `type_id`,
	//          `type`,
	//          payment_mode,
	//          payment_amount,
	//          transaction_id,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	InsertDgPosTmpPayment(ctx context.Context, arg *InsertDgPosTmpPaymentParams) error
	//InsertOrderTaxable
	//
	//  INSERT INTO
	//      order_taxes (
	//          order_id,
	//          tax_rate,
	//          tax_code,
	//          tax_amount,
	//          taxable_amount,
	//          type,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	InsertOrderTaxable(ctx context.Context, arg *InsertOrderTaxableParams) error
	//MakeCustomerAddressNonDefault
	//
	//  UPDATE delivery_location
	//  SET
	//      default_address = 0
	//  WHERE
	//      customer_id = ?
	MakeCustomerAddressNonDefault(ctx context.Context, customerID int32) error
	//RemoveOngoingOrderForTable
	//
	//  DELETE FROM dg_pos_tables_ongoing_orders WHERE table_id = ?
	RemoveOngoingOrderForTable(ctx context.Context, tableID uint64) error
	//SetLogout
	//
	//  UPDATE dg_pos_user_shifts
	//  SET
	//      logout = ?
	//  WHERE
	//      user_id = ?
	//      AND logout IS NULL
	SetLogout(ctx context.Context, arg *SetLogoutParams) error
	//UpdateClosingBalanceCounted
	//
	//  UPDATE dg_pos_cash_drawer_sessions
	//  SET
	//      closing_balance_counted = ?
	//  WHERE
	//      id = ?
	UpdateClosingBalanceCounted(ctx context.Context, arg *UpdateClosingBalanceCountedParams) error
	//UpdateCustomer
	//
	//  UPDATE customers
	//  SET
	//      first_name = ?,
	//      hashed_first_name = ?,
	//      key_id_first_name = ?,
	//      last_name = ?,
	//      hashed_last_name = ?,
	//      key_id_last_name = ?,
	//      hashed_phone = ?,
	//      phone = ?,
	//      key_id_phone = ?,
	//      country_code = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateCustomer(ctx context.Context, arg *UpdateCustomerParams) error
	//UpdateCustomerVoucher
	//
	//  UPDATE customer_vouchers
	//  SET
	//      is_used = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      customer_id = ?
	//      AND voucher_id = ?
	UpdateCustomerVoucher(ctx context.Context, arg *UpdateCustomerVoucherParams) error
	//UpdateDeliveryLocation
	//
	//  UPDATE delivery_location
	//  SET
	//      label = ?,
	//      flat_no = ?,
	//      house_no = ?,
	//      address_line_1 = ?,
	//      address_line_2 = ?,
	//      latitude = ?,
	//      longitude = ?,
	//      city = ?,
	//      landmark = ?,
	//      postal_code = ?,
	//      default_address = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	//      AND customer_id = ?
	UpdateDeliveryLocation(ctx context.Context, arg *UpdateDeliveryLocationParams) error
	//UpdateDgPosPayment
	//
	//  UPDATE `dg_pos_payments`
	//  SET
	//      amount = ?,
	//      cash = ?,
	//      balance = ?,
	//      transaction_id = ?,
	//      card_transaction_token = ?,
	//      payment_method_id = ?,
	//      status = ?,
	//      updated_at = ?
	//  WHERE
	//      order_id = ?
	UpdateDgPosPayment(ctx context.Context, arg *UpdateDgPosPaymentParams) error
	//UpdateOrder
	//
	//  UPDATE `order`
	//  SET
	//      shop_id = ?,
	//      platform_id = ?,
	//      remote_order_id = ?,
	//      display_order_id = ?,
	//      delivery_date_time = ?,
	//      total_amount = ?,
	//      sub_total = ?,
	//      total_fee = ?,
	//      campaign_code = ?,
	//      discount = ?,
	//      voucher_discount = ?,
	//      discount_mode_applied = ?,
	//      discount_percentage_applied = ?,
	//      discount_type = ?,
	//      vouchers = ?,
	//      status = ?,
	//      cancelled_reason = ?,
	//      order_type_id = ?,
	//      note = ?,
	//      customer_name = ?,
	//      user_id = ?,
	//      customer_id = ?,
	//      delivery_location_id = ?,
	//      shipping_method = ?,
	//      shipping_total = ?,
	//      shipping_tax = ?,
	//      total_tax = ?,
	//      cash_due = ?,
	//      surcharge = ?,
	//      contact_access_code = ?,
	//      testing_order = ?,
	//      cancelled_by_customer = ?,
	//      payment_method = ?,
	//      is_scheduled = ?,
	//      is_table_order = ?,
	//      tip = ?,
	//      tip_percentage = ?,
	//      dgpos_table_id = ?,
	//      table_order_method_id = ?,
	//      device_platform = ?,
	//      order_delayed = ?,
	//      unique_order_id = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateOrder(ctx context.Context, arg *UpdateOrderParams) error
	//UpdateOrderCancelledReason
	//
	//  UPDATE `order`
	//  SET
	//      cancelled_reason = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateOrderCancelledReason(ctx context.Context, arg *UpdateOrderCancelledReasonParams) error
	//UpdateOrderCommission
	//
	//  UPDATE order_commission
	//  SET
	//      commission = ?,
	//      updated_at = ?
	//  WHERE
	//      order_id = ?
	UpdateOrderCommission(ctx context.Context, arg *UpdateOrderCommissionParams) error
	//UpdateOrderItemsStatus
	//
	//  UPDATE `order_items` SET status = ? WHERE order_id = ?
	UpdateOrderItemsStatus(ctx context.Context, arg *UpdateOrderItemsStatusParams) error
	//UpdateOrderPaymentMode
	//
	//  UPDATE `order`
	//  SET
	//      payment_mode = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateOrderPaymentMode(ctx context.Context, arg *UpdateOrderPaymentModeParams) error
	//UpdateOrderStatus
	//
	//  UPDATE `order`
	//  SET
	//      status = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateOrderStatus(ctx context.Context, arg *UpdateOrderStatusParams) error
	//UpdateOrderTableId
	//
	//  UPDATE `order`
	//  SET
	//      dgpos_table_id = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateOrderTableId(ctx context.Context, arg *UpdateOrderTableIdParams) error
	//UpdateOrderTimestamps
	//
	//  UPDATE dg_pos_order_status_timestamps
	//  SET
	//      queue = ?,
	//      preparing = ?,
	//      ready = ?,
	//      served = ?,
	//      delivered = ?,
	//      completed = ?,
	//      updated_at = ?
	//  WHERE
	//      order_id = ?
	UpdateOrderTimestamps(ctx context.Context, arg *UpdateOrderTimestampsParams) error
	//UpdateOrderUserID
	//
	//  UPDATE `order`
	//  SET
	//      user_id = ?
	//  WHERE
	//      id = ?
	UpdateOrderUserID(ctx context.Context, arg *UpdateOrderUserIDParams) error
	//UpdatePayment
	//
	//  UPDATE `payments`
	//  SET
	//      amount = ?,
	//      tax = ?,
	//      discount = ?,
	//      payment_method_id = ?,
	//      updated_at = ?
	//  WHERE
	//      order_id = ?
	UpdatePayment(ctx context.Context, arg *UpdatePaymentParams) error
	//UpdateReportServiceToken
	//
	//  UPDATE report_service
	//  SET
	//      bearer_token = ?,
	//      expire_in = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE
	//      id = ?
	UpdateReportServiceToken(ctx context.Context, arg *UpdateReportServiceTokenParams) error
	//UpdateTableStatus
	//
	//  UPDATE dg_pos_tables
	//  SET
	//      status = ?
	//  WHERE
	//      id = ?
	UpdateTableStatus(ctx context.Context, arg *UpdateTableStatusParams) error
	//UpdateTableStatusByTableOrderingsID
	//
	//  UPDATE dg_pos_tables
	//  SET
	//      status = ?
	//  WHERE
	//      table_orderings_id = ?
	UpdateTableStatusByTableOrderingsID(ctx context.Context, arg *UpdateTableStatusByTableOrderingsIDParams) error
	//UpdateUserPin
	//
	//  UPDATE users
	//  SET
	//      pin = ?
	//  WHERE
	//      id = ?
	UpdateUserPin(ctx context.Context, arg *UpdateUserPinParams) error
	//UpdateVoucherUsage
	//
	//  UPDATE vouchers
	//  SET
	//      current_usage = current_usage + ?
	//  WHERE
	//      voucher_code = ?
	UpdateVoucherUsage(ctx context.Context, arg *UpdateVoucherUsageParams) error
	//UpsertCashMovement
	//
	//  INSERT INTO
	//      dg_pos_cash_movements (
	//          id,
	//          cash_drawer_session_id,
	//          movement_type,
	//          note,
	//          amount,
	//          user_id,
	//          created_at,
	//          updated_at
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          CURRENT_TIMESTAMP,
	//          CURRENT_TIMESTAMP
	//      )
	//  ON DUPLICATE KEY UPDATE
	//      amount = amount +
	//  VALUES (amount),
	//      note = VALUES(note),
	//      updated_at = CURRENT_TIMESTAMP
	UpsertCashMovement(ctx context.Context, arg *UpsertCashMovementParams) error
	//UpsertShopConfig
	//
	//  INSERT INTO
	//      dg_pos_shop_config (
	//          id,
	//          shop_id,
	//          brand_id,
	//          terminal_id,
	//          config_type,
	//          data
	//      )
	//  VALUES (
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?,
	//          ?
	//      )
	//  ON DUPLICATE KEY UPDATE
	//      data = VALUES(data)
	UpsertShopConfig(ctx context.Context, arg *UpsertShopConfigParams) error
}

var _ Querier = (*Queries)(nil)
