// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report_service.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestReportServiceToken = `-- name: GetLatestReportServiceToken :one
SELECT id, dns, server_client_id, server_client_secret, bearer_token, expire_in, created_at, updated_at FROM report_service ORDER BY id DESC LIMIT 1
`

// GetLatestReportServiceToken
//
//	SELECT id, dns, server_client_id, server_client_secret, bearer_token, expire_in, created_at, updated_at FROM report_service ORDER BY id DESC LIMIT 1
func (q *Queries) GetLatestReportServiceToken(ctx context.Context) (*ReportService, error) {
	row := q.db.QueryRowContext(ctx, getLatestReportServiceToken)
	var i ReportService
	err := row.Scan(
		&i.ID,
		&i.Dns,
		&i.ServerClientID,
		&i.ServerClientSecret,
		&i.BearerToken,
		&i.ExpireIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateReportServiceToken = `-- name: UpdateReportServiceToken :exec
UPDATE report_service
SET
    bearer_token = ?,
    expire_in = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateReportServiceTokenParams struct {
	BearerToken sql.NullString `json:"bearer_token"`
	ExpireIn    sql.NullTime   `json:"expire_in"`
	ID          uint64         `json:"id"`
}

// UpdateReportServiceToken
//
//	UPDATE report_service
//	SET
//	    bearer_token = ?,
//	    expire_in = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    id = ?
func (q *Queries) UpdateReportServiceToken(ctx context.Context, arg *UpdateReportServiceTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateReportServiceToken, arg.BearerToken, arg.ExpireIn, arg.ID)
	return err
}
