// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shift_reports.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getShiftInfoByShop = `-- name: GetShiftInfoByShop :many
WITH
    orders_and_net_totals AS (
        SELECT
            odr.id,
            odr.user_id,
            0 + SUM(
                CASE
                    WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
                        WHEN ot.transaction_type = 'SALE' THEN 1
                        WHEN ot.transaction_type = 'REFUND' THEN -1
                        ELSE 0
                    END
                    ELSE 0
                END
            ) AS cash_sales_total,
            0 + SUM(
                CASE
                    WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
                        WHEN ot.transaction_type = 'SALE' THEN 1
                        WHEN ot.transaction_type = 'REFUND' THEN -1
                        ELSE 0
                    END
                    ELSE 0
                END
            ) AS card_sales_total,
            0 + SUM(
                ot.transaction_amount * CASE
                    WHEN ot.transaction_type = 'SALE' THEN 1
                    WHEN ot.transaction_type = 'REFUND' THEN -1
                    ELSE 0
                END
            ) AS net_sales
        FROM
            ` + "`" + `order` + "`" + ` odr
            JOIN order_transaction ot ON odr.id = ot.type_id
        WHERE
            odr.status IN ('COMPLETED', 'CANCELED')
            AND odr.device_platform = 'dg_pos'
            AND odr.created_at >= ?
            AND odr.created_at <= ?
            AND odr.shop_id = ?
        GROUP BY
            odr.id
    )
SELECT
    user_id,
    COUNT(id) AS orders_created,
    0 + SUM(cash_sales_total) AS total_cash_sales,
    0 + SUM(card_sales_total) AS total_card_sales,
    0 + SUM(net_sales) AS total_net_sales
FROM orders_and_net_totals
GROUP BY
    user_id
`

type GetShiftInfoByShopParams struct {
	FromCreatedAt sql.NullTime `json:"from_created_at"`
	ToCreatedAt   sql.NullTime `json:"to_created_at"`
	ShopID        int32        `json:"shop_id"`
}

type GetShiftInfoByShopRow struct {
	UserID         sql.NullInt32 `json:"user_id"`
	OrdersCreated  int64         `json:"orders_created"`
	TotalCashSales int32         `json:"total_cash_sales"`
	TotalCardSales int32         `json:"total_card_sales"`
	TotalNetSales  int32         `json:"total_net_sales"`
}

// GetShiftInfoByShop
//
//	WITH
//	    orders_and_net_totals AS (
//	        SELECT
//	            odr.id,
//	            odr.user_id,
//	            0 + SUM(
//	                CASE
//	                    WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
//	                        WHEN ot.transaction_type = 'SALE' THEN 1
//	                        WHEN ot.transaction_type = 'REFUND' THEN -1
//	                        ELSE 0
//	                    END
//	                    ELSE 0
//	                END
//	            ) AS cash_sales_total,
//	            0 + SUM(
//	                CASE
//	                    WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
//	                        WHEN ot.transaction_type = 'SALE' THEN 1
//	                        WHEN ot.transaction_type = 'REFUND' THEN -1
//	                        ELSE 0
//	                    END
//	                    ELSE 0
//	                END
//	            ) AS card_sales_total,
//	            0 + SUM(
//	                ot.transaction_amount * CASE
//	                    WHEN ot.transaction_type = 'SALE' THEN 1
//	                    WHEN ot.transaction_type = 'REFUND' THEN -1
//	                    ELSE 0
//	                END
//	            ) AS net_sales
//	        FROM
//	            `order` odr
//	            JOIN order_transaction ot ON odr.id = ot.type_id
//	        WHERE
//	            odr.status IN ('COMPLETED', 'CANCELED')
//	            AND odr.device_platform = 'dg_pos'
//	            AND odr.created_at >= ?
//	            AND odr.created_at <= ?
//	            AND odr.shop_id = ?
//	        GROUP BY
//	            odr.id
//	    )
//	SELECT
//	    user_id,
//	    COUNT(id) AS orders_created,
//	    0 + SUM(cash_sales_total) AS total_cash_sales,
//	    0 + SUM(card_sales_total) AS total_card_sales,
//	    0 + SUM(net_sales) AS total_net_sales
//	FROM orders_and_net_totals
//	GROUP BY
//	    user_id
func (q *Queries) GetShiftInfoByShop(ctx context.Context, arg *GetShiftInfoByShopParams) ([]*GetShiftInfoByShopRow, error) {
	rows, err := q.db.QueryContext(ctx, getShiftInfoByShop, arg.FromCreatedAt, arg.ToCreatedAt, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetShiftInfoByShopRow{}
	for rows.Next() {
		var i GetShiftInfoByShopRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrdersCreated,
			&i.TotalCashSales,
			&i.TotalCardSales,
			&i.TotalNetSales,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShiftInfoByUser = `-- name: GetShiftInfoByUser :many
WITH
    orders_and_net_totals AS (
        SELECT
            odr.id,
            odr.user_id,
            odr.created_at,
            0 + SUM(
                CASE
                    WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
                        WHEN ot.transaction_type = 'SALE' THEN 1
                        WHEN ot.transaction_type = 'REFUND' THEN -1
                        ELSE 0
                    END
                    ELSE 0
                END
            ) AS cash_sales_total,
            0 + SUM(
                CASE
                    WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
                        WHEN ot.transaction_type = 'SALE' THEN 1
                        WHEN ot.transaction_type = 'REFUND' THEN -1
                        ELSE 0
                    END
                    ELSE 0
                END
            ) AS card_sales_total,
            0 + SUM(
                ot.transaction_amount * CASE
                    WHEN ot.transaction_type = 'SALE' THEN 1
                    WHEN ot.transaction_type = 'REFUND' THEN -1
                    ELSE 0
                END
            ) AS net_sales
        FROM
            ` + "`" + `order` + "`" + ` odr
            JOIN order_transaction ot ON odr.id = ot.type_id
        WHERE
            odr.status IN ('COMPLETED', 'CANCELED')
            AND odr.device_platform = 'dg_pos'
            AND odr.created_at >= ?
            AND odr.created_at <= ?
            AND odr.shop_id = ?
            AND odr.user_id = ?
        GROUP BY
            odr.id
    )
SELECT
    shifts.id AS shift_id,
    shifts.login,
    shifts.logout,
    COUNT(odr.id) AS orders_created,
    0 + SUM(odr.cash_sales_total) AS cash_total,
    0 + SUM(odr.card_sales_total) AS card_total,
    0 + SUM(odr.net_sales) AS total
FROM
    orders_and_net_totals odr
    JOIN dg_pos_user_shifts shifts ON shifts.user_id = odr.user_id
    AND odr.created_at BETWEEN shifts.login AND COALESCE(shifts.logout, NOW())
GROUP BY
    shifts.id
`

type GetShiftInfoByUserParams struct {
	FromCreatedAt sql.NullTime  `json:"from_created_at"`
	ToCreatedAt   sql.NullTime  `json:"to_created_at"`
	ShopID        int32         `json:"shop_id"`
	UserID        sql.NullInt32 `json:"user_id"`
}

type GetShiftInfoByUserRow struct {
	ShiftID       uint64       `json:"shift_id"`
	Login         time.Time    `json:"login"`
	Logout        sql.NullTime `json:"logout"`
	OrdersCreated int64        `json:"orders_created"`
	CashTotal     int32        `json:"cash_total"`
	CardTotal     int32        `json:"card_total"`
	Total         int32        `json:"total"`
}

// GetShiftInfoByUser
//
//	WITH
//	    orders_and_net_totals AS (
//	        SELECT
//	            odr.id,
//	            odr.user_id,
//	            odr.created_at,
//	            0 + SUM(
//	                CASE
//	                    WHEN ot.transaction_mode = 'CASH' THEN ot.transaction_amount * CASE
//	                        WHEN ot.transaction_type = 'SALE' THEN 1
//	                        WHEN ot.transaction_type = 'REFUND' THEN -1
//	                        ELSE 0
//	                    END
//	                    ELSE 0
//	                END
//	            ) AS cash_sales_total,
//	            0 + SUM(
//	                CASE
//	                    WHEN ot.transaction_mode = 'CARD' THEN ot.transaction_amount * CASE
//	                        WHEN ot.transaction_type = 'SALE' THEN 1
//	                        WHEN ot.transaction_type = 'REFUND' THEN -1
//	                        ELSE 0
//	                    END
//	                    ELSE 0
//	                END
//	            ) AS card_sales_total,
//	            0 + SUM(
//	                ot.transaction_amount * CASE
//	                    WHEN ot.transaction_type = 'SALE' THEN 1
//	                    WHEN ot.transaction_type = 'REFUND' THEN -1
//	                    ELSE 0
//	                END
//	            ) AS net_sales
//	        FROM
//	            `order` odr
//	            JOIN order_transaction ot ON odr.id = ot.type_id
//	        WHERE
//	            odr.status IN ('COMPLETED', 'CANCELED')
//	            AND odr.device_platform = 'dg_pos'
//	            AND odr.created_at >= ?
//	            AND odr.created_at <= ?
//	            AND odr.shop_id = ?
//	            AND odr.user_id = ?
//	        GROUP BY
//	            odr.id
//	    )
//	SELECT
//	    shifts.id AS shift_id,
//	    shifts.login,
//	    shifts.logout,
//	    COUNT(odr.id) AS orders_created,
//	    0 + SUM(odr.cash_sales_total) AS cash_total,
//	    0 + SUM(odr.card_sales_total) AS card_total,
//	    0 + SUM(odr.net_sales) AS total
//	FROM
//	    orders_and_net_totals odr
//	    JOIN dg_pos_user_shifts shifts ON shifts.user_id = odr.user_id
//	    AND odr.created_at BETWEEN shifts.login AND COALESCE(shifts.logout, NOW())
//	GROUP BY
//	    shifts.id
func (q *Queries) GetShiftInfoByUser(ctx context.Context, arg *GetShiftInfoByUserParams) ([]*GetShiftInfoByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getShiftInfoByUser,
		arg.FromCreatedAt,
		arg.ToCreatedAt,
		arg.ShopID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetShiftInfoByUserRow{}
	for rows.Next() {
		var i GetShiftInfoByUserRow
		if err := rows.Scan(
			&i.ShiftID,
			&i.Login,
			&i.Logout,
			&i.OrdersCreated,
			&i.CashTotal,
			&i.CardTotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
