// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shop_fee.sql

package db

import (
	"context"
	"database/sql"
)

const deleteOrderShopFees = `-- name: DeleteOrderShopFees :exec
DELETE FROM order_shop_fee WHERE order_id = ?
`

// DeleteOrderShopFees
//
//	DELETE FROM order_shop_fee WHERE order_id = ?
func (q *Queries) DeleteOrderShopFees(ctx context.Context, orderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrderShopFees, orderID)
	return err
}

const getShopFees = `-- name: GetShopFees :many
SELECT 
  sf.id, sf.shop_id, sf.webshop_brand_id, sf.platform, sf.type, sf.fee_name, sf.fee, sf.fee_type, sf.status, sf.tax_id, sf.mandatory, sf.created_at, sf.updated_at, sf.deleted_at,
  t.id, t.name, t.code, t.description, t.rate, t.status, t.created_at, t.updated_at
FROM shop_fee sf
LEFT JOIN taxes_main t ON t.id = sf.tax_id
WHERE
    sf.shop_id = ?
    AND sf.webshop_brand_id = ?
    AND sf.status = 1
    AND sf.platform = 'DG_POS'
`

type GetShopFeesParams struct {
	ShopID         int32  `json:"shop_id"`
	WebshopBrandID uint32 `json:"webshop_brand_id"`
}

type GetShopFeesRow struct {
	ID             uint64         `json:"id"`
	ShopID         int32          `json:"shop_id"`
	WebshopBrandID uint32         `json:"webshop_brand_id"`
	Platform       sql.NullString `json:"platform"`
	Type           sql.NullString `json:"type"`
	FeeName        string         `json:"fee_name"`
	Fee            string         `json:"fee"`
	FeeType        string         `json:"fee_type"`
	Status         bool           `json:"status"`
	TaxID          sql.NullInt32  `json:"tax_id"`
	Mandatory      bool           `json:"mandatory"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ID_2           sql.NullInt64  `json:"id_2"`
	Name           sql.NullString `json:"name"`
	Code           sql.NullString `json:"code"`
	Description    sql.NullString `json:"description"`
	Rate           sql.NullString `json:"rate"`
	Status_2       sql.NullBool   `json:"status_2"`
	CreatedAt_2    sql.NullTime   `json:"created_at_2"`
	UpdatedAt_2    sql.NullTime   `json:"updated_at_2"`
}

// GetShopFees
//
//	SELECT
//	  sf.id, sf.shop_id, sf.webshop_brand_id, sf.platform, sf.type, sf.fee_name, sf.fee, sf.fee_type, sf.status, sf.tax_id, sf.mandatory, sf.created_at, sf.updated_at, sf.deleted_at,
//	  t.id, t.name, t.code, t.description, t.rate, t.status, t.created_at, t.updated_at
//	FROM shop_fee sf
//	LEFT JOIN taxes_main t ON t.id = sf.tax_id
//	WHERE
//	    sf.shop_id = ?
//	    AND sf.webshop_brand_id = ?
//	    AND sf.status = 1
//	    AND sf.platform = 'DG_POS'
func (q *Queries) GetShopFees(ctx context.Context, arg *GetShopFeesParams) ([]*GetShopFeesRow, error) {
	rows, err := q.db.QueryContext(ctx, getShopFees, arg.ShopID, arg.WebshopBrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetShopFeesRow{}
	for rows.Next() {
		var i GetShopFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.WebshopBrandID,
			&i.Platform,
			&i.Type,
			&i.FeeName,
			&i.Fee,
			&i.FeeType,
			&i.Status,
			&i.TaxID,
			&i.Mandatory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ID_2,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Rate,
			&i.Status_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShopFeesByOrderID = `-- name: GetShopFeesByOrderID :many
SELECT 
  osf.id, osf.order_id, osf.shop_fee_id, osf.amount, osf.shop_fee_tax, osf.tax_id, osf.created_at, osf.updated_at, 
  t.code AS tax_code,
  t.rate AS tax_rate,
  sf.fee_name, 
  sf.fee_type
FROM
  order_shop_fee osf
  JOIN shop_fee sf ON sf.id = osf.shop_fee_id
  LEFT JOIN taxes_main t ON t.id = osf.tax_id
WHERE
  osf.order_id = ?
`

type GetShopFeesByOrderIDRow struct {
	ID         uint64         `json:"id"`
	OrderID    int32          `json:"order_id"`
	ShopFeeID  int32          `json:"shop_fee_id"`
	Amount     int32          `json:"amount"`
	ShopFeeTax sql.NullInt32  `json:"shop_fee_tax"`
	TaxID      sql.NullInt32  `json:"tax_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	TaxCode    sql.NullString `json:"tax_code"`
	TaxRate    sql.NullString `json:"tax_rate"`
	FeeName    string         `json:"fee_name"`
	FeeType    string         `json:"fee_type"`
}

// GetShopFeesByOrderID
//
//	SELECT
//	  osf.id, osf.order_id, osf.shop_fee_id, osf.amount, osf.shop_fee_tax, osf.tax_id, osf.created_at, osf.updated_at,
//	  t.code AS tax_code,
//	  t.rate AS tax_rate,
//	  sf.fee_name,
//	  sf.fee_type
//	FROM
//	  order_shop_fee osf
//	  JOIN shop_fee sf ON sf.id = osf.shop_fee_id
//	  LEFT JOIN taxes_main t ON t.id = osf.tax_id
//	WHERE
//	  osf.order_id = ?
func (q *Queries) GetShopFeesByOrderID(ctx context.Context, orderID int32) ([]*GetShopFeesByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getShopFeesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetShopFeesByOrderIDRow{}
	for rows.Next() {
		var i GetShopFeesByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ShopFeeID,
			&i.Amount,
			&i.ShopFeeTax,
			&i.TaxID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaxCode,
			&i.TaxRate,
			&i.FeeName,
			&i.FeeType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
