// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tax_query.sql

package db

import (
	"context"
	"database/sql"
)

const getTax = `-- name: GetTax :one
SELECT id, name, code, description, rate, status, created_at, updated_at FROM taxes_main WHERE id = ?
`

// GetTax
//
//	SELECT id, name, code, description, rate, status, created_at, updated_at FROM taxes_main WHERE id = ?
func (q *Queries) GetTax(ctx context.Context, id uint64) (*TaxesMain, error) {
	row := q.db.QueryRowContext(ctx, getTax, id)
	var i TaxesMain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Rate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTaxProfilesWithRulesConditions = `-- name: GetTaxProfilesWithRulesConditions :many
SELECT tp.id, tp.name, tp.description, tp.status, tp.created_at, tp.updated_at, tr.id, tax_profile_id, tax_id, tr.name, tr.created_at, tr.updated_at, trc.id, tax_rule_id, condition_type, condition_value, min_value, max_value, start_date, end_date, trc.created_at, trc.updated_at, t.id, t.name, code, t.description, rate, t.status, t.created_at, t.updated_at FROM tax_profiles tp
JOIN tax_rules tr ON tr.tax_profile_id = tp.id
JOIN tax_rule_conditions trc ON trc.tax_rule_id = tr.id
JOIN taxes_main t ON t.id = tr.tax_id
`

type GetTaxProfilesWithRulesConditionsRow struct {
	ID             uint64         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	Status         bool           `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ID_2           uint64         `json:"id_2"`
	TaxProfileID   int32          `json:"tax_profile_id"`
	TaxID          int32          `json:"tax_id"`
	Name_2         string         `json:"name_2"`
	CreatedAt_2    sql.NullTime   `json:"created_at_2"`
	UpdatedAt_2    sql.NullTime   `json:"updated_at_2"`
	ID_3           uint64         `json:"id_3"`
	TaxRuleID      int32          `json:"tax_rule_id"`
	ConditionType  string         `json:"condition_type"`
	ConditionValue sql.NullString `json:"condition_value"`
	MinValue       sql.NullString `json:"min_value"`
	MaxValue       sql.NullString `json:"max_value"`
	StartDate      sql.NullTime   `json:"start_date"`
	EndDate        sql.NullTime   `json:"end_date"`
	CreatedAt_3    sql.NullTime   `json:"created_at_3"`
	UpdatedAt_3    sql.NullTime   `json:"updated_at_3"`
	ID_4           uint64         `json:"id_4"`
	Name_3         sql.NullString `json:"name_3"`
	Code           string         `json:"code"`
	Description_2  sql.NullString `json:"description_2"`
	Rate           sql.NullString `json:"rate"`
	Status_2       bool           `json:"status_2"`
	CreatedAt_4    sql.NullTime   `json:"created_at_4"`
	UpdatedAt_4    sql.NullTime   `json:"updated_at_4"`
}

// GetTaxProfilesWithRulesConditions
//
//	SELECT tp.id, tp.name, tp.description, tp.status, tp.created_at, tp.updated_at, tr.id, tax_profile_id, tax_id, tr.name, tr.created_at, tr.updated_at, trc.id, tax_rule_id, condition_type, condition_value, min_value, max_value, start_date, end_date, trc.created_at, trc.updated_at, t.id, t.name, code, t.description, rate, t.status, t.created_at, t.updated_at FROM tax_profiles tp
//	JOIN tax_rules tr ON tr.tax_profile_id = tp.id
//	JOIN tax_rule_conditions trc ON trc.tax_rule_id = tr.id
//	JOIN taxes_main t ON t.id = tr.tax_id
func (q *Queries) GetTaxProfilesWithRulesConditions(ctx context.Context) ([]*GetTaxProfilesWithRulesConditionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaxProfilesWithRulesConditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTaxProfilesWithRulesConditionsRow{}
	for rows.Next() {
		var i GetTaxProfilesWithRulesConditionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.TaxProfileID,
			&i.TaxID,
			&i.Name_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.ID_3,
			&i.TaxRuleID,
			&i.ConditionType,
			&i.ConditionValue,
			&i.MinValue,
			&i.MaxValue,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt_3,
			&i.UpdatedAt_3,
			&i.ID_4,
			&i.Name_3,
			&i.Code,
			&i.Description_2,
			&i.Rate,
			&i.Status_2,
			&i.CreatedAt_4,
			&i.UpdatedAt_4,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
