// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_shifts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createLogin = `-- name: CreateLogin :exec
INSERT INTO dg_pos_user_shifts (user_id, login) VALUES (?, ?)
`

type CreateLoginParams struct {
	UserID int64     `json:"user_id"`
	Login  time.Time `json:"login"`
}

// CreateLogin
//
//	INSERT INTO dg_pos_user_shifts (user_id, login) VALUES (?, ?)
func (q *Queries) CreateLogin(ctx context.Context, arg *CreateLoginParams) error {
	_, err := q.db.ExecContext(ctx, createLogin, arg.UserID, arg.Login)
	return err
}

const getActiveShift = `-- name: GetActiveShift :one
SELECT id, user_id, login, logout, created_at, updated_at
FROM dg_pos_user_shifts
WHERE
    user_id = ?
    AND logout IS NULL
`

// GetActiveShift
//
//	SELECT id, user_id, login, logout, created_at, updated_at
//	FROM dg_pos_user_shifts
//	WHERE
//	    user_id = ?
//	    AND logout IS NULL
func (q *Queries) GetActiveShift(ctx context.Context, userID int64) (*DgPosUserShift, error) {
	row := q.db.QueryRowContext(ctx, getActiveShift, userID)
	var i DgPosUserShift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Login,
		&i.Logout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const setLogout = `-- name: SetLogout :exec
UPDATE dg_pos_user_shifts
SET
    logout = ?
WHERE
    user_id = ?
    AND logout IS NULL
`

type SetLogoutParams struct {
	Logout sql.NullTime `json:"logout"`
	UserID int64        `json:"user_id"`
}

// SetLogout
//
//	UPDATE dg_pos_user_shifts
//	SET
//	    logout = ?
//	WHERE
//	    user_id = ?
//	    AND logout IS NULL
func (q *Queries) SetLogout(ctx context.Context, arg *SetLogoutParams) error {
	_, err := q.db.ExecContext(ctx, setLogout, arg.Logout, arg.UserID)
	return err
}
