// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id,
    u.name,
    u.key_id_name,
    u.last_name,
    u.key_id_last_name,
    u.email,
    u.key_id_email,
    u.address,
    u.key_id_address,
    u.contact_no,
    u.key_id_contact_no,
    u.status,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.name AS role_name
FROM
    users u
    LEFT JOIN user_roles ur ON u.id = ur.user_id
    LEFT JOIN roles r ON ur.role_id = r.id
WHERE
    u.id = ?
`

type GetUserByIDRow struct {
	ID             uint64         `json:"id"`
	Name           string         `json:"name"`
	KeyIDName      int32          `json:"key_id_name"`
	LastName       sql.NullString `json:"last_name"`
	KeyIDLastName  int32          `json:"key_id_last_name"`
	Email          string         `json:"email"`
	KeyIDEmail     int32          `json:"key_id_email"`
	Address        sql.NullString `json:"address"`
	KeyIDAddress   int32          `json:"key_id_address"`
	ContactNo      sql.NullString `json:"contact_no"`
	KeyIDContactNo int32          `json:"key_id_contact_no"`
	Status         sql.NullString `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	RoleID         sql.NullInt32  `json:"role_id"`
	RoleName       sql.NullString `json:"role_name"`
}

// GetUserByID
//
//	SELECT
//	    u.id,
//	    u.name,
//	    u.key_id_name,
//	    u.last_name,
//	    u.key_id_last_name,
//	    u.email,
//	    u.key_id_email,
//	    u.address,
//	    u.key_id_address,
//	    u.contact_no,
//	    u.key_id_contact_no,
//	    u.status,
//	    u.created_at,
//	    u.updated_at,
//	    r.id AS role_id,
//	    r.name AS role_name
//	FROM
//	    users u
//	    LEFT JOIN user_roles ur ON u.id = ur.user_id
//	    LEFT JOIN roles r ON ur.role_id = r.id
//	WHERE
//	    u.id = ?
func (q *Queries) GetUserByID(ctx context.Context, id uint64) (*GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyIDName,
		&i.LastName,
		&i.KeyIDLastName,
		&i.Email,
		&i.KeyIDEmail,
		&i.Address,
		&i.KeyIDAddress,
		&i.ContactNo,
		&i.KeyIDContactNo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.RoleName,
	)
	return &i, err
}

const getUserByOutletCodeAndEmail = `-- name: GetUserByOutletCodeAndEmail :one
SELECT u.id, u.pin, u.status, s.id AS outlet_id
FROM
    users u
    JOIN user_shop us ON us.user_id = u.id
    JOIN shop s ON us.shop_id = s.id
WHERE
    u.hashed_email = ?
    AND s.code = ?
`

type GetUserByOutletCodeAndEmailParams struct {
	HashedEmail sql.NullString `json:"hashed_email"`
	OutletCode  string         `json:"outlet_code"`
}

type GetUserByOutletCodeAndEmailRow struct {
	ID       uint64         `json:"id"`
	Pin      sql.NullString `json:"pin"`
	Status   sql.NullString `json:"status"`
	OutletID uint64         `json:"outlet_id"`
}

// GetUserByOutletCodeAndEmail
//
//	SELECT u.id, u.pin, u.status, s.id AS outlet_id
//	FROM
//	    users u
//	    JOIN user_shop us ON us.user_id = u.id
//	    JOIN shop s ON us.shop_id = s.id
//	WHERE
//	    u.hashed_email = ?
//	    AND s.code = ?
func (q *Queries) GetUserByOutletCodeAndEmail(ctx context.Context, arg *GetUserByOutletCodeAndEmailParams) (*GetUserByOutletCodeAndEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByOutletCodeAndEmail, arg.HashedEmail, arg.OutletCode)
	var i GetUserByOutletCodeAndEmailRow
	err := row.Scan(
		&i.ID,
		&i.Pin,
		&i.Status,
		&i.OutletID,
	)
	return &i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    u.id,
    u.name,
    u.key_id_name,
    u.last_name,
    u.key_id_last_name,
    u.email,
    u.key_id_email,
    u.contact_no,
    u.key_id_contact_no,
    u.address,
    u.key_id_address,
    r.id AS role_id,
    r.name AS role_name
FROM
    users u
    LEFT JOIN user_roles ur ON u.id = ur.user_id
    LEFT JOIN roles r ON ur.role_id = r.id
    JOIN user_shop us ON us.user_id = u.id
    JOIN shop s ON s.id = us.shop_id
WHERE
    r.id IN (/*SLICE:role_ids*/?)
    AND s.code = ?
ORDER BY u.name
`

type GetUsersParams struct {
	RoleIds    []uint32 `json:"role_ids"`
	OutletCode string   `json:"outlet_code"`
}

type GetUsersRow struct {
	ID             uint64         `json:"id"`
	Name           string         `json:"name"`
	KeyIDName      int32          `json:"key_id_name"`
	LastName       sql.NullString `json:"last_name"`
	KeyIDLastName  int32          `json:"key_id_last_name"`
	Email          string         `json:"email"`
	KeyIDEmail     int32          `json:"key_id_email"`
	ContactNo      sql.NullString `json:"contact_no"`
	KeyIDContactNo int32          `json:"key_id_contact_no"`
	Address        sql.NullString `json:"address"`
	KeyIDAddress   int32          `json:"key_id_address"`
	RoleID         sql.NullInt32  `json:"role_id"`
	RoleName       sql.NullString `json:"role_name"`
}

// GetUsers
//
//	SELECT
//	    u.id,
//	    u.name,
//	    u.key_id_name,
//	    u.last_name,
//	    u.key_id_last_name,
//	    u.email,
//	    u.key_id_email,
//	    u.contact_no,
//	    u.key_id_contact_no,
//	    u.address,
//	    u.key_id_address,
//	    r.id AS role_id,
//	    r.name AS role_name
//	FROM
//	    users u
//	    LEFT JOIN user_roles ur ON u.id = ur.user_id
//	    LEFT JOIN roles r ON ur.role_id = r.id
//	    JOIN user_shop us ON us.user_id = u.id
//	    JOIN shop s ON s.id = us.shop_id
//	WHERE
//	    r.id IN (/*SLICE:role_ids*/?)
//	    AND s.code = ?
//	ORDER BY u.name
func (q *Queries) GetUsers(ctx context.Context, arg *GetUsersParams) ([]*GetUsersRow, error) {
	query := getUsers
	var queryParams []interface{}
	if len(arg.RoleIds) > 0 {
		for _, v := range arg.RoleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:role_ids*/?", strings.Repeat(",?", len(arg.RoleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:role_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OutletCode)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyIDName,
			&i.LastName,
			&i.KeyIDLastName,
			&i.Email,
			&i.KeyIDEmail,
			&i.ContactNo,
			&i.KeyIDContactNo,
			&i.Address,
			&i.KeyIDAddress,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPin = `-- name: UpdateUserPin :exec
UPDATE users
SET
    pin = ?
WHERE
    id = ?
`

type UpdateUserPinParams struct {
	Pin sql.NullString `json:"pin"`
	ID  uint64         `json:"id"`
}

// UpdateUserPin
//
//	UPDATE users
//	SET
//	    pin = ?
//	WHERE
//	    id = ?
func (q *Queries) UpdateUserPin(ctx context.Context, arg *UpdateUserPinParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPin, arg.Pin, arg.ID)
	return err
}
