// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vouchers.sql

package db

import (
	"context"
)

const createCustomerVoucher = `-- name: CreateCustomerVoucher :exec
INSERT INTO
    customer_vouchers (
        customer_id,
        voucher_id,
        is_used,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateCustomerVoucherParams struct {
	CustomerID uint32 `json:"customer_id"`
	VoucherID  uint32 `json:"voucher_id"`
	IsUsed     bool   `json:"is_used"`
}

// CreateCustomerVoucher
//
//	INSERT INTO
//	    customer_vouchers (
//	        customer_id,
//	        voucher_id,
//	        is_used,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
func (q *Queries) CreateCustomerVoucher(ctx context.Context, arg *CreateCustomerVoucherParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerVoucher, arg.CustomerID, arg.VoucherID, arg.IsUsed)
	return err
}

const deleteCustomerVoucher = `-- name: DeleteCustomerVoucher :exec
DELETE FROM customer_vouchers
WHERE
    customer_id = ?
    AND voucher_id = ?
`

type DeleteCustomerVoucherParams struct {
	CustomerID uint32 `json:"customer_id"`
	VoucherID  uint32 `json:"voucher_id"`
}

// DeleteCustomerVoucher
//
//	DELETE FROM customer_vouchers
//	WHERE
//	    customer_id = ?
//	    AND voucher_id = ?
func (q *Queries) DeleteCustomerVoucher(ctx context.Context, arg *DeleteCustomerVoucherParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerVoucher, arg.CustomerID, arg.VoucherID)
	return err
}

const getVoucherIdAndType = `-- name: GetVoucherIdAndType :one
SELECT id, voucher_type FROM vouchers WHERE voucher_code = ?
`

type GetVoucherIdAndTypeRow struct {
	ID          uint64 `json:"id"`
	VoucherType string `json:"voucher_type"`
}

// GetVoucherIdAndType
//
//	SELECT id, voucher_type FROM vouchers WHERE voucher_code = ?
func (q *Queries) GetVoucherIdAndType(ctx context.Context, voucherCode string) (*GetVoucherIdAndTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getVoucherIdAndType, voucherCode)
	var i GetVoucherIdAndTypeRow
	err := row.Scan(&i.ID, &i.VoucherType)
	return &i, err
}

const updateCustomerVoucher = `-- name: UpdateCustomerVoucher :exec
UPDATE customer_vouchers
SET
    is_used = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    customer_id = ?
    AND voucher_id = ?
`

type UpdateCustomerVoucherParams struct {
	IsUsed     bool   `json:"is_used"`
	CustomerID uint32 `json:"customer_id"`
	VoucherID  uint32 `json:"voucher_id"`
}

// UpdateCustomerVoucher
//
//	UPDATE customer_vouchers
//	SET
//	    is_used = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE
//	    customer_id = ?
//	    AND voucher_id = ?
func (q *Queries) UpdateCustomerVoucher(ctx context.Context, arg *UpdateCustomerVoucherParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerVoucher, arg.IsUsed, arg.CustomerID, arg.VoucherID)
	return err
}

const updateVoucherUsage = `-- name: UpdateVoucherUsage :exec
UPDATE vouchers
SET
    current_usage = current_usage + ?
WHERE
    voucher_code = ?
`

type UpdateVoucherUsageParams struct {
	IncrementBy int32  `json:"increment_by"`
	VoucherCode string `json:"voucher_code"`
}

// UpdateVoucherUsage
//
//	UPDATE vouchers
//	SET
//	    current_usage = current_usage + ?
//	WHERE
//	    voucher_code = ?
func (q *Queries) UpdateVoucherUsage(ctx context.Context, arg *UpdateVoucherUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucherUsage, arg.IncrementBy, arg.VoucherCode)
	return err
}
