// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webshop_brand.sql

package db

import (
	"context"
)

const getWebshopBrandById = `-- name: GetWebshopBrandById :one
SELECT id, brand_name, brand_code, domain, status, setup_status, has_multishop, default_shop, created_at, updated_at, loyalty_points_per_pound, pounds_per_point, loyalty_expire_date FROM webshop_brand WHERE id = ?
`

// GetWebshopBrandById
//
//	SELECT id, brand_name, brand_code, domain, status, setup_status, has_multishop, default_shop, created_at, updated_at, loyalty_points_per_pound, pounds_per_point, loyalty_expire_date FROM webshop_brand WHERE id = ?
func (q *Queries) GetWebshopBrandById(ctx context.Context, id uint32) (*WebshopBrand, error) {
	row := q.db.QueryRowContext(ctx, getWebshopBrandById, id)
	var i WebshopBrand
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.BrandCode,
		&i.Domain,
		&i.Status,
		&i.SetupStatus,
		&i.HasMultishop,
		&i.DefaultShop,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoyaltyPointsPerPound,
		&i.PoundsPerPoint,
		&i.LoyaltyExpireDate,
	)
	return &i, err
}
